// @generated by tools/py2rust from py-armodel models/M2 (see PY_ARMODEL_VERSION). Do not edit.

//! generated from spec package: m2::autosar_templates::diagnostic_extract::diagnostic_mapping::service_mapping

use slotmap::new_key_type;

new_key_type! {
    pub struct BswServiceDependencyIdentId;
    pub struct DiagnosticDemProvidedDataMappingId;
    pub struct DiagnosticFimFunctionMappingId;
    pub struct DiagnosticParameterElementAccessId;
    pub struct DiagnosticSecurityEventReportingModeMappingId;
    pub struct DiagnosticServiceDataMappingId;
    pub struct DiagnosticServiceSwMappingId;
}

use crate::m2::autosar_templates::diagnostic_extract::diagnostic_mapping::DiagnosticMapping;
use crate::m2::autosar_templates::diagnostic_extract::diagnostic_mapping::DiagnosticSwMapping;
use crate::m2::autosar_templates::generic_structure::general_template_classes::ar_object::ARObject;
use crate::m2::autosar_templates::generic_structure::general_template_classes::ar_object::ElementRef;
use crate::m2::autosar_templates::generic_structure::general_template_classes::identifiable::ShortNameFragmentId;
use crate::m2::autosar_templates::sw_component_template::rpt_scenario::IdentCaption;
use crate::m2::msr::asam_hdo::admin_data::AdminDataId;
use crate::m2::msr::documentation::annotation::AnnotationId;
use crate::m2::msr::documentation::text_model::block_elements::DocumentationBlockId;
use crate::m2::msr::documentation::text_model::multilanguage_data::MultiLanguageOverviewParagraphId;
use crate::m2::msr::documentation::text_model::multilanguage_data::MultilanguageLongNameId;
use crate::Document;

/// spec class `BswServiceDependencyIdent`
/// This meta-class is created to add the ability to become the target of a reference
/// to the non-Referrable BswServiceDependency.
#[derive(Debug, Default)]
pub struct BswServiceDependencyIdent {
    base: IdentCaption,
}

impl BswServiceDependencyIdent {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn base(&self) -> &IdentCaption {
        &self.base
    }

    pub fn base_mut(&mut self) -> &mut IdentCaption {
        &mut self.base
    }

    pub fn get_atp_features(&self) -> &[ElementRef] {
        self.base().base().base().get_atp_features()
    }

    pub fn push_atp_feature(&mut self, value: ElementRef) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .push_atp_feature(value)
    }

    pub fn get_admin_data(&self) -> Option<AdminDataId> {
        self.base().base().base().base().get_admin_data()
    }

    pub fn set_admin_data(&mut self, value: AdminDataId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_admin_data(value);
        self
    }

    pub fn remove_admin_data(&mut self) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .remove_admin_data();
        self
    }

    pub fn get_annotations(&self) -> &[AnnotationId] {
        self.base().base().base().base().get_annotations()
    }

    pub fn push_annotation(&mut self, value: AnnotationId) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .push_annotation(value)
    }

    pub fn get_category(&self) -> Option<&str> {
        self.base().base().base().base().get_category()
    }

    pub fn set_category(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_category(value);
        self
    }

    pub fn get_desc(&self) -> Option<MultiLanguageOverviewParagraphId> {
        self.base().base().base().base().get_desc()
    }

    pub fn set_desc(&mut self, value: MultiLanguageOverviewParagraphId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_desc(value);
        self
    }

    pub fn get_introduction(&self) -> Option<DocumentationBlockId> {
        self.base().base().base().base().get_introduction()
    }

    pub fn set_introduction(&mut self, value: DocumentationBlockId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_introduction(value);
        self
    }

    pub fn get_uuid(&self) -> Option<&str> {
        self.base().base().base().base().get_uuid()
    }

    pub fn set_uuid(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_uuid(value);
        self
    }

    pub fn get_elements(&self) -> &[ElementRef] {
        self.base().base().base().base().get_elements()
    }

    pub fn push_element(&mut self, value: ElementRef) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .push_element(value)
    }

    pub fn get_long_name(&self) -> Option<MultilanguageLongNameId> {
        self.base().base().base().base().base().get_long_name()
    }

    pub fn set_long_name(&mut self, value: MultilanguageLongNameId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_long_name(value);
        self
    }

    pub fn get_short_name_fragments(&self) -> &[ShortNameFragmentId] {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_short_name_fragments()
    }

    pub fn push_short_name_fragment(&mut self, value: ShortNameFragmentId) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .push_short_name_fragment(value)
    }

    pub fn get_short_name(&self) -> Option<&str> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_short_name()
    }

    pub fn set_short_name(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_short_name(value);
        self
    }

    pub fn get_checksum(&self) -> Option<&str> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_checksum()
    }

    pub fn set_checksum(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_checksum(value);
        self
    }

    pub fn get_timestamp(&self) -> Option<&str> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_timestamp()
    }

    pub fn set_timestamp(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_timestamp(value);
        self
    }

    pub fn get_parent(&self) -> Option<ElementRef> {
        self.base().base().base().base().base().base().get_parent()
    }

    pub fn set_parent(&mut self, parent: Option<ElementRef>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_parent(parent);
        self
    }
}

/// spec class `DiagnosticDemProvidedDataMapping`
#[derive(Debug, Default)]
pub struct DiagnosticDemProvidedDataMapping {
    base: DiagnosticMapping,
}

impl DiagnosticDemProvidedDataMapping {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn base(&self) -> &DiagnosticMapping {
        &self.base
    }

    pub fn base_mut(&mut self) -> &mut DiagnosticMapping {
        &mut self.base
    }

    pub fn get_provider_software_cluster_ref(&self) -> Option<&str> {
        self.base().get_provider_software_cluster_ref()
    }

    pub fn set_provider_software_cluster_ref(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_provider_software_cluster_ref(value);
        self
    }

    pub fn get_requester_software_cluster_ref(&self) -> Option<&str> {
        self.base().get_requester_software_cluster_ref()
    }

    pub fn set_requester_software_cluster_ref(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_requester_software_cluster_ref(value);
        self
    }

    pub fn get_admin_data(&self) -> Option<AdminDataId> {
        self.base().base().base().base().base().get_admin_data()
    }

    pub fn set_admin_data(&mut self, value: AdminDataId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_admin_data(value);
        self
    }

    pub fn remove_admin_data(&mut self) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .remove_admin_data();
        self
    }

    pub fn get_annotations(&self) -> &[AnnotationId] {
        self.base().base().base().base().base().get_annotations()
    }

    pub fn push_annotation(&mut self, value: AnnotationId) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .push_annotation(value)
    }

    pub fn get_category(&self) -> Option<&str> {
        self.base().base().base().base().base().get_category()
    }

    pub fn set_category(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_category(value);
        self
    }

    pub fn get_desc(&self) -> Option<MultiLanguageOverviewParagraphId> {
        self.base().base().base().base().base().get_desc()
    }

    pub fn set_desc(&mut self, value: MultiLanguageOverviewParagraphId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_desc(value);
        self
    }

    pub fn get_introduction(&self) -> Option<DocumentationBlockId> {
        self.base().base().base().base().base().get_introduction()
    }

    pub fn set_introduction(&mut self, value: DocumentationBlockId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_introduction(value);
        self
    }

    pub fn get_uuid(&self) -> Option<&str> {
        self.base().base().base().base().base().get_uuid()
    }

    pub fn set_uuid(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_uuid(value);
        self
    }

    pub fn get_elements(&self) -> &[ElementRef] {
        self.base().base().base().base().base().get_elements()
    }

    pub fn push_element(&mut self, value: ElementRef) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .push_element(value)
    }

    pub fn get_long_name(&self) -> Option<MultilanguageLongNameId> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_long_name()
    }

    pub fn set_long_name(&mut self, value: MultilanguageLongNameId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_long_name(value);
        self
    }

    pub fn get_short_name_fragments(&self) -> &[ShortNameFragmentId] {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_short_name_fragments()
    }

    pub fn push_short_name_fragment(&mut self, value: ShortNameFragmentId) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .push_short_name_fragment(value)
    }

    pub fn get_short_name(&self) -> Option<&str> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_short_name()
    }

    pub fn set_short_name(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_short_name(value);
        self
    }

    pub fn get_checksum(&self) -> Option<&str> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_checksum()
    }

    pub fn set_checksum(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_checksum(value);
        self
    }

    pub fn get_timestamp(&self) -> Option<&str> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_timestamp()
    }

    pub fn set_timestamp(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_timestamp(value);
        self
    }

    pub fn get_parent(&self) -> Option<ElementRef> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_parent()
    }

    pub fn set_parent(&mut self, parent: Option<ElementRef>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_parent(parent);
        self
    }
}

/// spec class `DiagnosticFimFunctionMapping`
#[derive(Debug, Default)]
pub struct DiagnosticFimFunctionMapping {
    base: ARObject,
}

impl DiagnosticFimFunctionMapping {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn base(&self) -> &ARObject {
        &self.base
    }

    pub fn base_mut(&mut self) -> &mut ARObject {
        &mut self.base
    }

    pub fn get_checksum(&self) -> Option<&str> {
        self.base().get_checksum()
    }

    pub fn set_checksum(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_checksum(value);
        self
    }

    pub fn get_timestamp(&self) -> Option<&str> {
        self.base().get_timestamp()
    }

    pub fn set_timestamp(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_timestamp(value);
        self
    }
}

/// spec class `DiagnosticParameterElementAccess`
#[derive(Debug, Default)]
pub struct DiagnosticParameterElementAccess {
    base: ARObject,
}

impl DiagnosticParameterElementAccess {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn base(&self) -> &ARObject {
        &self.base
    }

    pub fn base_mut(&mut self) -> &mut ARObject {
        &mut self.base
    }

    pub fn get_checksum(&self) -> Option<&str> {
        self.base().get_checksum()
    }

    pub fn set_checksum(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_checksum(value);
        self
    }

    pub fn get_timestamp(&self) -> Option<&str> {
        self.base().get_timestamp()
    }

    pub fn set_timestamp(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_timestamp(value);
        self
    }
}

/// spec class `DiagnosticSecurityEventReportingModeMapping`
#[derive(Debug, Default)]
pub struct DiagnosticSecurityEventReportingModeMapping {
    base: DiagnosticMapping,
}

impl DiagnosticSecurityEventReportingModeMapping {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn base(&self) -> &DiagnosticMapping {
        &self.base
    }

    pub fn base_mut(&mut self) -> &mut DiagnosticMapping {
        &mut self.base
    }

    pub fn get_provider_software_cluster_ref(&self) -> Option<&str> {
        self.base().get_provider_software_cluster_ref()
    }

    pub fn set_provider_software_cluster_ref(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_provider_software_cluster_ref(value);
        self
    }

    pub fn get_requester_software_cluster_ref(&self) -> Option<&str> {
        self.base().get_requester_software_cluster_ref()
    }

    pub fn set_requester_software_cluster_ref(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_requester_software_cluster_ref(value);
        self
    }

    pub fn get_admin_data(&self) -> Option<AdminDataId> {
        self.base().base().base().base().base().get_admin_data()
    }

    pub fn set_admin_data(&mut self, value: AdminDataId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_admin_data(value);
        self
    }

    pub fn remove_admin_data(&mut self) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .remove_admin_data();
        self
    }

    pub fn get_annotations(&self) -> &[AnnotationId] {
        self.base().base().base().base().base().get_annotations()
    }

    pub fn push_annotation(&mut self, value: AnnotationId) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .push_annotation(value)
    }

    pub fn get_category(&self) -> Option<&str> {
        self.base().base().base().base().base().get_category()
    }

    pub fn set_category(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_category(value);
        self
    }

    pub fn get_desc(&self) -> Option<MultiLanguageOverviewParagraphId> {
        self.base().base().base().base().base().get_desc()
    }

    pub fn set_desc(&mut self, value: MultiLanguageOverviewParagraphId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_desc(value);
        self
    }

    pub fn get_introduction(&self) -> Option<DocumentationBlockId> {
        self.base().base().base().base().base().get_introduction()
    }

    pub fn set_introduction(&mut self, value: DocumentationBlockId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_introduction(value);
        self
    }

    pub fn get_uuid(&self) -> Option<&str> {
        self.base().base().base().base().base().get_uuid()
    }

    pub fn set_uuid(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_uuid(value);
        self
    }

    pub fn get_elements(&self) -> &[ElementRef] {
        self.base().base().base().base().base().get_elements()
    }

    pub fn push_element(&mut self, value: ElementRef) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .push_element(value)
    }

    pub fn get_long_name(&self) -> Option<MultilanguageLongNameId> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_long_name()
    }

    pub fn set_long_name(&mut self, value: MultilanguageLongNameId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_long_name(value);
        self
    }

    pub fn get_short_name_fragments(&self) -> &[ShortNameFragmentId] {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_short_name_fragments()
    }

    pub fn push_short_name_fragment(&mut self, value: ShortNameFragmentId) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .push_short_name_fragment(value)
    }

    pub fn get_short_name(&self) -> Option<&str> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_short_name()
    }

    pub fn set_short_name(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_short_name(value);
        self
    }

    pub fn get_checksum(&self) -> Option<&str> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_checksum()
    }

    pub fn set_checksum(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_checksum(value);
        self
    }

    pub fn get_timestamp(&self) -> Option<&str> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_timestamp()
    }

    pub fn set_timestamp(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_timestamp(value);
        self
    }

    pub fn get_parent(&self) -> Option<ElementRef> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_parent()
    }

    pub fn set_parent(&mut self, parent: Option<ElementRef>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_parent(parent);
        self
    }
}

/// spec class `DiagnosticServiceDataMapping`
#[derive(Debug, Default)]
pub struct DiagnosticServiceDataMapping {
    base: DiagnosticSwMapping,
}

impl DiagnosticServiceDataMapping {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn base(&self) -> &DiagnosticSwMapping {
        &self.base
    }

    pub fn base_mut(&mut self) -> &mut DiagnosticSwMapping {
        &mut self.base
    }

    pub fn get_provider_software_cluster_ref(&self) -> Option<&str> {
        self.base().base().get_provider_software_cluster_ref()
    }

    pub fn set_provider_software_cluster_ref(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .set_provider_software_cluster_ref(value);
        self
    }

    pub fn get_requester_software_cluster_ref(&self) -> Option<&str> {
        self.base().base().get_requester_software_cluster_ref()
    }

    pub fn set_requester_software_cluster_ref(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .set_requester_software_cluster_ref(value);
        self
    }

    pub fn get_admin_data(&self) -> Option<AdminDataId> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_admin_data()
    }

    pub fn set_admin_data(&mut self, value: AdminDataId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_admin_data(value);
        self
    }

    pub fn remove_admin_data(&mut self) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .remove_admin_data();
        self
    }

    pub fn get_annotations(&self) -> &[AnnotationId] {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_annotations()
    }

    pub fn push_annotation(&mut self, value: AnnotationId) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .push_annotation(value)
    }

    pub fn get_category(&self) -> Option<&str> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_category()
    }

    pub fn set_category(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_category(value);
        self
    }

    pub fn get_desc(&self) -> Option<MultiLanguageOverviewParagraphId> {
        self.base().base().base().base().base().base().get_desc()
    }

    pub fn set_desc(&mut self, value: MultiLanguageOverviewParagraphId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_desc(value);
        self
    }

    pub fn get_introduction(&self) -> Option<DocumentationBlockId> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_introduction()
    }

    pub fn set_introduction(&mut self, value: DocumentationBlockId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_introduction(value);
        self
    }

    pub fn get_uuid(&self) -> Option<&str> {
        self.base().base().base().base().base().base().get_uuid()
    }

    pub fn set_uuid(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_uuid(value);
        self
    }

    pub fn get_elements(&self) -> &[ElementRef] {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_elements()
    }

    pub fn push_element(&mut self, value: ElementRef) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .push_element(value)
    }

    pub fn get_long_name(&self) -> Option<MultilanguageLongNameId> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_long_name()
    }

    pub fn set_long_name(&mut self, value: MultilanguageLongNameId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_long_name(value);
        self
    }

    pub fn get_short_name_fragments(&self) -> &[ShortNameFragmentId] {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_short_name_fragments()
    }

    pub fn push_short_name_fragment(&mut self, value: ShortNameFragmentId) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .push_short_name_fragment(value)
    }

    pub fn get_short_name(&self) -> Option<&str> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_short_name()
    }

    pub fn set_short_name(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_short_name(value);
        self
    }

    pub fn get_checksum(&self) -> Option<&str> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_checksum()
    }

    pub fn set_checksum(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_checksum(value);
        self
    }

    pub fn get_timestamp(&self) -> Option<&str> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_timestamp()
    }

    pub fn set_timestamp(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_timestamp(value);
        self
    }

    pub fn get_parent(&self) -> Option<ElementRef> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_parent()
    }

    pub fn set_parent(&mut self, parent: Option<ElementRef>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_parent(parent);
        self
    }
}

/// spec class `DiagnosticServiceMappingDiagTarget` (abstract)
#[derive(Debug, Default)]
pub struct DiagnosticServiceMappingDiagTarget {
    base: ARObject,
}

impl DiagnosticServiceMappingDiagTarget {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn base(&self) -> &ARObject {
        &self.base
    }

    pub fn base_mut(&mut self) -> &mut ARObject {
        &mut self.base
    }

    pub fn get_checksum(&self) -> Option<&str> {
        self.base().get_checksum()
    }

    pub fn set_checksum(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_checksum(value);
        self
    }

    pub fn get_timestamp(&self) -> Option<&str> {
        self.base().get_timestamp()
    }

    pub fn set_timestamp(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_timestamp(value);
        self
    }
}

/// spec class `DiagnosticServiceSwMapping`
#[derive(Debug, Default)]
pub struct DiagnosticServiceSwMapping {
    base: ARObject,
}

impl DiagnosticServiceSwMapping {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn base(&self) -> &ARObject {
        &self.base
    }

    pub fn base_mut(&mut self) -> &mut ARObject {
        &mut self.base
    }

    pub fn get_checksum(&self) -> Option<&str> {
        self.base().get_checksum()
    }

    pub fn set_checksum(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_checksum(value);
        self
    }

    pub fn get_timestamp(&self) -> Option<&str> {
        self.base().get_timestamp()
    }

    pub fn set_timestamp(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_timestamp(value);
        self
    }
}

impl Document {
    pub(crate) fn compare_bsw_service_dependency_ident(
        &self,
        other: &Document,
        a: &BswServiceDependencyIdent,
        b: &BswServiceDependencyIdent,
        path: &str,
    ) -> Result<(), String> {
        self.compare_ident_caption(other, a.base(), b.base(), path)?;
        Ok(())
    }

    pub(crate) fn compare_diagnostic_dem_provided_data_mapping(
        &self,
        other: &Document,
        a: &DiagnosticDemProvidedDataMapping,
        b: &DiagnosticDemProvidedDataMapping,
        path: &str,
    ) -> Result<(), String> {
        self.compare_diagnostic_mapping(other, a.base(), b.base(), path)?;
        Ok(())
    }

    pub(crate) fn compare_diagnostic_fim_function_mapping(
        &self,
        _other: &Document,
        a: &DiagnosticFimFunctionMapping,
        b: &DiagnosticFimFunctionMapping,
        path: &str,
    ) -> Result<(), String> {
        Self::compare_ar_object(a.base(), b.base(), path)?;
        Ok(())
    }

    pub(crate) fn compare_diagnostic_parameter_element_access(
        &self,
        _other: &Document,
        a: &DiagnosticParameterElementAccess,
        b: &DiagnosticParameterElementAccess,
        path: &str,
    ) -> Result<(), String> {
        Self::compare_ar_object(a.base(), b.base(), path)?;
        Ok(())
    }

    pub(crate) fn compare_diagnostic_security_event_reporting_mode_mapping(
        &self,
        other: &Document,
        a: &DiagnosticSecurityEventReportingModeMapping,
        b: &DiagnosticSecurityEventReportingModeMapping,
        path: &str,
    ) -> Result<(), String> {
        self.compare_diagnostic_mapping(other, a.base(), b.base(), path)?;
        Ok(())
    }

    pub(crate) fn compare_diagnostic_service_data_mapping(
        &self,
        other: &Document,
        a: &DiagnosticServiceDataMapping,
        b: &DiagnosticServiceDataMapping,
        path: &str,
    ) -> Result<(), String> {
        self.compare_diagnostic_sw_mapping(other, a.base(), b.base(), path)?;
        Ok(())
    }

    pub(crate) fn compare_diagnostic_service_mapping_diag_target(
        &self,
        _other: &Document,
        a: &DiagnosticServiceMappingDiagTarget,
        b: &DiagnosticServiceMappingDiagTarget,
        path: &str,
    ) -> Result<(), String> {
        Self::compare_ar_object(a.base(), b.base(), path)?;
        Ok(())
    }

    pub(crate) fn compare_diagnostic_service_sw_mapping(
        &self,
        _other: &Document,
        a: &DiagnosticServiceSwMapping,
        b: &DiagnosticServiceSwMapping,
        path: &str,
    ) -> Result<(), String> {
        Self::compare_ar_object(a.base(), b.base(), path)?;
        Ok(())
    }
}
