// @generated by tools/py2rust from py-armodel models/M2 (see PY_ARMODEL_VERSION). Do not edit.

//! generated from spec package: m2::autosar_templates::diagnostic_extract::dcm::diagnostic_service::ecu_reset

use slotmap::new_key_type;

new_key_type! {
    pub struct DiagnosticEcuResetId;
    pub struct DiagnosticEcuResetClassId;
}

use crate::m2::autosar_templates::diagnostic_extract::dcm::diagnostic_service::common_service::DiagnosticServiceClass;
use crate::m2::autosar_templates::generic_structure::general_template_classes::ar_object::ElementRef;
use crate::m2::autosar_templates::generic_structure::general_template_classes::ar_package::ARElement;
use crate::m2::autosar_templates::generic_structure::general_template_classes::identifiable::ShortNameFragmentId;
use crate::m2::msr::asam_hdo::admin_data::AdminDataId;
use crate::m2::msr::documentation::annotation::AnnotationId;
use crate::m2::msr::documentation::text_model::block_elements::DocumentationBlockId;
use crate::m2::msr::documentation::text_model::multilanguage_data::MultiLanguageOverviewParagraphId;
use crate::m2::msr::documentation::text_model::multilanguage_data::MultilanguageLongNameId;
use crate::Document;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DiagnosticResponseToEcuResetEnum {
    RespondAfterReset,
    RespondBeforeReset,
}

impl DiagnosticResponseToEcuResetEnum {
    pub fn as_str(&self) -> &'static str {
        match self {
            DiagnosticResponseToEcuResetEnum::RespondAfterReset => "respondAfterReset",
            DiagnosticResponseToEcuResetEnum::RespondBeforeReset => "respondBeforeReset",
        }
    }
}

impl TryFrom<&str> for DiagnosticResponseToEcuResetEnum {
    type Error = ();

    fn try_from(value: &str) -> Result<Self, ()> {
        match value {
            "respondAfterReset" => Ok(DiagnosticResponseToEcuResetEnum::RespondAfterReset),
            "respondBeforeReset" => Ok(DiagnosticResponseToEcuResetEnum::RespondBeforeReset),
            _ => Err(()),
        }
    }
}

/// spec class `DiagnosticEcuReset`
/// This represents an instance of the "ECU Reset" diagnostic service.
#[derive(Debug, Default)]
pub struct DiagnosticEcuReset {
    base: ARElement,
    custom_sub_function_number: Option<String>,
    ecu_reset_class: Option<String>,
}

impl DiagnosticEcuReset {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn base(&self) -> &ARElement {
        &self.base
    }

    pub fn base_mut(&mut self) -> &mut ARElement {
        &mut self.base
    }

    pub fn get_custom_sub_function_number(&self) -> Option<&str> {
        self.custom_sub_function_number.as_deref()
    }

    pub fn set_custom_sub_function_number(&mut self, value: impl Into<String>) -> &mut Self {
        self.custom_sub_function_number = Some(value.into());
        self
    }

    pub fn get_ecu_reset_class(&self) -> Option<&str> {
        self.ecu_reset_class.as_deref()
    }

    pub fn set_ecu_reset_class(&mut self, value: impl Into<String>) -> &mut Self {
        self.ecu_reset_class = Some(value.into());
        self
    }

    pub fn get_admin_data(&self) -> Option<AdminDataId> {
        self.base().base().base().base().get_admin_data()
    }

    pub fn set_admin_data(&mut self, value: AdminDataId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_admin_data(value);
        self
    }

    pub fn get_annotations(&self) -> &[AnnotationId] {
        self.base().base().base().base().get_annotations()
    }

    pub fn push_annotation(&mut self, value: AnnotationId) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .push_annotation(value)
    }

    pub fn get_category(&self) -> Option<&str> {
        self.base().base().base().base().get_category()
    }

    pub fn set_category(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_category(value);
        self
    }

    pub fn get_desc(&self) -> Option<MultiLanguageOverviewParagraphId> {
        self.base().base().base().base().get_desc()
    }

    pub fn set_desc(&mut self, value: MultiLanguageOverviewParagraphId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_desc(value);
        self
    }

    pub fn get_introduction(&self) -> Option<DocumentationBlockId> {
        self.base().base().base().base().get_introduction()
    }

    pub fn set_introduction(&mut self, value: DocumentationBlockId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_introduction(value);
        self
    }

    pub fn get_uuid(&self) -> Option<&str> {
        self.base().base().base().base().get_uuid()
    }

    pub fn set_uuid(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_uuid(value);
        self
    }

    pub fn get_elements(&self) -> &[ElementRef] {
        self.base().base().base().base().get_elements()
    }

    pub fn push_element(&mut self, value: ElementRef) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .push_element(value)
    }

    pub fn get_long_name(&self) -> Option<MultilanguageLongNameId> {
        self.base().base().base().base().base().get_long_name()
    }

    pub fn set_long_name(&mut self, value: MultilanguageLongNameId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_long_name(value);
        self
    }

    pub fn get_short_name_fragments(&self) -> &[ShortNameFragmentId] {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_short_name_fragments()
    }

    pub fn push_short_name_fragment(&mut self, value: ShortNameFragmentId) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .push_short_name_fragment(value)
    }

    pub fn get_short_name(&self) -> Option<&str> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_short_name()
    }

    pub fn set_short_name(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_short_name(value);
        self
    }

    pub fn get_checksum(&self) -> Option<&str> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_checksum()
    }

    pub fn set_checksum(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_checksum(value);
        self
    }

    pub fn get_timestamp(&self) -> Option<&str> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_timestamp()
    }

    pub fn set_timestamp(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_timestamp(value);
        self
    }

    pub fn get_parent(&self) -> Option<ElementRef> {
        self.base().base().base().base().base().base().get_parent()
    }

    pub fn set_parent(&mut self, parent: Option<ElementRef>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_parent(parent);
        self
    }
}

/// spec class `DiagnosticEcuResetClass`
/// This meta-class contains attributes shared by all instances of the "Ecu Reset" diagnostic service.
#[derive(Debug, Default)]
pub struct DiagnosticEcuResetClass {
    base: DiagnosticServiceClass,
    respond_to_reset: Option<DiagnosticResponseToEcuResetEnum>,
}

impl DiagnosticEcuResetClass {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn base(&self) -> &DiagnosticServiceClass {
        &self.base
    }

    pub fn base_mut(&mut self) -> &mut DiagnosticServiceClass {
        &mut self.base
    }

    pub fn get_respond_to_reset(&self) -> Option<DiagnosticResponseToEcuResetEnum> {
        self.respond_to_reset
    }

    pub fn set_respond_to_reset(&mut self, value: DiagnosticResponseToEcuResetEnum) -> &mut Self {
        self.respond_to_reset = Some(value);
        self
    }

    pub fn get_admin_data(&self) -> Option<AdminDataId> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_admin_data()
    }

    pub fn set_admin_data(&mut self, value: AdminDataId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_admin_data(value);
        self
    }

    pub fn get_annotations(&self) -> &[AnnotationId] {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_annotations()
    }

    pub fn push_annotation(&mut self, value: AnnotationId) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .push_annotation(value)
    }

    pub fn get_category(&self) -> Option<&str> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_category()
    }

    pub fn set_category(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_category(value);
        self
    }

    pub fn get_desc(&self) -> Option<MultiLanguageOverviewParagraphId> {
        self.base().base().base().base().base().base().get_desc()
    }

    pub fn set_desc(&mut self, value: MultiLanguageOverviewParagraphId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_desc(value);
        self
    }

    pub fn get_introduction(&self) -> Option<DocumentationBlockId> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_introduction()
    }

    pub fn set_introduction(&mut self, value: DocumentationBlockId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_introduction(value);
        self
    }

    pub fn get_uuid(&self) -> Option<&str> {
        self.base().base().base().base().base().base().get_uuid()
    }

    pub fn set_uuid(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_uuid(value);
        self
    }

    pub fn get_elements(&self) -> &[ElementRef] {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_elements()
    }

    pub fn push_element(&mut self, value: ElementRef) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .push_element(value)
    }

    pub fn get_long_name(&self) -> Option<MultilanguageLongNameId> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_long_name()
    }

    pub fn set_long_name(&mut self, value: MultilanguageLongNameId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_long_name(value);
        self
    }

    pub fn get_short_name_fragments(&self) -> &[ShortNameFragmentId] {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_short_name_fragments()
    }

    pub fn push_short_name_fragment(&mut self, value: ShortNameFragmentId) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .push_short_name_fragment(value)
    }

    pub fn get_short_name(&self) -> Option<&str> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_short_name()
    }

    pub fn set_short_name(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_short_name(value);
        self
    }

    pub fn get_checksum(&self) -> Option<&str> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_checksum()
    }

    pub fn set_checksum(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_checksum(value);
        self
    }

    pub fn get_timestamp(&self) -> Option<&str> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_timestamp()
    }

    pub fn set_timestamp(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_timestamp(value);
        self
    }

    pub fn get_parent(&self) -> Option<ElementRef> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_parent()
    }

    pub fn set_parent(&mut self, parent: Option<ElementRef>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_parent(parent);
        self
    }
}

impl Document {
    pub(crate) fn compare_diagnostic_ecu_reset(
        &self,
        other: &Document,
        a: &DiagnosticEcuReset,
        b: &DiagnosticEcuReset,
        path: &str,
    ) -> Result<(), String> {
        self.compare_ar_element(other, a.base(), b.base(), path)?;
        if a.get_custom_sub_function_number() != b.get_custom_sub_function_number() {
            return Err(format!("{path}: CUSTOM_SUB_FUNCTION_NUMBER mismatch"));
        }
        if a.get_ecu_reset_class() != b.get_ecu_reset_class() {
            return Err(format!("{path}: ECU_RESET_CLASS mismatch"));
        }
        Ok(())
    }

    pub(crate) fn compare_diagnostic_ecu_reset_class(
        &self,
        other: &Document,
        a: &DiagnosticEcuResetClass,
        b: &DiagnosticEcuResetClass,
        path: &str,
    ) -> Result<(), String> {
        self.compare_diagnostic_service_class(other, a.base(), b.base(), path)?;
        if a.get_respond_to_reset() != b.get_respond_to_reset() {
            return Err(format!("{path}: RESPOND_TO_RESET mismatch"));
        }
        Ok(())
    }
}
