// @generated by tools/py2rust from py-armodel models/M2 (see PY_ARMODEL_VERSION). Do not edit.

//! generated from spec package: m2::msr::documentation::text_model::multilanguage_data

use slotmap::new_key_type;

new_key_type! {
    pub struct MultiLanguageOverviewParagraphId;
    pub struct MultiLanguageParagraphId;
    pub struct MultiLanguagePlainTextId;
    pub struct MultiLanguageVerbatimId;
    pub struct MultilanguageLongNameId;
}

use crate::m2::autosar_templates::generic_structure::general_template_classes::ar_object::ARObject;
use crate::m2::autosar_templates::generic_structure::general_template_classes::stereotype_mixins::VariationPointCapable;
use crate::m2::autosar_templates::generic_structure::variant_handling::VariationPointId;
use crate::m2::msr::documentation::block_elements::oasis_exchange_table::FloatEnum;
use crate::m2::msr::documentation::block_elements::oasis_exchange_table::PgwideEnum;
use crate::m2::msr::documentation::block_elements::pagination_and_view::ChapterEnumBreak;
use crate::m2::msr::documentation::block_elements::pagination_and_view::KeepWithPreviousEnum;
use crate::m2::msr::documentation::block_elements::pagination_and_view::Paginateable;
use crate::m2::msr::documentation::text_model::language_data_model::LLongNameId;
use crate::m2::msr::documentation::text_model::language_data_model::LOverviewParagraphId;
use crate::m2::msr::documentation::text_model::language_data_model::LParagraphId;
use crate::m2::msr::documentation::text_model::language_data_model::LPlainTextId;
use crate::m2::msr::documentation::text_model::language_data_model::LVerbatimId;
use crate::Document;

/// spec class `MultiLanguageOverviewParagraph`
/// This is the content of a multilingual paragraph in an overview item.
#[derive(Debug, Default)]
pub struct MultiLanguageOverviewParagraph {
    base: ARObject,
    l2: Vec<LOverviewParagraphId>,
}

impl MultiLanguageOverviewParagraph {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn base(&self) -> &ARObject {
        &self.base
    }

    pub fn base_mut(&mut self) -> &mut ARObject {
        &mut self.base
    }

    pub fn get_l2(&self) -> &[LOverviewParagraphId] {
        &self.l2
    }

    pub fn push_l2(&mut self, value: LOverviewParagraphId) {
        self.l2.push(value);
    }

    pub fn get_checksum(&self) -> Option<&str> {
        self.base().get_checksum()
    }

    pub fn set_checksum(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_checksum(value);
        self
    }

    pub fn get_timestamp(&self) -> Option<&str> {
        self.base().get_timestamp()
    }

    pub fn set_timestamp(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_timestamp(value);
        self
    }
}

/// spec class `MultiLanguageParagraph`
/// This is the content model of a multilingual paragraph in a documentation.
#[derive(Debug, Default)]
pub struct MultiLanguageParagraph {
    base: Paginateable,
    help_entry: Option<String>,
    l1: Vec<LParagraphId>,
}

impl MultiLanguageParagraph {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn base(&self) -> &Paginateable {
        &self.base
    }

    pub fn base_mut(&mut self) -> &mut Paginateable {
        &mut self.base
    }

    pub fn get_help_entry(&self) -> Option<&str> {
        self.help_entry.as_deref()
    }

    pub fn set_help_entry(&mut self, value: impl Into<String>) -> &mut Self {
        self.help_entry = Some(value.into());
        self
    }

    pub fn get_l1(&self) -> &[LParagraphId] {
        &self.l1
    }

    pub fn push_l1(&mut self, value: LParagraphId) {
        self.l1.push(value);
    }

    pub fn get_chapter_break(&self) -> Option<ChapterEnumBreak> {
        self.base().get_chapter_break()
    }

    pub fn set_chapter_break(&mut self, value: ChapterEnumBreak) -> &mut Self {
        self.base_mut().set_chapter_break(value);
        self
    }

    pub fn get_keep_with_previous(&self) -> Option<KeepWithPreviousEnum> {
        self.base().get_keep_with_previous()
    }

    pub fn set_keep_with_previous(&mut self, value: KeepWithPreviousEnum) -> &mut Self {
        self.base_mut().set_keep_with_previous(value);
        self
    }

    pub fn get_si(&self) -> Option<&str> {
        self.base().base().get_si()
    }

    pub fn set_si(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().base_mut().set_si(value);
        self
    }

    pub fn get_view(&self) -> Option<&str> {
        self.base().base().get_view()
    }

    pub fn set_view(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().base_mut().set_view(value);
        self
    }

    pub fn get_checksum(&self) -> Option<&str> {
        self.base().base().base().get_checksum()
    }

    pub fn set_checksum(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().base_mut().base_mut().set_checksum(value);
        self
    }

    pub fn get_timestamp(&self) -> Option<&str> {
        self.base().base().base().get_timestamp()
    }

    pub fn set_timestamp(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().base_mut().base_mut().set_timestamp(value);
        self
    }
}

/// spec class `MultiLanguagePlainText`
/// This is a multilingual plaint Text. It is intended to be rendered as a paragraph.
#[derive(Debug, Default)]
pub struct MultiLanguagePlainText {
    base: ARObject,
    l10s: Vec<LPlainTextId>,
}

impl MultiLanguagePlainText {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn base(&self) -> &ARObject {
        &self.base
    }

    pub fn base_mut(&mut self) -> &mut ARObject {
        &mut self.base
    }

    pub fn get_l10s(&self) -> &[LPlainTextId] {
        &self.l10s
    }

    pub fn push_l10(&mut self, value: LPlainTextId) {
        self.l10s.push(value);
    }

    pub fn get_checksum(&self) -> Option<&str> {
        self.base().get_checksum()
    }

    pub fn set_checksum(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_checksum(value);
        self
    }

    pub fn get_timestamp(&self) -> Option<&str> {
        self.base().get_timestamp()
    }

    pub fn set_timestamp(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_timestamp(value);
        self
    }
}

/// spec class `MultiLanguageVerbatim`
/// This class represents multilingual Verbatim. Verbatim means, that white-space is maintained. When Verbatim is rendered in PDF or Online media, white-space is obeyed. Blanks are rendered as well as newline characters.
#[derive(Debug, Default)]
pub struct MultiLanguageVerbatim {
    base: Paginateable,
    variation_point_capable: VariationPointCapable,
    allow_break: Option<String>,
    float: Option<FloatEnum>,
    help_entry: Option<String>,
    l5s: Vec<LVerbatimId>,
    pgwide: Option<PgwideEnum>,
}

impl MultiLanguageVerbatim {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn base(&self) -> &Paginateable {
        &self.base
    }

    pub fn base_mut(&mut self) -> &mut Paginateable {
        &mut self.base
    }

    pub fn variation_point_capable(&self) -> &VariationPointCapable {
        &self.variation_point_capable
    }

    pub fn variation_point_capable_mut(&mut self) -> &mut VariationPointCapable {
        &mut self.variation_point_capable
    }

    pub fn get_allow_break(&self) -> Option<&str> {
        self.allow_break.as_deref()
    }

    pub fn set_allow_break(&mut self, value: impl Into<String>) -> &mut Self {
        self.allow_break = Some(value.into());
        self
    }

    pub fn get_float(&self) -> Option<FloatEnum> {
        self.float
    }

    pub fn set_float(&mut self, value: FloatEnum) -> &mut Self {
        self.float = Some(value);
        self
    }

    pub fn get_help_entry(&self) -> Option<&str> {
        self.help_entry.as_deref()
    }

    pub fn set_help_entry(&mut self, value: impl Into<String>) -> &mut Self {
        self.help_entry = Some(value.into());
        self
    }

    pub fn get_l5s(&self) -> &[LVerbatimId] {
        &self.l5s
    }

    pub fn push_l5(&mut self, value: LVerbatimId) {
        self.l5s.push(value);
    }

    pub fn get_pgwide(&self) -> Option<PgwideEnum> {
        self.pgwide
    }

    pub fn set_pgwide(&mut self, value: PgwideEnum) -> &mut Self {
        self.pgwide = Some(value);
        self
    }

    pub fn get_chapter_break(&self) -> Option<ChapterEnumBreak> {
        self.base().get_chapter_break()
    }

    pub fn set_chapter_break(&mut self, value: ChapterEnumBreak) -> &mut Self {
        self.base_mut().set_chapter_break(value);
        self
    }

    pub fn get_keep_with_previous(&self) -> Option<KeepWithPreviousEnum> {
        self.base().get_keep_with_previous()
    }

    pub fn set_keep_with_previous(&mut self, value: KeepWithPreviousEnum) -> &mut Self {
        self.base_mut().set_keep_with_previous(value);
        self
    }

    pub fn get_si(&self) -> Option<&str> {
        self.base().base().get_si()
    }

    pub fn set_si(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().base_mut().set_si(value);
        self
    }

    pub fn get_view(&self) -> Option<&str> {
        self.base().base().get_view()
    }

    pub fn set_view(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().base_mut().set_view(value);
        self
    }

    pub fn get_checksum(&self) -> Option<&str> {
        self.base().base().base().get_checksum()
    }

    pub fn set_checksum(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().base_mut().base_mut().set_checksum(value);
        self
    }

    pub fn get_timestamp(&self) -> Option<&str> {
        self.base().base().base().get_timestamp()
    }

    pub fn set_timestamp(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().base_mut().base_mut().set_timestamp(value);
        self
    }

    pub fn get_variation_point(&self) -> Option<VariationPointId> {
        self.variation_point_capable().get_variation_point()
    }

    pub fn set_variation_point(&mut self, value: VariationPointId) -> &mut Self {
        self.variation_point_capable_mut()
            .set_variation_point(value);
        self
    }
}

/// spec class `MultilanguageLongName`
/// This meta-class represents the ability to specify a long name which acts in the role of a headline. It is intended for human readers. Per language it should be around max 80 characters.
#[derive(Debug, Default)]
pub struct MultilanguageLongName {
    base: ARObject,
    l4: Vec<LLongNameId>,
}

impl MultilanguageLongName {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn base(&self) -> &ARObject {
        &self.base
    }

    pub fn base_mut(&mut self) -> &mut ARObject {
        &mut self.base
    }

    pub fn get_l4(&self) -> &[LLongNameId] {
        &self.l4
    }

    pub fn push_l4(&mut self, value: LLongNameId) {
        self.l4.push(value);
    }

    pub fn get_checksum(&self) -> Option<&str> {
        self.base().get_checksum()
    }

    pub fn set_checksum(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_checksum(value);
        self
    }

    pub fn get_timestamp(&self) -> Option<&str> {
        self.base().get_timestamp()
    }

    pub fn set_timestamp(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_timestamp(value);
        self
    }
}

impl Document {
    pub(crate) fn compare_multi_language_overview_paragraph(
        &self,
        other: &Document,
        a: &MultiLanguageOverviewParagraph,
        b: &MultiLanguageOverviewParagraph,
        path: &str,
    ) -> Result<(), String> {
        Self::compare_ar_object(a.base(), b.base(), path)?;
        let list_a = a.get_l2();
        let list_b = b.get_l2();
        if list_a.len() != list_b.len() {
            return Err(format!("{path}: L2 length mismatch"));
        }
        for (index, (x, y)) in list_a.iter().zip(list_b.iter()).enumerate() {
            let x = self
                .l_overview_paragraphs
                .get(*x)
                .ok_or_else(|| format!("{path}.L2[{index}]: id not found in own arena"))?;
            let y = other
                .l_overview_paragraphs
                .get(*y)
                .ok_or_else(|| format!("{path}.L2[{index}]: id not found in other arena"))?;
            self.compare_l_overview_paragraph(other, x, y, &format!("{path}.L2[{index}]"))?;
        }
        Ok(())
    }

    pub(crate) fn compare_multi_language_paragraph(
        &self,
        other: &Document,
        a: &MultiLanguageParagraph,
        b: &MultiLanguageParagraph,
        path: &str,
    ) -> Result<(), String> {
        self.compare_paginateable(other, a.base(), b.base(), path)?;
        if a.get_help_entry() != b.get_help_entry() {
            return Err(format!("{path}: HELP_ENTRY mismatch"));
        }
        let list_a = a.get_l1();
        let list_b = b.get_l1();
        if list_a.len() != list_b.len() {
            return Err(format!("{path}: L1 length mismatch"));
        }
        for (index, (x, y)) in list_a.iter().zip(list_b.iter()).enumerate() {
            let x = self
                .l_paragraphs
                .get(*x)
                .ok_or_else(|| format!("{path}.L1[{index}]: id not found in own arena"))?;
            let y = other
                .l_paragraphs
                .get(*y)
                .ok_or_else(|| format!("{path}.L1[{index}]: id not found in other arena"))?;
            self.compare_l_paragraph(other, x, y, &format!("{path}.L1[{index}]"))?;
        }
        Ok(())
    }

    pub(crate) fn compare_multi_language_plain_text(
        &self,
        other: &Document,
        a: &MultiLanguagePlainText,
        b: &MultiLanguagePlainText,
        path: &str,
    ) -> Result<(), String> {
        Self::compare_ar_object(a.base(), b.base(), path)?;
        let list_a = a.get_l10s();
        let list_b = b.get_l10s();
        if list_a.len() != list_b.len() {
            return Err(format!("{path}: L10S length mismatch"));
        }
        for (index, (x, y)) in list_a.iter().zip(list_b.iter()).enumerate() {
            let x = self
                .l_plain_texts
                .get(*x)
                .ok_or_else(|| format!("{path}.L10S[{index}]: id not found in own arena"))?;
            let y = other
                .l_plain_texts
                .get(*y)
                .ok_or_else(|| format!("{path}.L10S[{index}]: id not found in other arena"))?;
            self.compare_l_plain_text(other, x, y, &format!("{path}.L10S[{index}]"))?;
        }
        Ok(())
    }

    pub(crate) fn compare_multi_language_verbatim(
        &self,
        other: &Document,
        a: &MultiLanguageVerbatim,
        b: &MultiLanguageVerbatim,
        path: &str,
    ) -> Result<(), String> {
        self.compare_paginateable(other, a.base(), b.base(), path)?;
        self.compare_variation_point_capable(
            other,
            a.variation_point_capable(),
            b.variation_point_capable(),
            path,
        )?;
        if a.get_allow_break() != b.get_allow_break() {
            return Err(format!("{path}: ALLOW_BREAK mismatch"));
        }
        if a.get_float() != b.get_float() {
            return Err(format!("{path}: FLOAT mismatch"));
        }
        if a.get_help_entry() != b.get_help_entry() {
            return Err(format!("{path}: HELP_ENTRY mismatch"));
        }
        let list_a = a.get_l5s();
        let list_b = b.get_l5s();
        if list_a.len() != list_b.len() {
            return Err(format!("{path}: L5S length mismatch"));
        }
        for (index, (x, y)) in list_a.iter().zip(list_b.iter()).enumerate() {
            let x = self
                .l_verbatims
                .get(*x)
                .ok_or_else(|| format!("{path}.L5S[{index}]: id not found in own arena"))?;
            let y = other
                .l_verbatims
                .get(*y)
                .ok_or_else(|| format!("{path}.L5S[{index}]: id not found in other arena"))?;
            self.compare_l_verbatim(other, x, y, &format!("{path}.L5S[{index}]"))?;
        }
        if a.get_pgwide() != b.get_pgwide() {
            return Err(format!("{path}: PGWIDE mismatch"));
        }
        Ok(())
    }

    pub(crate) fn compare_multilanguage_long_name(
        &self,
        other: &Document,
        a: &MultilanguageLongName,
        b: &MultilanguageLongName,
        path: &str,
    ) -> Result<(), String> {
        Self::compare_ar_object(a.base(), b.base(), path)?;
        let list_a = a.get_l4();
        let list_b = b.get_l4();
        if list_a.len() != list_b.len() {
            return Err(format!("{path}: L4 length mismatch"));
        }
        for (index, (x, y)) in list_a.iter().zip(list_b.iter()).enumerate() {
            let x = self
                .l_long_names
                .get(*x)
                .ok_or_else(|| format!("{path}.L4[{index}]: id not found in own arena"))?;
            let y = other
                .l_long_names
                .get(*y)
                .ok_or_else(|| format!("{path}.L4[{index}]: id not found in other arena"))?;
            self.compare_l_long_name(other, x, y, &format!("{path}.L4[{index}]"))?;
        }
        Ok(())
    }
}
