"""Emit one rust module file: imports, enums, structs, key types, accessors, forwarders.

Generated classes forward every inherited accessor through the base chain
(py subclasses inherit getX/setX; docs/code_guide.md §3 requires the public
API to match py-armodel 1:1). Setters/pushers go through base_mut() paths,
getters through base() paths.
"""
from __future__ import annotations

import templates
from ir import ClassIr, FieldIr, Ir, snake_case
from overrides import Overrides
from placement import Placement, py_module_segments
from typemap import RustField, map_field

BANNER = "// @generated by tools/py2rust from py-armodel models/M2 (see PY_ARMODEL_VERSION). Do not edit.\n"


def enum_variant_name(literal: str) -> str:
    name = "".join(part.capitalize() for part in literal.lower().split("_"))
    if not name[:1].isalpha():
        # rust identifiers cannot start with a digit — `1000baseT1` and
        # `100baseT1` would even collide after rustc's digit stripping
        return "X" + name
    return name


def _emit_enum(cls: ClassIr) -> str:
    lines = [
        "#[derive(Debug, Clone, Copy, PartialEq, Eq)]",
        f"pub enum {cls.name} {{",
    ]
    lines += [f"    {enum_variant_name(l.name)}," for l in cls.enum_literals]
    lines += ["}"]
    if not cls.enum_literals:
        # upstream placeholder enums (py `class X(AREnum): pass`) have no
        # literals; a match over a zero-variant enum is E0004
        return "\n".join(lines)
    lines += ["", f"impl {cls.name} {{", "    pub fn as_str(&self) -> &'static str {", "        match self {"]
    lines += [f'            {cls.name}::{enum_variant_name(l.name)} => "{l.value}",' for l in cls.enum_literals]
    lines += ["        }", "    }", "}", "",
              f"impl TryFrom<&str> for {cls.name} {{", "    type Error = ();", "",
              # enums with an `Error` literal make `Self::Error` ambiguous
              "    fn try_from(value: &str) -> Result<Self, ()> {", "        match value {"]
    lines += [f'            "{l.value}" => Ok({cls.name}::{enum_variant_name(l.name)}),' for l in cls.enum_literals]
    lines += ["            _ => Err(()),", "        }", "    }", "}"]
    return "\n".join(lines)



def method_stem(rust_name: str) -> str:
    """Field identifiers escape rust keywords (r#type); method names use the bare stem."""
    return rust_name[2:] if rust_name.startswith("r#") else rust_name


def push_method_name(rust_name: str) -> str:
    """P0 pusher convention: strip one trailing 's' from the snake_case field
    (py `sdgs` -> push_sdg, `DocRevisions` -> push_doc_revision, `sd` -> push_sd)."""
    name = method_stem(rust_name)
    return name[:-1] if name.endswith("s") and len(name) > 1 else name

def _emit_struct_field(rf: RustField, field_ident: str | None = None) -> str:
    ident = field_ident or rf.rust_name
    if rf.wrapper == "list":
        return f"    {ident}: Vec<{rf.rust_type}>,"
    return f"    {ident}: Option<{rf.rust_type}>,"


def _accessors_for(rf: RustField, recv: str) -> list[str]:
    """Accessors for a field reached via `recv` (e.g. `self.gid` or `self.r#base`)."""
    name, t = method_stem(rf.rust_name), rf.rust_type
    push = push_method_name(rf.rust_name)
    if rf.wrapper == "list":
        return [
            f"    pub fn get_{name}(&self) -> &[{t}] {{",
            f"        &{recv}",
            "    }",
            "",
            f"    pub fn push_{push}(&mut self, value: {t}) {{",
            f"        {recv}.push(value);",
            "    }",
            "",
        ]
    if t == "String":
        return [
            f"    pub fn get_{name}(&self) -> Option<&str> {{",
            f"        {recv}.as_deref()",
            "    }",
            "",
            f"    pub fn set_{name}(&mut self, value: impl Into<String>) -> &mut Self {{",
            f"        {recv} = Some(value.into());",
            "        self",
            "    }",
            "",
        ]
    # Copy enum or arena link: both are Option<T> with plain get/set; the
    # bare place expression copies (Option<Copy> is Copy), keeping clippy's
    # clone_on_copy quiet
    return [
        f"    pub fn get_{name}(&self) -> Option<{t}> {{",
        f"        {recv}",
        "    }",
        "",
        f"    pub fn set_{name}(&mut self, value: {t}) -> &mut Self {{",
        f"        {recv} = Some(value);",
        "        self",
        "    }",
        "",
    ]


def _forwarded_accessors(rf: RustField, get_path: str, mut_path: str) -> list[str]:
    """Forwarded accessors delegating to the ancestor's accessor methods."""
    name, t = method_stem(rf.rust_name), rf.rust_type
    push = push_method_name(rf.rust_name)
    if rf.wrapper == "list":
        return [
            f"    pub fn get_{name}(&self) -> &[{t}] {{",
            f"        {get_path}.get_{name}()",
            "    }",
            "",
            f"    pub fn push_{push}(&mut self, value: {t}) {{",
            f"        {mut_path}.push_{push}(value)",
            "    }",
            "",
        ]
    if t == "String":
        return [
            f"    pub fn get_{name}(&self) -> Option<&str> {{",
            f"        {get_path}.get_{name}()",
            "    }",
            "",
            f"    pub fn set_{name}(&mut self, value: impl Into<String>) -> &mut Self {{",
            f"        {mut_path}.set_{name}(value);",
            "        self",
            "    }",
            "",
        ]
    return [
        f"    pub fn get_{name}(&self) -> Option<{t}> {{",
        f"        {get_path}.get_{name}()",
        "    }",
        "",
        f"    pub fn set_{name}(&mut self, value: {t}) -> &mut Self {{",
        f"        {mut_path}.set_{name}(value);",
        "        self",
        "    }",
        "",
    ]


def _emit_parent_forwarders(get_path: str, mut_path: str) -> list[str]:
    return [
        "    pub fn get_parent(&self) -> Option<ElementRef> {",
        f"        {get_path}.get_parent()",
        "    }",
        "",
        "    pub fn set_parent(&mut self, parent: Option<ElementRef>) -> &mut Self {",
        f"        {mut_path}.set_parent(parent);",
        "        self",
        "    }",
        "",
    ]


def _base_field(base: str, first: bool) -> str:
    return f"    base: {base}," if first else f"    {snake_case(base)}: {base},"


def _base_accessor(base: str, first: bool) -> list[str]:
    if first:
        return [f"    pub fn base(&self) -> &{base} {{", "        &self.base", "    }", "",
                f"    pub fn base_mut(&mut self) -> &mut {base} {{", "        &mut self.base", "    }", ""]
    name = snake_case(base)
    return [f"    pub fn {name}(&self) -> &{base} {{", f"        &self.{name}", "    }", "",
            f"    pub fn {name}_mut(&mut self) -> &mut {base} {{", f"        &mut self.{name}", "    }", ""]


def _template_pseudo_fields(cur_name: str) -> list[FieldIr]:
    """Param-derived template accessors (constructor quirks) as pseudo fields."""
    out = []
    for name, kind in templates.TEMPLATE_ACCESSORS.get(cur_name, []):
        if kind == "string":
            out.append(FieldIr(name=name, type_expr="Optional[String]", kind="optional", inner="String"))
        elif kind == "parent":
            out.append(FieldIr(name=name, type_expr="Optional[ElementRef]", kind="optional", inner="ElementRef"))
    return out


def _inherit_items(ir: Ir, cls: ClassIr) -> list[tuple[str, str, FieldIr]]:
    """(get_path, mut_path, field) for every accessor inherited from ancestors.

    get_path/mut_path are rust expressions on &self/&mut self reaching the
    ancestor struct: `self.base()` / `self.base_mut()` along the first-base
    chain, `self.<mixin>()` / `self.<mixin>_mut()` for extra bases.
    """
    items: list[tuple[str, str, FieldIr]] = []
    seen: set[str] = {FieldIr.rust_name_for(f.name) for f in cls.fields}
    get_path, mut_path = "self.base()", "self.base_mut()"
    cur = ir.get(cls.bases[0]) if cls.bases else None
    walked: set[str] = set()
    while cur is not None and cur.name not in walked:
        walked.add(cur.name)
        for f in cur.fields + _template_pseudo_fields(cur.name):
            rn = FieldIr.rust_name_for(f.name)
            if rn not in seen:
                items.append((get_path, mut_path, f))
                seen.add(rn)
        if not cur.bases:
            break
        get_path += ".base()"
        mut_path += ".base_mut()"
        cur = ir.get(cur.bases[0])
    for extra in cls.bases[1:]:
        extra_cls = ir.get(extra)
        if extra_cls is None:
            continue
        acc = snake_case(extra)
        for f in extra_cls.fields + _template_pseudo_fields(extra_cls.name):
            rn = FieldIr.rust_name_for(f.name)
            if rn not in seen:
                items.append((f"self.{acc}()", f"self.{acc}_mut()", f))
                seen.add(rn)
    return items


def _inherited(ir: Ir, cls: ClassIr, overrides: Overrides) -> tuple[list[tuple[str, str, RustField]], bool]:
    """([(get_path, mut_path, mapped field)], needs_parent_forwarder), own fields shadowing."""
    own_rust = {FieldIr.rust_name_for(f.name) for f in cls.fields}
    out: list[tuple[str, str, RustField]] = []
    needs_parent = False
    for get_path, mut_path, f in _inherit_items(ir, cls):
        if FieldIr.rust_name_for(f.name) in own_rust:
            continue
        if f.inner == "ElementRef":
            needs_parent = True
            continue
        out.append((get_path, mut_path, map_field(f, ir, overrides)))
    return out, needs_parent


def _embedded_field_names(cls: ClassIr) -> set[str]:
    """Struct-field identifiers taken by the embedded base chain."""
    return {"base"} | {snake_case(b) for b in cls.bases[1:]}


def _emit_struct(cls: ClassIr, ir: Ir, overrides: Overrides) -> list[str]:
    lines = [f"/// spec class `{cls.name}`" + (" (abstract)" if cls.is_abstract else "")]
    if cls.doc:
        lines += [f"/// {line}".rstrip() for line in cls.doc.splitlines()[:3] if line.strip()]
    lines += ["#[derive(Debug, Default)]", f"pub struct {cls.name} {{"]
    embedded = _embedded_field_names(cls)
    for i, base in enumerate(cls.bases):
        lines.append(_base_field(base, i == 0))
    own_rust = [map_field(f, ir, overrides) for f in cls.fields]
    field_idents: dict[str, str] = {}
    for rf in own_rust:
        # a py field named like an embedded base (RefType.base vs base: ARObject)
        # gets a trailing-underscore identifier — `r#base` would be the SAME
        # identifier as the embedded `base` field, not a distinct one
        ident = f"{rf.rust_name}_" if rf.rust_name in embedded else rf.rust_name
        field_idents[rf.rust_name] = ident
        lines.append(_emit_struct_field(rf, ident))
    lines += ["}", "", f"impl {cls.name} {{", "    pub fn new() -> Self {", "        Self::default()", "    }", ""]
    for i, base in enumerate(cls.bases):
        lines.extend(_base_accessor(base, i == 0))
    for rf in own_rust:
        lines.extend(_accessors_for(rf, f"self.{field_idents[rf.rust_name]}"))
    inherited, needs_parent = _inherited(ir, cls, overrides)
    for get_path, mut_path, rf in inherited:
        lines.extend(_forwarded_accessors(rf, get_path, mut_path))
    if needs_parent:
        for get_path, mut_path, f in _inherit_items(ir, cls):
            if f.inner == "ElementRef":
                lines.extend(_emit_parent_forwarders(get_path, mut_path))
                break
    lines += ["}"]
    return lines


def _referenced_types(ir: Ir, overrides: Overrides, classes: list[ClassIr]) -> set[str]:
    """Rust type names referenced by this module's structs but not defined here."""
    own = {c.name for c in classes} | {c.name + "Id" for c in classes}
    refs: set[str] = set()
    for cls in classes:
        if cls.is_enum or not overrides.emits(cls.name):
            continue
        for b in cls.bases:
            if b not in own:
                refs.add(b)
        own_rust = {FieldIr.rust_name_for(f.name) for f in cls.fields}
        own_mapped = [map_field(f, ir, overrides) for f in cls.fields]
        inherited, needs_parent = _inherited(ir, cls, overrides)
        for rf in own_mapped + [rf for _, _, rf in inherited]:
            if rf.rust_name in own_rust and rf not in own_mapped:
                continue
            if rf.link:
                refs.add(f"{rf.link}Id")
            elif rf.rust_type != "String":
                refs.add(rf.rust_type)
        if needs_parent:
            refs.add("ElementRef")
    return refs


def _module_path_of(name: str, ir: Ir, overrides: Overrides, placement: Placement) -> str | None:
    segments = placement.module_of(name)
    if segments:
        return "::".join(segments)
    if name in overrides.alias_module:
        return overrides.alias_module[name]
    cls = ir.get(name)
    if cls is not None:
        segments = py_module_segments(cls.module_py)
        if segments:
            return "::".join(segments)
    return None


def collect_imports(ir: Ir, overrides: Overrides, placement: Placement,
                    classes: list[ClassIr], module_segments: list[str] | None = None) -> list[str]:
    refs = _referenced_types(ir, overrides, classes)
    own = {c.name for c in classes} | {c.name + "Id" for c in classes}
    own_path = "::".join(module_segments) if module_segments else None
    lines: list[str] = []
    for name in sorted(refs):
        if name in own or name in ("String",):
            continue
        lookup = name[:-2] if name.endswith("Id") else name
        module_path = _module_path_of(lookup, ir, overrides, placement)
        if module_path is None or module_path == own_path:
            # unresolvable (reported elsewhere) or a self-import — a module
            # binding its own item again is a hard rust error (E0255)
            continue
        lines.append(f"use crate::{module_path}::{name};")
    has_struct = any(not c.is_enum and overrides.emits(c.name) for c in classes)
    if has_struct:
        lines.append("use crate::Document;")  # the generated compare fn needs it
    return lines


def emit_module(ir: Ir, overrides: Overrides, placement: Placement,
                classes: list[ClassIr], module_segments: list[str]) -> str:
    classes = sorted(classes, key=lambda c: c.name)
    out = [BANNER, f"//! generated from spec package: {'::'.join(module_segments)}", ""]
    concrete = [c for c in classes if not c.is_abstract and not c.is_enum and overrides.emits(c.name)]
    if concrete:
        out += ["use slotmap::new_key_type;", ""]
        out += ["new_key_type! {"]
        out += [f"    pub struct {c.name}Id;" for c in concrete]
        out += ["}", ""]
    imports = collect_imports(ir, overrides, placement, classes, module_segments)
    if imports:
        out += imports
        out.append("")
    for cls in classes:
        if cls.is_enum and overrides.emits(cls.name):
            out.append(_emit_enum(cls))
            out.append("")
    for cls in classes:
        if overrides.emits(cls.name) and not cls.is_enum:
            out.extend(_emit_struct(cls, ir, overrides))
            out.append("")
    return "\n".join(out)
