"""Emit docs/port_checklist.md — the P2-P4 progress checklist (spec §5.2).

Deliberately dumb: a method is "ported" iff a `fn <snake_case>` exists under
src/. Correctness is the harness's job, not this file's.
"""
import ast
import pathlib
import re


def collect_py_methods(py_root: pathlib.Path):
    """Yield (name, (file, line)) for every def read*/write* in the parser and
    writer modules, skipping the abstract helper classes."""
    results = []
    for rel in ("parser/arxml_parser.py", "writer/arxml_writer.py"):
        path = py_root / rel
        tree = ast.parse(path.read_text())
        for node in ast.walk(tree):
            if isinstance(node, ast.FunctionDef) and re.match(r"^(read|write)[A-Z]", node.name):
                results.append((node.name, (rel, node.lineno)))
    return results


def rust_name(py_name: str) -> str:
    out = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", py_name)
    out = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", out)
    return out.lower()


def collect_fn_names(src_root: pathlib.Path) -> set[str]:
    """All `fn <name>` identifiers under src/, one read per file."""
    pattern = re.compile(r"\bfn ([A-Za-z_][A-Za-z0-9_]*)")
    names: set[str] = set()
    for path in src_root.rglob("*.rs"):
        names.update(pattern.findall(path.read_text(errors="ignore")))
    return names


def check_ported(py_name: str, src_root: pathlib.Path) -> bool:
    # convenience wrapper for single probes (tests); bulk callers should
    # build the name set once via collect_fn_names
    return rust_name(py_name) in collect_fn_names(src_root)


def render(methods, src_root: pathlib.Path) -> str:
    fns = collect_fn_names(src_root)
    lines = [
        "<!-- @generated by tools/py2rust --emit-port-checklist. Do not edit. -->",
        "# Port checklist (py reader/writer methods → Rust)",
        "",
        "| py method | Rust name | ported | py location |",
        "|---|---|---|---|",
    ]
    for name, (rel, lineno) in sorted(methods):
        done = "x" if rust_name(name) in fns else " "
        lines.append(f"| `{name}` | `{rust_name(name)}` | [{done}] | `{rel}:{lineno}` |")
    ported = sum(1 for name, _ in methods if rust_name(name) in fns)
    lines += ["", f"**{ported}/{len(methods)} ported.**", ""]
    return "\n".join(lines)
