// @generated by tools/py2rust from py-armodel models/M2 (see PY_ARMODEL_VERSION). Do not edit.

//! generated from spec package: m2::autosar_templates::abstract_platform

use slotmap::new_key_type;

new_key_type! {
    pub struct ApplicationDeferredDataTypeId;
    pub struct ApplicationInterfaceId;
}

use crate::m2::autosar_templates::adaptive_platform::application_design::port_interface::FieldId;
use crate::m2::autosar_templates::common_structure::service_needs::ServiceProviderEnum;
use crate::m2::autosar_templates::generic_structure::general_template_classes::ar_object::ElementRef;
use crate::m2::autosar_templates::generic_structure::general_template_classes::identifiable::ShortNameFragmentId;
use crate::m2::autosar_templates::sw_component_template::datatype::data_prototypes::VariableDataPrototypeId;
use crate::m2::autosar_templates::sw_component_template::datatype::datatypes::ApplicationDataType;
use crate::m2::autosar_templates::sw_component_template::port_interface::ClientServerOperationId;
use crate::m2::autosar_templates::sw_component_template::port_interface::PortInterface;
use crate::m2::msr::asam_hdo::admin_data::AdminDataId;
use crate::m2::msr::data_dictionary::data_def_properties::SwDataDefPropsId;
use crate::m2::msr::documentation::annotation::AnnotationId;
use crate::m2::msr::documentation::text_model::block_elements::DocumentationBlockId;
use crate::m2::msr::documentation::text_model::multilanguage_data::MultiLanguageOverviewParagraphId;
use crate::m2::msr::documentation::text_model::multilanguage_data::MultilanguageLongNameId;
use crate::Document;

/// spec class `ApplicationDeferredDataType`
/// A placeholder data type in which the precise application data type is deferred to a later stage.
#[derive(Debug, Default)]
pub struct ApplicationDeferredDataType {
    base: ApplicationDataType,
}

impl ApplicationDeferredDataType {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn base(&self) -> &ApplicationDataType {
        &self.base
    }

    pub fn base_mut(&mut self) -> &mut ApplicationDataType {
        &mut self.base
    }

    pub fn get_sw_data_def_props(&self) -> Option<SwDataDefPropsId> {
        self.base().base().get_sw_data_def_props()
    }

    pub fn set_sw_data_def_props(&mut self, value: SwDataDefPropsId) -> &mut Self {
        self.base_mut().base_mut().set_sw_data_def_props(value);
        self
    }

    pub fn get_admin_data(&self) -> Option<AdminDataId> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_admin_data()
    }

    pub fn set_admin_data(&mut self, value: AdminDataId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_admin_data(value);
        self
    }

    pub fn remove_admin_data(&mut self) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .remove_admin_data();
        self
    }

    pub fn get_annotations(&self) -> &[AnnotationId] {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_annotations()
    }

    pub fn push_annotation(&mut self, value: AnnotationId) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .push_annotation(value)
    }

    pub fn get_category(&self) -> Option<&str> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_category()
    }

    pub fn set_category(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_category(value);
        self
    }

    pub fn get_desc(&self) -> Option<MultiLanguageOverviewParagraphId> {
        self.base().base().base().base().base().base().get_desc()
    }

    pub fn set_desc(&mut self, value: MultiLanguageOverviewParagraphId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_desc(value);
        self
    }

    pub fn get_introduction(&self) -> Option<DocumentationBlockId> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_introduction()
    }

    pub fn set_introduction(&mut self, value: DocumentationBlockId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_introduction(value);
        self
    }

    pub fn get_uuid(&self) -> Option<&str> {
        self.base().base().base().base().base().base().get_uuid()
    }

    pub fn set_uuid(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_uuid(value);
        self
    }

    pub fn get_elements(&self) -> &[ElementRef] {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_elements()
    }

    pub fn push_element(&mut self, value: ElementRef) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .push_element(value)
    }

    pub fn get_long_name(&self) -> Option<MultilanguageLongNameId> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_long_name()
    }

    pub fn set_long_name(&mut self, value: MultilanguageLongNameId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_long_name(value);
        self
    }

    pub fn get_short_name_fragments(&self) -> &[ShortNameFragmentId] {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_short_name_fragments()
    }

    pub fn push_short_name_fragment(&mut self, value: ShortNameFragmentId) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .push_short_name_fragment(value)
    }

    pub fn get_short_name(&self) -> Option<&str> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_short_name()
    }

    pub fn set_short_name(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_short_name(value);
        self
    }

    pub fn get_checksum(&self) -> Option<&str> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_checksum()
    }

    pub fn set_checksum(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_checksum(value);
        self
    }

    pub fn get_timestamp(&self) -> Option<&str> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_timestamp()
    }

    pub fn set_timestamp(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_timestamp(value);
        self
    }

    pub fn get_parent(&self) -> Option<ElementRef> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_parent()
    }

    pub fn set_parent(&mut self, parent: Option<ElementRef>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_parent(parent);
        self
    }
}

/// spec class `ApplicationInterface`
/// This represents the ability to define a PortInterface that consists of a
/// composition of commands (method calls), indications (events) and attributes
/// (fields). Tags: atp.Status=draft atp.recommendedPackage=Interfaces
#[derive(Debug, Default)]
pub struct ApplicationInterface {
    base: PortInterface,
    attributes: Vec<FieldId>,
    commands: Vec<ClientServerOperationId>,
    indications: Vec<VariableDataPrototypeId>,
}

impl ApplicationInterface {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn base(&self) -> &PortInterface {
        &self.base
    }

    pub fn base_mut(&mut self) -> &mut PortInterface {
        &mut self.base
    }

    pub fn get_attributes(&self) -> &[FieldId] {
        &self.attributes
    }

    pub fn push_attribute(&mut self, value: FieldId) {
        self.attributes.push(value);
    }

    pub fn get_commands(&self) -> &[ClientServerOperationId] {
        &self.commands
    }

    pub fn push_command(&mut self, value: ClientServerOperationId) {
        self.commands.push(value);
    }

    pub fn get_indications(&self) -> &[VariableDataPrototypeId] {
        &self.indications
    }

    pub fn push_indication(&mut self, value: VariableDataPrototypeId) {
        self.indications.push(value);
    }

    pub fn get_is_service(&self) -> Option<&str> {
        self.base().get_is_service()
    }

    pub fn set_is_service(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_is_service(value);
        self
    }

    pub fn get_service_kind(&self) -> Option<ServiceProviderEnum> {
        self.base().get_service_kind()
    }

    pub fn set_service_kind(&mut self, value: ServiceProviderEnum) -> &mut Self {
        self.base_mut().set_service_kind(value);
        self
    }

    pub fn get_atp_features(&self) -> &[ElementRef] {
        self.base().base().base().get_atp_features()
    }

    pub fn push_atp_feature(&mut self, value: ElementRef) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .push_atp_feature(value)
    }

    pub fn get_admin_data(&self) -> Option<AdminDataId> {
        self.base().base().base().base().get_admin_data()
    }

    pub fn set_admin_data(&mut self, value: AdminDataId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_admin_data(value);
        self
    }

    pub fn remove_admin_data(&mut self) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .remove_admin_data();
        self
    }

    pub fn get_annotations(&self) -> &[AnnotationId] {
        self.base().base().base().base().get_annotations()
    }

    pub fn push_annotation(&mut self, value: AnnotationId) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .push_annotation(value)
    }

    pub fn get_category(&self) -> Option<&str> {
        self.base().base().base().base().get_category()
    }

    pub fn set_category(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_category(value);
        self
    }

    pub fn get_desc(&self) -> Option<MultiLanguageOverviewParagraphId> {
        self.base().base().base().base().get_desc()
    }

    pub fn set_desc(&mut self, value: MultiLanguageOverviewParagraphId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_desc(value);
        self
    }

    pub fn get_introduction(&self) -> Option<DocumentationBlockId> {
        self.base().base().base().base().get_introduction()
    }

    pub fn set_introduction(&mut self, value: DocumentationBlockId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_introduction(value);
        self
    }

    pub fn get_uuid(&self) -> Option<&str> {
        self.base().base().base().base().get_uuid()
    }

    pub fn set_uuid(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_uuid(value);
        self
    }

    pub fn get_elements(&self) -> &[ElementRef] {
        self.base().base().base().base().get_elements()
    }

    pub fn push_element(&mut self, value: ElementRef) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .push_element(value)
    }

    pub fn get_long_name(&self) -> Option<MultilanguageLongNameId> {
        self.base().base().base().base().base().get_long_name()
    }

    pub fn set_long_name(&mut self, value: MultilanguageLongNameId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_long_name(value);
        self
    }

    pub fn get_short_name_fragments(&self) -> &[ShortNameFragmentId] {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_short_name_fragments()
    }

    pub fn push_short_name_fragment(&mut self, value: ShortNameFragmentId) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .push_short_name_fragment(value)
    }

    pub fn get_short_name(&self) -> Option<&str> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_short_name()
    }

    pub fn set_short_name(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_short_name(value);
        self
    }

    pub fn get_checksum(&self) -> Option<&str> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_checksum()
    }

    pub fn set_checksum(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_checksum(value);
        self
    }

    pub fn get_timestamp(&self) -> Option<&str> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_timestamp()
    }

    pub fn set_timestamp(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_timestamp(value);
        self
    }

    pub fn get_parent(&self) -> Option<ElementRef> {
        self.base().base().base().base().base().base().get_parent()
    }

    pub fn set_parent(&mut self, parent: Option<ElementRef>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_parent(parent);
        self
    }
}

impl Document {
    pub(crate) fn compare_application_deferred_data_type(
        &self,
        other: &Document,
        a: &ApplicationDeferredDataType,
        b: &ApplicationDeferredDataType,
        path: &str,
    ) -> Result<(), String> {
        self.compare_application_data_type(other, a.base(), b.base(), path)?;
        Ok(())
    }

    pub(crate) fn compare_application_interface(
        &self,
        other: &Document,
        a: &ApplicationInterface,
        b: &ApplicationInterface,
        path: &str,
    ) -> Result<(), String> {
        self.compare_port_interface(other, a.base(), b.base(), path)?;
        let list_a = a.get_attributes();
        let list_b = b.get_attributes();
        if list_a.len() != list_b.len() {
            return Err(format!("{path}: ATTRIBUTES length mismatch"));
        }
        for (index, (x, y)) in list_a.iter().zip(list_b.iter()).enumerate() {
            let x = self
                .fields
                .get(*x)
                .ok_or_else(|| format!("{path}.ATTRIBUTES[{index}]: id not found in own arena"))?;
            let y = other.fields.get(*y).ok_or_else(|| {
                format!("{path}.ATTRIBUTES[{index}]: id not found in other arena")
            })?;
            self.compare_field(other, x, y, &format!("{path}.ATTRIBUTES[{index}]"))?;
        }
        let list_a = a.get_commands();
        let list_b = b.get_commands();
        if list_a.len() != list_b.len() {
            return Err(format!("{path}: COMMANDS length mismatch"));
        }
        for (index, (x, y)) in list_a.iter().zip(list_b.iter()).enumerate() {
            let x = self
                .client_server_operations
                .get(*x)
                .ok_or_else(|| format!("{path}.COMMANDS[{index}]: id not found in own arena"))?;
            let y = other
                .client_server_operations
                .get(*y)
                .ok_or_else(|| format!("{path}.COMMANDS[{index}]: id not found in other arena"))?;
            self.compare_client_server_operation(
                other,
                x,
                y,
                &format!("{path}.COMMANDS[{index}]"),
            )?;
        }
        let list_a = a.get_indications();
        let list_b = b.get_indications();
        if list_a.len() != list_b.len() {
            return Err(format!("{path}: INDICATIONS length mismatch"));
        }
        for (index, (x, y)) in list_a.iter().zip(list_b.iter()).enumerate() {
            let x = self
                .variable_data_prototypes
                .get(*x)
                .ok_or_else(|| format!("{path}.INDICATIONS[{index}]: id not found in own arena"))?;
            let y = other.variable_data_prototypes.get(*y).ok_or_else(|| {
                format!("{path}.INDICATIONS[{index}]: id not found in other arena")
            })?;
            self.compare_variable_data_prototype(
                other,
                x,
                y,
                &format!("{path}.INDICATIONS[{index}]"),
            )?;
        }
        Ok(())
    }
}
