// @generated by tools/py2rust from py-armodel models/M2 (see PY_ARMODEL_VERSION). Do not edit.

//! generated from spec package: m2::autosar_templates::generic_structure::general_template_classes::tag_with_optional_value

use slotmap::new_key_type;

new_key_type! {
    pub struct TagWithOptionalValueId;
}

use crate::m2::autosar_templates::generic_structure::general_template_classes::ar_object::ARObject;
use crate::m2::autosar_templates::generic_structure::general_template_classes::stereotype_mixins::VariationPointCapable;
use crate::m2::autosar_templates::generic_structure::variant_handling::VariationPointId;
use crate::Document;

/// spec class `TagWithOptionalValue`
/// A tagged value is a combination of a tag (key) and a value that gives supplementary information that is attached to a model element. Please note that keys without a value are allowed.
#[derive(Debug, Default)]
pub struct TagWithOptionalValue {
    base: ARObject,
    variation_point_capable: VariationPointCapable,
    key: Option<String>,
    sequence_offset: Option<String>,
    value: Option<String>,
}

impl TagWithOptionalValue {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn base(&self) -> &ARObject {
        &self.base
    }

    pub fn base_mut(&mut self) -> &mut ARObject {
        &mut self.base
    }

    pub fn variation_point_capable(&self) -> &VariationPointCapable {
        &self.variation_point_capable
    }

    pub fn variation_point_capable_mut(&mut self) -> &mut VariationPointCapable {
        &mut self.variation_point_capable
    }

    pub fn get_key(&self) -> Option<&str> {
        self.key.as_deref()
    }

    pub fn set_key(&mut self, value: impl Into<String>) -> &mut Self {
        self.key = Some(value.into());
        self
    }

    pub fn get_sequence_offset(&self) -> Option<&str> {
        self.sequence_offset.as_deref()
    }

    pub fn set_sequence_offset(&mut self, value: impl Into<String>) -> &mut Self {
        self.sequence_offset = Some(value.into());
        self
    }

    pub fn get_value(&self) -> Option<&str> {
        self.value.as_deref()
    }

    pub fn set_value(&mut self, value: impl Into<String>) -> &mut Self {
        self.value = Some(value.into());
        self
    }

    pub fn get_checksum(&self) -> Option<&str> {
        self.base().get_checksum()
    }

    pub fn set_checksum(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_checksum(value);
        self
    }

    pub fn get_timestamp(&self) -> Option<&str> {
        self.base().get_timestamp()
    }

    pub fn set_timestamp(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_timestamp(value);
        self
    }

    pub fn get_variation_point(&self) -> Option<VariationPointId> {
        self.variation_point_capable().get_variation_point()
    }

    pub fn set_variation_point(&mut self, value: VariationPointId) -> &mut Self {
        self.variation_point_capable_mut()
            .set_variation_point(value);
        self
    }
}

impl Document {
    pub(crate) fn compare_tag_with_optional_value(
        &self,
        other: &Document,
        a: &TagWithOptionalValue,
        b: &TagWithOptionalValue,
        path: &str,
    ) -> Result<(), String> {
        Self::compare_ar_object(a.base(), b.base(), path)?;
        self.compare_variation_point_capable(
            other,
            a.variation_point_capable(),
            b.variation_point_capable(),
            path,
        )?;
        if a.get_key() != b.get_key() {
            return Err(format!("{path}: KEY mismatch"));
        }
        if a.get_sequence_offset() != b.get_sequence_offset() {
            return Err(format!("{path}: SEQUENCE_OFFSET mismatch"));
        }
        if a.get_value() != b.get_value() {
            return Err(format!("{path}: VALUE mismatch"));
        }
        Ok(())
    }
}
