// @generated by tools/py2rust from py-armodel models/M2 (see PY_ARMODEL_VERSION). Do not edit.

//! generated from spec package: m2::autosar_templates::ecu_resource_template::hw_element_category

use slotmap::new_key_type;

new_key_type! {
    pub struct HwAttributeDefId;
    pub struct HwAttributeLiteralDefId;
    pub struct HwAttributeValueId;
    pub struct HwCategoryId;
    pub struct HwTypeId;
}

use crate::m2::autosar_templates::ecu_resource_template::HwDescriptionEntity;
use crate::m2::autosar_templates::generic_structure::general_template_classes::ar_object::ARObject;
use crate::m2::autosar_templates::generic_structure::general_template_classes::ar_object::ElementRef;
use crate::m2::autosar_templates::generic_structure::general_template_classes::ar_package::ARElement;
use crate::m2::autosar_templates::generic_structure::general_template_classes::identifiable::Identifiable;
use crate::m2::autosar_templates::generic_structure::general_template_classes::identifiable::ShortNameFragmentId;
use crate::m2::autosar_templates::generic_structure::general_template_classes::stereotype_mixins::VariationPointCapable;
use crate::m2::autosar_templates::generic_structure::variant_handling::VariationPointId;
use crate::m2::msr::asam_hdo::admin_data::AdminDataId;
use crate::m2::msr::documentation::annotation::AnnotationId;
use crate::m2::msr::documentation::text_model::block_elements::DocumentationBlockId;
use crate::m2::msr::documentation::text_model::multilanguage_data::MultiLanguageOverviewParagraphId;
use crate::m2::msr::documentation::text_model::multilanguage_data::MultilanguageLongNameId;
use crate::Document;

/// spec class `HwAttributeDef`
/// This metaclass represents the ability to define a particular hardware attribute. The category of this element defines the type of the attributeValue. If the category is Enumeration the hwAttributeEnumerationLiterals specify the available literals.
#[derive(Debug, Default)]
pub struct HwAttributeDef {
    base: Identifiable,
    hw_attribute_literals: Vec<HwAttributeLiteralDefId>,
    is_required: Option<String>,
    unit_ref: Option<String>,
}

impl HwAttributeDef {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn base(&self) -> &Identifiable {
        &self.base
    }

    pub fn base_mut(&mut self) -> &mut Identifiable {
        &mut self.base
    }

    pub fn get_hw_attribute_literals(&self) -> &[HwAttributeLiteralDefId] {
        &self.hw_attribute_literals
    }

    pub fn push_hw_attribute_literal(&mut self, value: HwAttributeLiteralDefId) {
        self.hw_attribute_literals.push(value);
    }

    pub fn get_is_required(&self) -> Option<&str> {
        self.is_required.as_deref()
    }

    pub fn set_is_required(&mut self, value: impl Into<String>) -> &mut Self {
        self.is_required = Some(value.into());
        self
    }

    pub fn get_unit_ref(&self) -> Option<&str> {
        self.unit_ref.as_deref()
    }

    pub fn set_unit_ref(&mut self, value: impl Into<String>) -> &mut Self {
        self.unit_ref = Some(value.into());
        self
    }

    pub fn get_admin_data(&self) -> Option<AdminDataId> {
        self.base().get_admin_data()
    }

    pub fn set_admin_data(&mut self, value: AdminDataId) -> &mut Self {
        self.base_mut().set_admin_data(value);
        self
    }

    pub fn get_annotations(&self) -> &[AnnotationId] {
        self.base().get_annotations()
    }

    pub fn push_annotation(&mut self, value: AnnotationId) {
        self.base_mut().push_annotation(value)
    }

    pub fn get_category(&self) -> Option<&str> {
        self.base().get_category()
    }

    pub fn set_category(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_category(value);
        self
    }

    pub fn get_desc(&self) -> Option<MultiLanguageOverviewParagraphId> {
        self.base().get_desc()
    }

    pub fn set_desc(&mut self, value: MultiLanguageOverviewParagraphId) -> &mut Self {
        self.base_mut().set_desc(value);
        self
    }

    pub fn get_introduction(&self) -> Option<DocumentationBlockId> {
        self.base().get_introduction()
    }

    pub fn set_introduction(&mut self, value: DocumentationBlockId) -> &mut Self {
        self.base_mut().set_introduction(value);
        self
    }

    pub fn get_uuid(&self) -> Option<&str> {
        self.base().get_uuid()
    }

    pub fn set_uuid(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_uuid(value);
        self
    }

    pub fn get_elements(&self) -> &[ElementRef] {
        self.base().get_elements()
    }

    pub fn push_element(&mut self, value: ElementRef) {
        self.base_mut().push_element(value)
    }

    pub fn get_long_name(&self) -> Option<MultilanguageLongNameId> {
        self.base().base().get_long_name()
    }

    pub fn set_long_name(&mut self, value: MultilanguageLongNameId) -> &mut Self {
        self.base_mut().base_mut().set_long_name(value);
        self
    }

    pub fn get_short_name_fragments(&self) -> &[ShortNameFragmentId] {
        self.base().base().base().get_short_name_fragments()
    }

    pub fn push_short_name_fragment(&mut self, value: ShortNameFragmentId) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .push_short_name_fragment(value)
    }

    pub fn get_short_name(&self) -> Option<&str> {
        self.base().base().base().get_short_name()
    }

    pub fn set_short_name(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().base_mut().base_mut().set_short_name(value);
        self
    }

    pub fn get_checksum(&self) -> Option<&str> {
        self.base().base().base().base().get_checksum()
    }

    pub fn set_checksum(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_checksum(value);
        self
    }

    pub fn get_timestamp(&self) -> Option<&str> {
        self.base().base().base().base().get_timestamp()
    }

    pub fn set_timestamp(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_timestamp(value);
        self
    }

    pub fn get_parent(&self) -> Option<ElementRef> {
        self.base().base().base().get_parent()
    }

    pub fn set_parent(&mut self, parent: Option<ElementRef>) -> &mut Self {
        self.base_mut().base_mut().base_mut().set_parent(parent);
        self
    }
}

/// spec class `HwAttributeLiteralDef`
/// One available EnumerationLiteral of the Enumeration definition. Only applicable if the category of the HwAttributeDef equals Enumeration.
#[derive(Debug, Default)]
pub struct HwAttributeLiteralDef {
    base: Identifiable,
}

impl HwAttributeLiteralDef {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn base(&self) -> &Identifiable {
        &self.base
    }

    pub fn base_mut(&mut self) -> &mut Identifiable {
        &mut self.base
    }

    pub fn get_admin_data(&self) -> Option<AdminDataId> {
        self.base().get_admin_data()
    }

    pub fn set_admin_data(&mut self, value: AdminDataId) -> &mut Self {
        self.base_mut().set_admin_data(value);
        self
    }

    pub fn get_annotations(&self) -> &[AnnotationId] {
        self.base().get_annotations()
    }

    pub fn push_annotation(&mut self, value: AnnotationId) {
        self.base_mut().push_annotation(value)
    }

    pub fn get_category(&self) -> Option<&str> {
        self.base().get_category()
    }

    pub fn set_category(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_category(value);
        self
    }

    pub fn get_desc(&self) -> Option<MultiLanguageOverviewParagraphId> {
        self.base().get_desc()
    }

    pub fn set_desc(&mut self, value: MultiLanguageOverviewParagraphId) -> &mut Self {
        self.base_mut().set_desc(value);
        self
    }

    pub fn get_introduction(&self) -> Option<DocumentationBlockId> {
        self.base().get_introduction()
    }

    pub fn set_introduction(&mut self, value: DocumentationBlockId) -> &mut Self {
        self.base_mut().set_introduction(value);
        self
    }

    pub fn get_uuid(&self) -> Option<&str> {
        self.base().get_uuid()
    }

    pub fn set_uuid(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_uuid(value);
        self
    }

    pub fn get_elements(&self) -> &[ElementRef] {
        self.base().get_elements()
    }

    pub fn push_element(&mut self, value: ElementRef) {
        self.base_mut().push_element(value)
    }

    pub fn get_long_name(&self) -> Option<MultilanguageLongNameId> {
        self.base().base().get_long_name()
    }

    pub fn set_long_name(&mut self, value: MultilanguageLongNameId) -> &mut Self {
        self.base_mut().base_mut().set_long_name(value);
        self
    }

    pub fn get_short_name_fragments(&self) -> &[ShortNameFragmentId] {
        self.base().base().base().get_short_name_fragments()
    }

    pub fn push_short_name_fragment(&mut self, value: ShortNameFragmentId) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .push_short_name_fragment(value)
    }

    pub fn get_short_name(&self) -> Option<&str> {
        self.base().base().base().get_short_name()
    }

    pub fn set_short_name(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().base_mut().base_mut().set_short_name(value);
        self
    }

    pub fn get_checksum(&self) -> Option<&str> {
        self.base().base().base().base().get_checksum()
    }

    pub fn set_checksum(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_checksum(value);
        self
    }

    pub fn get_timestamp(&self) -> Option<&str> {
        self.base().base().base().base().get_timestamp()
    }

    pub fn set_timestamp(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_timestamp(value);
        self
    }

    pub fn get_parent(&self) -> Option<ElementRef> {
        self.base().base().base().get_parent()
    }

    pub fn set_parent(&mut self, parent: Option<ElementRef>) -> &mut Self {
        self.base_mut().base_mut().base_mut().set_parent(parent);
        self
    }
}

/// spec class `HwAttributeValue`
/// This metaclass represents the ability to assign a hardware attribute value. Note that v and vt are mutually exclusive.
#[derive(Debug, Default)]
pub struct HwAttributeValue {
    base: ARObject,
    variation_point_capable: VariationPointCapable,
    annotation: Option<AnnotationId>,
    hw_attribute_def_ref: Option<String>,
    v: Option<String>,
    vt: Option<String>,
}

impl HwAttributeValue {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn base(&self) -> &ARObject {
        &self.base
    }

    pub fn base_mut(&mut self) -> &mut ARObject {
        &mut self.base
    }

    pub fn variation_point_capable(&self) -> &VariationPointCapable {
        &self.variation_point_capable
    }

    pub fn variation_point_capable_mut(&mut self) -> &mut VariationPointCapable {
        &mut self.variation_point_capable
    }

    pub fn get_annotation(&self) -> Option<AnnotationId> {
        self.annotation
    }

    pub fn set_annotation(&mut self, value: AnnotationId) -> &mut Self {
        self.annotation = Some(value);
        self
    }

    pub fn get_hw_attribute_def_ref(&self) -> Option<&str> {
        self.hw_attribute_def_ref.as_deref()
    }

    pub fn set_hw_attribute_def_ref(&mut self, value: impl Into<String>) -> &mut Self {
        self.hw_attribute_def_ref = Some(value.into());
        self
    }

    pub fn get_v(&self) -> Option<&str> {
        self.v.as_deref()
    }

    pub fn set_v(&mut self, value: impl Into<String>) -> &mut Self {
        self.v = Some(value.into());
        self
    }

    pub fn get_vt(&self) -> Option<&str> {
        self.vt.as_deref()
    }

    pub fn set_vt(&mut self, value: impl Into<String>) -> &mut Self {
        self.vt = Some(value.into());
        self
    }

    pub fn get_checksum(&self) -> Option<&str> {
        self.base().get_checksum()
    }

    pub fn set_checksum(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_checksum(value);
        self
    }

    pub fn get_timestamp(&self) -> Option<&str> {
        self.base().get_timestamp()
    }

    pub fn set_timestamp(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_timestamp(value);
        self
    }

    pub fn get_variation_point(&self) -> Option<VariationPointId> {
        self.variation_point_capable().get_variation_point()
    }

    pub fn set_variation_point(&mut self, value: VariationPointId) -> &mut Self {
        self.variation_point_capable_mut()
            .set_variation_point(value);
        self
    }
}

/// spec class `HwCategory`
/// This metaclass represents the ability to declare hardware categories and its particular attributes. Tags: atp.recommendedPackage=HwCategorys
#[derive(Debug, Default)]
pub struct HwCategory {
    base: ARElement,
    hw_attribute_defs: Vec<HwAttributeDefId>,
}

impl HwCategory {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn base(&self) -> &ARElement {
        &self.base
    }

    pub fn base_mut(&mut self) -> &mut ARElement {
        &mut self.base
    }

    pub fn get_hw_attribute_defs(&self) -> &[HwAttributeDefId] {
        &self.hw_attribute_defs
    }

    pub fn push_hw_attribute_def(&mut self, value: HwAttributeDefId) {
        self.hw_attribute_defs.push(value);
    }

    pub fn get_admin_data(&self) -> Option<AdminDataId> {
        self.base().base().base().base().get_admin_data()
    }

    pub fn set_admin_data(&mut self, value: AdminDataId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_admin_data(value);
        self
    }

    pub fn get_annotations(&self) -> &[AnnotationId] {
        self.base().base().base().base().get_annotations()
    }

    pub fn push_annotation(&mut self, value: AnnotationId) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .push_annotation(value)
    }

    pub fn get_category(&self) -> Option<&str> {
        self.base().base().base().base().get_category()
    }

    pub fn set_category(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_category(value);
        self
    }

    pub fn get_desc(&self) -> Option<MultiLanguageOverviewParagraphId> {
        self.base().base().base().base().get_desc()
    }

    pub fn set_desc(&mut self, value: MultiLanguageOverviewParagraphId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_desc(value);
        self
    }

    pub fn get_introduction(&self) -> Option<DocumentationBlockId> {
        self.base().base().base().base().get_introduction()
    }

    pub fn set_introduction(&mut self, value: DocumentationBlockId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_introduction(value);
        self
    }

    pub fn get_uuid(&self) -> Option<&str> {
        self.base().base().base().base().get_uuid()
    }

    pub fn set_uuid(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_uuid(value);
        self
    }

    pub fn get_elements(&self) -> &[ElementRef] {
        self.base().base().base().base().get_elements()
    }

    pub fn push_element(&mut self, value: ElementRef) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .push_element(value)
    }

    pub fn get_long_name(&self) -> Option<MultilanguageLongNameId> {
        self.base().base().base().base().base().get_long_name()
    }

    pub fn set_long_name(&mut self, value: MultilanguageLongNameId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_long_name(value);
        self
    }

    pub fn get_short_name_fragments(&self) -> &[ShortNameFragmentId] {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_short_name_fragments()
    }

    pub fn push_short_name_fragment(&mut self, value: ShortNameFragmentId) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .push_short_name_fragment(value)
    }

    pub fn get_short_name(&self) -> Option<&str> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_short_name()
    }

    pub fn set_short_name(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_short_name(value);
        self
    }

    pub fn get_checksum(&self) -> Option<&str> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_checksum()
    }

    pub fn set_checksum(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_checksum(value);
        self
    }

    pub fn get_timestamp(&self) -> Option<&str> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_timestamp()
    }

    pub fn set_timestamp(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_timestamp(value);
        self
    }

    pub fn get_parent(&self) -> Option<ElementRef> {
        self.base().base().base().base().base().base().get_parent()
    }

    pub fn set_parent(&mut self, parent: Option<ElementRef>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_parent(parent);
        self
    }
}

/// spec class `HwType`
/// This represents the ability to describe Hardware types on an abstract level. The particular types of hardware are distinguished by the category. This category determines the applicable attributes. The possible categories and attributes are defined in HwCategory.
#[derive(Debug, Default)]
pub struct HwType {
    base: ARElement,
    hw_description_entity: HwDescriptionEntity,
}

impl HwType {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn base(&self) -> &ARElement {
        &self.base
    }

    pub fn base_mut(&mut self) -> &mut ARElement {
        &mut self.base
    }

    pub fn hw_description_entity(&self) -> &HwDescriptionEntity {
        &self.hw_description_entity
    }

    pub fn hw_description_entity_mut(&mut self) -> &mut HwDescriptionEntity {
        &mut self.hw_description_entity
    }

    pub fn get_admin_data(&self) -> Option<AdminDataId> {
        self.base().base().base().base().get_admin_data()
    }

    pub fn set_admin_data(&mut self, value: AdminDataId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_admin_data(value);
        self
    }

    pub fn get_annotations(&self) -> &[AnnotationId] {
        self.base().base().base().base().get_annotations()
    }

    pub fn push_annotation(&mut self, value: AnnotationId) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .push_annotation(value)
    }

    pub fn get_category(&self) -> Option<&str> {
        self.base().base().base().base().get_category()
    }

    pub fn set_category(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_category(value);
        self
    }

    pub fn get_desc(&self) -> Option<MultiLanguageOverviewParagraphId> {
        self.base().base().base().base().get_desc()
    }

    pub fn set_desc(&mut self, value: MultiLanguageOverviewParagraphId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_desc(value);
        self
    }

    pub fn get_introduction(&self) -> Option<DocumentationBlockId> {
        self.base().base().base().base().get_introduction()
    }

    pub fn set_introduction(&mut self, value: DocumentationBlockId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_introduction(value);
        self
    }

    pub fn get_uuid(&self) -> Option<&str> {
        self.base().base().base().base().get_uuid()
    }

    pub fn set_uuid(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_uuid(value);
        self
    }

    pub fn get_elements(&self) -> &[ElementRef] {
        self.base().base().base().base().get_elements()
    }

    pub fn push_element(&mut self, value: ElementRef) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .push_element(value)
    }

    pub fn get_long_name(&self) -> Option<MultilanguageLongNameId> {
        self.base().base().base().base().base().get_long_name()
    }

    pub fn set_long_name(&mut self, value: MultilanguageLongNameId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_long_name(value);
        self
    }

    pub fn get_short_name_fragments(&self) -> &[ShortNameFragmentId] {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_short_name_fragments()
    }

    pub fn push_short_name_fragment(&mut self, value: ShortNameFragmentId) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .push_short_name_fragment(value)
    }

    pub fn get_short_name(&self) -> Option<&str> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_short_name()
    }

    pub fn set_short_name(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_short_name(value);
        self
    }

    pub fn get_checksum(&self) -> Option<&str> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_checksum()
    }

    pub fn set_checksum(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_checksum(value);
        self
    }

    pub fn get_timestamp(&self) -> Option<&str> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_timestamp()
    }

    pub fn set_timestamp(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_timestamp(value);
        self
    }

    pub fn get_hw_attribute_values(&self) -> &[HwAttributeValueId] {
        self.hw_description_entity().get_hw_attribute_values()
    }

    pub fn push_hw_attribute_value(&mut self, value: HwAttributeValueId) {
        self.hw_description_entity_mut()
            .push_hw_attribute_value(value)
    }

    pub fn get_hw_category_refs(&self) -> &[String] {
        self.hw_description_entity().get_hw_category_refs()
    }

    pub fn push_hw_category_ref(&mut self, value: String) {
        self.hw_description_entity_mut().push_hw_category_ref(value)
    }

    pub fn get_hw_type_ref(&self) -> Option<&str> {
        self.hw_description_entity().get_hw_type_ref()
    }

    pub fn set_hw_type_ref(&mut self, value: impl Into<String>) -> &mut Self {
        self.hw_description_entity_mut().set_hw_type_ref(value);
        self
    }

    pub fn get_parent(&self) -> Option<ElementRef> {
        self.base().base().base().base().base().base().get_parent()
    }

    pub fn set_parent(&mut self, parent: Option<ElementRef>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_parent(parent);
        self
    }
}

impl Document {
    pub(crate) fn compare_hw_attribute_def(
        &self,
        other: &Document,
        a: &HwAttributeDef,
        b: &HwAttributeDef,
        path: &str,
    ) -> Result<(), String> {
        self.compare_identifiable(other, a.base(), b.base(), path)?;
        let list_a = a.get_hw_attribute_literals();
        let list_b = b.get_hw_attribute_literals();
        if list_a.len() != list_b.len() {
            return Err(format!("{path}: HW_ATTRIBUTE_LITERALS length mismatch"));
        }
        for (index, (x, y)) in list_a.iter().zip(list_b.iter()).enumerate() {
            let x = self.hw_attribute_literal_defs.get(*x).ok_or_else(|| {
                format!("{path}.HW_ATTRIBUTE_LITERALS[{index}]: id not found in own arena")
            })?;
            let y = other.hw_attribute_literal_defs.get(*y).ok_or_else(|| {
                format!("{path}.HW_ATTRIBUTE_LITERALS[{index}]: id not found in other arena")
            })?;
            self.compare_hw_attribute_literal_def(
                other,
                x,
                y,
                &format!("{path}.HW_ATTRIBUTE_LITERALS[{index}]"),
            )?;
        }
        if a.get_is_required() != b.get_is_required() {
            return Err(format!("{path}: IS_REQUIRED mismatch"));
        }
        if a.get_unit_ref() != b.get_unit_ref() {
            return Err(format!("{path}: UNIT_REF mismatch"));
        }
        Ok(())
    }

    pub(crate) fn compare_hw_attribute_literal_def(
        &self,
        other: &Document,
        a: &HwAttributeLiteralDef,
        b: &HwAttributeLiteralDef,
        path: &str,
    ) -> Result<(), String> {
        self.compare_identifiable(other, a.base(), b.base(), path)?;
        Ok(())
    }

    pub(crate) fn compare_hw_attribute_value(
        &self,
        other: &Document,
        a: &HwAttributeValue,
        b: &HwAttributeValue,
        path: &str,
    ) -> Result<(), String> {
        Self::compare_ar_object(a.base(), b.base(), path)?;
        self.compare_variation_point_capable(
            other,
            a.variation_point_capable(),
            b.variation_point_capable(),
            path,
        )?;
        if a.get_annotation() != b.get_annotation() {
            return Err(format!("{path}: ANNOTATION mismatch"));
        }
        if a.get_hw_attribute_def_ref() != b.get_hw_attribute_def_ref() {
            return Err(format!("{path}: HW_ATTRIBUTE_DEF_REF mismatch"));
        }
        if a.get_v() != b.get_v() {
            return Err(format!("{path}: V mismatch"));
        }
        if a.get_vt() != b.get_vt() {
            return Err(format!("{path}: VT mismatch"));
        }
        Ok(())
    }

    pub(crate) fn compare_hw_category(
        &self,
        other: &Document,
        a: &HwCategory,
        b: &HwCategory,
        path: &str,
    ) -> Result<(), String> {
        self.compare_ar_element(other, a.base(), b.base(), path)?;
        let list_a = a.get_hw_attribute_defs();
        let list_b = b.get_hw_attribute_defs();
        if list_a.len() != list_b.len() {
            return Err(format!("{path}: HW_ATTRIBUTE_DEFS length mismatch"));
        }
        for (index, (x, y)) in list_a.iter().zip(list_b.iter()).enumerate() {
            let x = self.hw_attribute_defs.get(*x).ok_or_else(|| {
                format!("{path}.HW_ATTRIBUTE_DEFS[{index}]: id not found in own arena")
            })?;
            let y = other.hw_attribute_defs.get(*y).ok_or_else(|| {
                format!("{path}.HW_ATTRIBUTE_DEFS[{index}]: id not found in other arena")
            })?;
            self.compare_hw_attribute_def(
                other,
                x,
                y,
                &format!("{path}.HW_ATTRIBUTE_DEFS[{index}]"),
            )?;
        }
        Ok(())
    }

    pub(crate) fn compare_hw_type(
        &self,
        other: &Document,
        a: &HwType,
        b: &HwType,
        path: &str,
    ) -> Result<(), String> {
        self.compare_ar_element(other, a.base(), b.base(), path)?;
        self.compare_hw_description_entity(
            other,
            a.hw_description_entity(),
            b.hw_description_entity(),
            path,
        )?;
        Ok(())
    }
}
