// @generated by tools/py2rust from py-armodel models/M2 (see PY_ARMODEL_VERSION). Do not edit.

//! generated from spec package: m2::autosar_templates::system_template::diagnostic_connection

use slotmap::new_key_type;

new_key_type! {
    pub struct DiagnosticConnectionId;
    pub struct DoIpTpConnectionId;
    pub struct TpConnectionIdentId;
}

use crate::m2::autosar_templates::generic_structure::general_template_classes::ar_object::ARObject;
use crate::m2::autosar_templates::generic_structure::general_template_classes::ar_object::ElementRef;
use crate::m2::autosar_templates::generic_structure::general_template_classes::ar_package::ARElement;
use crate::m2::autosar_templates::generic_structure::general_template_classes::identifiable::Referrable;
use crate::m2::autosar_templates::generic_structure::general_template_classes::identifiable::ShortNameFragmentId;
use crate::m2::autosar_templates::generic_structure::general_template_classes::primitive_types::RefTypeId;
use crate::m2::msr::asam_hdo::admin_data::AdminDataId;
use crate::m2::msr::documentation::annotation::AnnotationId;
use crate::m2::msr::documentation::text_model::block_elements::DocumentationBlockId;
use crate::m2::msr::documentation::text_model::multilanguage_data::MultiLanguageOverviewParagraphId;
use crate::m2::msr::documentation::text_model::multilanguage_data::MultilanguageLongNameId;
use crate::Document;

/// spec class `DiagnosticConnection`
/// DiagnosticConncection that is used to describe the relationship between several TP connections.
#[derive(Debug, Default)]
pub struct DiagnosticConnection {
    base: ARElement,
    functional_request_refs: Vec<RefTypeId>,
    periodic_response_uudt_refs: Vec<RefTypeId>,
    physical_request_ref: Option<RefTypeId>,
    response_ref: Option<RefTypeId>,
    response_on_event_ref: Option<RefTypeId>,
}

impl DiagnosticConnection {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn base(&self) -> &ARElement {
        &self.base
    }

    pub fn base_mut(&mut self) -> &mut ARElement {
        &mut self.base
    }

    pub fn get_functional_request_refs(&self) -> &[RefTypeId] {
        &self.functional_request_refs
    }

    pub fn push_functional_request_ref(&mut self, value: RefTypeId) {
        self.functional_request_refs.push(value);
    }

    pub fn get_periodic_response_uudt_refs(&self) -> &[RefTypeId] {
        &self.periodic_response_uudt_refs
    }

    pub fn push_periodic_response_uudt_ref(&mut self, value: RefTypeId) {
        self.periodic_response_uudt_refs.push(value);
    }

    pub fn get_physical_request_ref(&self) -> Option<RefTypeId> {
        self.physical_request_ref
    }

    pub fn set_physical_request_ref(&mut self, value: RefTypeId) -> &mut Self {
        self.physical_request_ref = Some(value);
        self
    }

    pub fn get_response_ref(&self) -> Option<RefTypeId> {
        self.response_ref
    }

    pub fn set_response_ref(&mut self, value: RefTypeId) -> &mut Self {
        self.response_ref = Some(value);
        self
    }

    pub fn get_response_on_event_ref(&self) -> Option<RefTypeId> {
        self.response_on_event_ref
    }

    pub fn set_response_on_event_ref(&mut self, value: RefTypeId) -> &mut Self {
        self.response_on_event_ref = Some(value);
        self
    }

    pub fn get_admin_data(&self) -> Option<AdminDataId> {
        self.base().base().base().base().get_admin_data()
    }

    pub fn set_admin_data(&mut self, value: AdminDataId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_admin_data(value);
        self
    }

    pub fn remove_admin_data(&mut self) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .remove_admin_data();
        self
    }

    pub fn get_annotations(&self) -> &[AnnotationId] {
        self.base().base().base().base().get_annotations()
    }

    pub fn push_annotation(&mut self, value: AnnotationId) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .push_annotation(value)
    }

    pub fn get_category(&self) -> Option<&str> {
        self.base().base().base().base().get_category()
    }

    pub fn set_category(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_category(value);
        self
    }

    pub fn get_desc(&self) -> Option<MultiLanguageOverviewParagraphId> {
        self.base().base().base().base().get_desc()
    }

    pub fn set_desc(&mut self, value: MultiLanguageOverviewParagraphId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_desc(value);
        self
    }

    pub fn get_introduction(&self) -> Option<DocumentationBlockId> {
        self.base().base().base().base().get_introduction()
    }

    pub fn set_introduction(&mut self, value: DocumentationBlockId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_introduction(value);
        self
    }

    pub fn get_uuid(&self) -> Option<&str> {
        self.base().base().base().base().get_uuid()
    }

    pub fn set_uuid(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_uuid(value);
        self
    }

    pub fn get_elements(&self) -> &[ElementRef] {
        self.base().base().base().base().get_elements()
    }

    pub fn push_element(&mut self, value: ElementRef) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .push_element(value)
    }

    pub fn get_long_name(&self) -> Option<MultilanguageLongNameId> {
        self.base().base().base().base().base().get_long_name()
    }

    pub fn set_long_name(&mut self, value: MultilanguageLongNameId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_long_name(value);
        self
    }

    pub fn get_short_name_fragments(&self) -> &[ShortNameFragmentId] {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_short_name_fragments()
    }

    pub fn push_short_name_fragment(&mut self, value: ShortNameFragmentId) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .push_short_name_fragment(value)
    }

    pub fn get_short_name(&self) -> Option<&str> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_short_name()
    }

    pub fn set_short_name(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_short_name(value);
        self
    }

    pub fn get_checksum(&self) -> Option<&str> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_checksum()
    }

    pub fn set_checksum(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_checksum(value);
        self
    }

    pub fn get_timestamp(&self) -> Option<&str> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_timestamp()
    }

    pub fn set_timestamp(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_timestamp(value);
        self
    }

    pub fn get_parent(&self) -> Option<ElementRef> {
        self.base().base().base().base().base().base().get_parent()
    }

    pub fn set_parent(&mut self, parent: Option<ElementRef>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_parent(parent);
        self
    }
}

/// spec class `DoIpTpConnection`
/// A connection identifies the sender and the receiver of this particular communication. The DoIp module routes a tpSdu through this connection.
#[derive(Debug, Default)]
pub struct DoIpTpConnection {
    base: TpConnection,
    do_ip_source_address_ref: Option<RefTypeId>,
    do_ip_target_address_ref: Option<RefTypeId>,
    tp_sdu_ref: Option<RefTypeId>,
}

impl DoIpTpConnection {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn base(&self) -> &TpConnection {
        &self.base
    }

    pub fn base_mut(&mut self) -> &mut TpConnection {
        &mut self.base
    }

    pub fn get_do_ip_source_address_ref(&self) -> Option<RefTypeId> {
        self.do_ip_source_address_ref
    }

    pub fn set_do_ip_source_address_ref(&mut self, value: RefTypeId) -> &mut Self {
        self.do_ip_source_address_ref = Some(value);
        self
    }

    pub fn get_do_ip_target_address_ref(&self) -> Option<RefTypeId> {
        self.do_ip_target_address_ref
    }

    pub fn set_do_ip_target_address_ref(&mut self, value: RefTypeId) -> &mut Self {
        self.do_ip_target_address_ref = Some(value);
        self
    }

    pub fn get_tp_sdu_ref(&self) -> Option<RefTypeId> {
        self.tp_sdu_ref
    }

    pub fn set_tp_sdu_ref(&mut self, value: RefTypeId) -> &mut Self {
        self.tp_sdu_ref = Some(value);
        self
    }

    pub fn get_ident(&self) -> Option<TpConnectionIdentId> {
        self.base().get_ident()
    }

    pub fn set_ident(&mut self, value: TpConnectionIdentId) -> &mut Self {
        self.base_mut().set_ident(value);
        self
    }

    pub fn get_checksum(&self) -> Option<&str> {
        self.base().base().get_checksum()
    }

    pub fn set_checksum(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().base_mut().set_checksum(value);
        self
    }

    pub fn get_timestamp(&self) -> Option<&str> {
        self.base().base().get_timestamp()
    }

    pub fn set_timestamp(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().base_mut().set_timestamp(value);
        self
    }
}

/// spec class `TpConnection` (abstract)
/// TpConnection Base Class.
#[derive(Debug, Default)]
pub struct TpConnection {
    base: ARObject,
    ident: Option<TpConnectionIdentId>,
}

impl TpConnection {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn base(&self) -> &ARObject {
        &self.base
    }

    pub fn base_mut(&mut self) -> &mut ARObject {
        &mut self.base
    }

    pub fn get_ident(&self) -> Option<TpConnectionIdentId> {
        self.ident
    }

    pub fn set_ident(&mut self, value: TpConnectionIdentId) -> &mut Self {
        self.ident = Some(value);
        self
    }

    pub fn get_checksum(&self) -> Option<&str> {
        self.base().get_checksum()
    }

    pub fn set_checksum(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_checksum(value);
        self
    }

    pub fn get_timestamp(&self) -> Option<&str> {
        self.base().get_timestamp()
    }

    pub fn set_timestamp(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_timestamp(value);
        self
    }
}

/// spec class `TpConnectionIdent`
/// This meta-class is created to add the ability to become the target of a reference to the non-Referrable Tp Connection.
#[derive(Debug, Default)]
pub struct TpConnectionIdent {
    base: Referrable,
}

impl TpConnectionIdent {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn base(&self) -> &Referrable {
        &self.base
    }

    pub fn base_mut(&mut self) -> &mut Referrable {
        &mut self.base
    }

    pub fn get_short_name_fragments(&self) -> &[ShortNameFragmentId] {
        self.base().get_short_name_fragments()
    }

    pub fn push_short_name_fragment(&mut self, value: ShortNameFragmentId) {
        self.base_mut().push_short_name_fragment(value)
    }

    pub fn get_short_name(&self) -> Option<&str> {
        self.base().get_short_name()
    }

    pub fn set_short_name(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_short_name(value);
        self
    }

    pub fn get_checksum(&self) -> Option<&str> {
        self.base().base().get_checksum()
    }

    pub fn set_checksum(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().base_mut().set_checksum(value);
        self
    }

    pub fn get_timestamp(&self) -> Option<&str> {
        self.base().base().get_timestamp()
    }

    pub fn set_timestamp(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().base_mut().set_timestamp(value);
        self
    }

    pub fn get_parent(&self) -> Option<ElementRef> {
        self.base().get_parent()
    }

    pub fn set_parent(&mut self, parent: Option<ElementRef>) -> &mut Self {
        self.base_mut().set_parent(parent);
        self
    }
}

impl Document {
    pub(crate) fn compare_diagnostic_connection(
        &self,
        other: &Document,
        a: &DiagnosticConnection,
        b: &DiagnosticConnection,
        path: &str,
    ) -> Result<(), String> {
        self.compare_ar_element(other, a.base(), b.base(), path)?;
        let list_a = a.get_functional_request_refs();
        let list_b = b.get_functional_request_refs();
        if list_a.len() != list_b.len() {
            return Err(format!("{path}: FUNCTIONAL_REQUEST_REFS length mismatch"));
        }
        for (index, (x, y)) in list_a.iter().zip(list_b.iter()).enumerate() {
            let x = self.ref_types.get(*x).ok_or_else(|| {
                format!("{path}.FUNCTIONAL_REQUEST_REFS[{index}]: id not found in own arena")
            })?;
            let y = other.ref_types.get(*y).ok_or_else(|| {
                format!("{path}.FUNCTIONAL_REQUEST_REFS[{index}]: id not found in other arena")
            })?;
            self.compare_ref_type(
                other,
                x,
                y,
                &format!("{path}.FUNCTIONAL_REQUEST_REFS[{index}]"),
            )?;
        }
        let list_a = a.get_periodic_response_uudt_refs();
        let list_b = b.get_periodic_response_uudt_refs();
        if list_a.len() != list_b.len() {
            return Err(format!(
                "{path}: PERIODIC_RESPONSE_UUDT_REFS length mismatch"
            ));
        }
        for (index, (x, y)) in list_a.iter().zip(list_b.iter()).enumerate() {
            let x = self.ref_types.get(*x).ok_or_else(|| {
                format!("{path}.PERIODIC_RESPONSE_UUDT_REFS[{index}]: id not found in own arena")
            })?;
            let y = other.ref_types.get(*y).ok_or_else(|| {
                format!("{path}.PERIODIC_RESPONSE_UUDT_REFS[{index}]: id not found in other arena")
            })?;
            self.compare_ref_type(
                other,
                x,
                y,
                &format!("{path}.PERIODIC_RESPONSE_UUDT_REFS[{index}]"),
            )?;
        }
        if a.get_physical_request_ref() != b.get_physical_request_ref() {
            return Err(format!("{path}: PHYSICAL_REQUEST_REF mismatch"));
        }
        if a.get_response_ref() != b.get_response_ref() {
            return Err(format!("{path}: RESPONSE_REF mismatch"));
        }
        if a.get_response_on_event_ref() != b.get_response_on_event_ref() {
            return Err(format!("{path}: RESPONSE_ON_EVENT_REF mismatch"));
        }
        Ok(())
    }

    pub(crate) fn compare_do_ip_tp_connection(
        &self,
        other: &Document,
        a: &DoIpTpConnection,
        b: &DoIpTpConnection,
        path: &str,
    ) -> Result<(), String> {
        self.compare_tp_connection(other, a.base(), b.base(), path)?;
        if a.get_do_ip_source_address_ref() != b.get_do_ip_source_address_ref() {
            return Err(format!("{path}: DO_IP_SOURCE_ADDRESS_REF mismatch"));
        }
        if a.get_do_ip_target_address_ref() != b.get_do_ip_target_address_ref() {
            return Err(format!("{path}: DO_IP_TARGET_ADDRESS_REF mismatch"));
        }
        if a.get_tp_sdu_ref() != b.get_tp_sdu_ref() {
            return Err(format!("{path}: TP_SDU_REF mismatch"));
        }
        Ok(())
    }

    pub(crate) fn compare_tp_connection(
        &self,
        _other: &Document,
        a: &TpConnection,
        b: &TpConnection,
        path: &str,
    ) -> Result<(), String> {
        Self::compare_ar_object(a.base(), b.base(), path)?;
        if a.get_ident() != b.get_ident() {
            return Err(format!("{path}: IDENT mismatch"));
        }
        Ok(())
    }

    pub(crate) fn compare_tp_connection_ident(
        &self,
        other: &Document,
        a: &TpConnectionIdent,
        b: &TpConnectionIdent,
        path: &str,
    ) -> Result<(), String> {
        self.compare_referrable(other, a.base(), b.base(), path)?;
        Ok(())
    }
}
