// @generated by tools/py2rust from py-armodel models/M2 (see PY_ARMODEL_VERSION). Do not edit.

//! generated from spec package: m2::msr::data_dictionary::data_def_properties

use slotmap::new_key_type;

new_key_type! {
    pub struct SwBitRepresentationId;
    pub struct SwDataDefPropsId;
    pub struct SwDataDependencyId;
    pub struct SwDataDependencyArgsId;
    pub struct SwPointerTargetPropsId;
    pub struct SwTextPropsId;
    pub struct ValueListId;
}

use crate::m2::autosar_templates::generic_structure::general_template_classes::ar_object::ARObject;
use crate::m2::msr::documentation::annotation::AnnotationId;
use crate::m2::msr::asam_hdo::computation_method::CompuGenericMathId;
use crate::m2::autosar_templates::generic_structure::general_template_classes::ar_object::ElementRef;
use crate::m2::autosar_templates::generic_structure::general_template_classes::multidimensional_time::MultidimensionalTimeId;
use crate::m2::autosar_templates::generic_structure::general_template_classes::primitive_types::RefTypeId;
use crate::m2::msr::data_dictionary::calibration_parameter::SwCalprmAxisSetId;
use crate::m2::msr::data_dictionary::datadictionary_proxies::SwCalprmRefProxyId;
use crate::m2::msr::data_dictionary::datadictionary_proxies::SwVariableRefProxyId;
use crate::Document;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DisplayPresentationEnum {
    PresentationContinuous,
    PresentationDiscrete,
}

impl DisplayPresentationEnum {
    pub fn as_str(&self) -> &'static str {
        match self {
            DisplayPresentationEnum::PresentationContinuous => "presentationContinuous",
            DisplayPresentationEnum::PresentationDiscrete => "presentationDiscrete",
        }
    }
}

impl TryFrom<&str> for DisplayPresentationEnum {
    type Error = ();

    fn try_from(value: &str) -> Result<Self, ()> {
        match value {
            "presentationContinuous" => Ok(DisplayPresentationEnum::PresentationContinuous),
            "presentationDiscrete" => Ok(DisplayPresentationEnum::PresentationDiscrete),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SwCalibrationAccessEnum {
    NotAccessible,
    ReadOnly,
    ReadWrite,
}

impl SwCalibrationAccessEnum {
    pub fn as_str(&self) -> &'static str {
        match self {
            SwCalibrationAccessEnum::NotAccessible => "notAccessible",
            SwCalibrationAccessEnum::ReadOnly => "readOnly",
            SwCalibrationAccessEnum::ReadWrite => "readWrite",
        }
    }
}

impl TryFrom<&str> for SwCalibrationAccessEnum {
    type Error = ();

    fn try_from(value: &str) -> Result<Self, ()> {
        match value {
            "notAccessible" => Ok(SwCalibrationAccessEnum::NotAccessible),
            "readOnly" => Ok(SwCalibrationAccessEnum::ReadOnly),
            "readWrite" => Ok(SwCalibrationAccessEnum::ReadWrite),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SwImplPolicyEnum {
    Const,
    Fixed,
    MeasurementPoint,
    Queued,
    Standard,
}

impl SwImplPolicyEnum {
    pub fn as_str(&self) -> &'static str {
        match self {
            SwImplPolicyEnum::Const => "const",
            SwImplPolicyEnum::Fixed => "fixed",
            SwImplPolicyEnum::MeasurementPoint => "measurementPoint",
            SwImplPolicyEnum::Queued => "queued",
            SwImplPolicyEnum::Standard => "standard",
        }
    }
}

impl TryFrom<&str> for SwImplPolicyEnum {
    type Error = ();

    fn try_from(value: &str) -> Result<Self, ()> {
        match value {
            "const" => Ok(SwImplPolicyEnum::Const),
            "fixed" => Ok(SwImplPolicyEnum::Fixed),
            "measurementPoint" => Ok(SwImplPolicyEnum::MeasurementPoint),
            "queued" => Ok(SwImplPolicyEnum::Queued),
            "standard" => Ok(SwImplPolicyEnum::Standard),
            _ => Err(()),
        }
    }
}

/// spec class `SwBitRepresentation`
/// Description of the structure of a bit variable: Comprises of the bitPosition in a memory object (e.g. sw HostVariable, which stands parallel to swBitRepresentation) and the numberOfBits . In this way, interrelated memory areas can be described. Non-related memory areas are not supported.
#[derive(Debug, Default)]
pub struct SwBitRepresentation {
    base: ARObject,
    bit_position: Option<String>,
    number_of_bits: Option<String>,
}

impl SwBitRepresentation {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn base(&self) -> &ARObject {
        &self.base
    }

    pub fn base_mut(&mut self) -> &mut ARObject {
        &mut self.base
    }

    pub fn get_bit_position(&self) -> Option<&str> {
        self.bit_position.as_deref()
    }

    pub fn set_bit_position(&mut self, value: impl Into<String>) -> &mut Self {
        self.bit_position = Some(value.into());
        self
    }

    pub fn get_number_of_bits(&self) -> Option<&str> {
        self.number_of_bits.as_deref()
    }

    pub fn set_number_of_bits(&mut self, value: impl Into<String>) -> &mut Self {
        self.number_of_bits = Some(value.into());
        self
    }

    pub fn get_checksum(&self) -> Option<&str> {
        self.base().get_checksum()
    }

    pub fn set_checksum(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_checksum(value);
        self
    }

    pub fn get_timestamp(&self) -> Option<&str> {
        self.base().get_timestamp()
    }

    pub fn set_timestamp(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_timestamp(value);
        self
    }
}

/// spec class `SwDataDefProps`
/// This class is a collection of properties relevant for data objects under various aspects. One could consider this class as a "pattern of inheritance by aggregation". The properties can be applied to all objects of all classes in which SwDataDefProps is aggregated. Note that not all of the attributes or associated elements are useful all of the time. Hence, the process definition (e.g. expressed with an OCL or a Document Control Instance MSR-DCI) has the task of implementing limitations. SwDataDefProps covers various aspects: • Structure of the data element for calibration use cases: is it a single value, a curve, or a map, but also the recordLayouts which specify how such elements are mapped/converted to the DataTypes in the programming language (or in AUTOSAR). This is mainly expressed by properties like swRecordLayout and swCalprmAxisSet • Implementation aspects, mainly expressed by swImplPolicy, swVariableAccessImplPolicy, swAddr Method, swPointerTagetProps, baseType, implementationDataType and additionalNativeTypeQualifier • Access policy for the MCD system, mainly expressed by swCalibrationAccess • Semantics of the data element, mainly expressed by compuMethod and/or unit, dataConstr, invalid Value • Code generation policy provided by swRecordLayout
#[derive(Debug, Default)]
pub struct SwDataDefProps {
    base: ARObject,
    display_presentation: Option<DisplayPresentationEnum>,
    step_size: Option<String>,
    sw_value_block_size_mults: Vec<String>,
    annotations: Vec<AnnotationId>,
    sw_addr_method_ref: Option<RefTypeId>,
    sw_alignment: Option<String>,
    base_type_ref: Option<RefTypeId>,
    sw_bit_representation: Option<SwBitRepresentationId>,
    sw_calibration_access: Option<String>,
    sw_value_block_size: Option<String>,
    sw_calprm_axis_set: Option<SwCalprmAxisSetId>,
    sw_text_props: Option<SwTextPropsId>,
    sw_comparison_variables: Vec<SwVariableRefProxyId>,
    compu_method_ref: Option<RefTypeId>,
    data_constr_ref: Option<RefTypeId>,
    sw_data_dependency: Option<SwDataDependencyId>,
    display_format: Option<String>,
    implementation_data_type_ref: Option<RefTypeId>,
    sw_host_variable: Option<SwVariableRefProxyId>,
    sw_impl_policy: Option<SwImplPolicyEnum>,
    additional_native_type_qualifier: Option<String>,
    sw_intended_resolution: Option<String>,
    sw_interpolation_method: Option<String>,
    invalid_value: Option<ElementRef>,
    sw_is_virtual: Option<String>,
    sw_pointer_target_props: Option<SwPointerTargetPropsId>,
    sw_record_layout_ref: Option<RefTypeId>,
    sw_refresh_timing: Option<MultidimensionalTimeId>,
    unit_ref: Option<RefTypeId>,
    value_axis_data_type_ref: Option<RefTypeId>,
}

impl SwDataDefProps {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn base(&self) -> &ARObject {
        &self.base
    }

    pub fn base_mut(&mut self) -> &mut ARObject {
        &mut self.base
    }

    pub fn get_display_presentation(&self) -> Option<DisplayPresentationEnum> {
        self.display_presentation
    }

    pub fn set_display_presentation(&mut self, value: DisplayPresentationEnum) -> &mut Self {
        self.display_presentation = Some(value);
        self
    }

    pub fn get_step_size(&self) -> Option<&str> {
        self.step_size.as_deref()
    }

    pub fn set_step_size(&mut self, value: impl Into<String>) -> &mut Self {
        self.step_size = Some(value.into());
        self
    }

    pub fn get_sw_value_block_size_mults(&self) -> &[String] {
        &self.sw_value_block_size_mults
    }

    pub fn push_sw_value_block_size_mult(&mut self, value: String) {
        self.sw_value_block_size_mults.push(value);
    }

    pub fn get_annotations(&self) -> &[AnnotationId] {
        &self.annotations
    }

    pub fn push_annotation(&mut self, value: AnnotationId) {
        self.annotations.push(value);
    }

    pub fn get_sw_addr_method_ref(&self) -> Option<RefTypeId> {
        self.sw_addr_method_ref
    }

    pub fn set_sw_addr_method_ref(&mut self, value: RefTypeId) -> &mut Self {
        self.sw_addr_method_ref = Some(value);
        self
    }

    pub fn get_sw_alignment(&self) -> Option<&str> {
        self.sw_alignment.as_deref()
    }

    pub fn set_sw_alignment(&mut self, value: impl Into<String>) -> &mut Self {
        self.sw_alignment = Some(value.into());
        self
    }

    pub fn get_base_type_ref(&self) -> Option<RefTypeId> {
        self.base_type_ref
    }

    pub fn set_base_type_ref(&mut self, value: RefTypeId) -> &mut Self {
        self.base_type_ref = Some(value);
        self
    }

    pub fn get_sw_bit_representation(&self) -> Option<SwBitRepresentationId> {
        self.sw_bit_representation
    }

    pub fn set_sw_bit_representation(&mut self, value: SwBitRepresentationId) -> &mut Self {
        self.sw_bit_representation = Some(value);
        self
    }

    pub fn get_sw_calibration_access(&self) -> Option<&str> {
        self.sw_calibration_access.as_deref()
    }

    pub fn set_sw_calibration_access(&mut self, value: impl Into<String>) -> &mut Self {
        self.sw_calibration_access = Some(value.into());
        self
    }

    pub fn get_sw_value_block_size(&self) -> Option<&str> {
        self.sw_value_block_size.as_deref()
    }

    pub fn set_sw_value_block_size(&mut self, value: impl Into<String>) -> &mut Self {
        self.sw_value_block_size = Some(value.into());
        self
    }

    pub fn get_sw_calprm_axis_set(&self) -> Option<SwCalprmAxisSetId> {
        self.sw_calprm_axis_set
    }

    pub fn set_sw_calprm_axis_set(&mut self, value: SwCalprmAxisSetId) -> &mut Self {
        self.sw_calprm_axis_set = Some(value);
        self
    }

    pub fn get_sw_text_props(&self) -> Option<SwTextPropsId> {
        self.sw_text_props
    }

    pub fn set_sw_text_props(&mut self, value: SwTextPropsId) -> &mut Self {
        self.sw_text_props = Some(value);
        self
    }

    pub fn get_sw_comparison_variables(&self) -> &[SwVariableRefProxyId] {
        &self.sw_comparison_variables
    }

    pub fn push_sw_comparison_variable(&mut self, value: SwVariableRefProxyId) {
        self.sw_comparison_variables.push(value);
    }

    pub fn get_compu_method_ref(&self) -> Option<RefTypeId> {
        self.compu_method_ref
    }

    pub fn set_compu_method_ref(&mut self, value: RefTypeId) -> &mut Self {
        self.compu_method_ref = Some(value);
        self
    }

    pub fn get_data_constr_ref(&self) -> Option<RefTypeId> {
        self.data_constr_ref
    }

    pub fn set_data_constr_ref(&mut self, value: RefTypeId) -> &mut Self {
        self.data_constr_ref = Some(value);
        self
    }

    pub fn get_sw_data_dependency(&self) -> Option<SwDataDependencyId> {
        self.sw_data_dependency
    }

    pub fn set_sw_data_dependency(&mut self, value: SwDataDependencyId) -> &mut Self {
        self.sw_data_dependency = Some(value);
        self
    }

    pub fn get_display_format(&self) -> Option<&str> {
        self.display_format.as_deref()
    }

    pub fn set_display_format(&mut self, value: impl Into<String>) -> &mut Self {
        self.display_format = Some(value.into());
        self
    }

    pub fn get_implementation_data_type_ref(&self) -> Option<RefTypeId> {
        self.implementation_data_type_ref
    }

    pub fn set_implementation_data_type_ref(&mut self, value: RefTypeId) -> &mut Self {
        self.implementation_data_type_ref = Some(value);
        self
    }

    pub fn get_sw_host_variable(&self) -> Option<SwVariableRefProxyId> {
        self.sw_host_variable
    }

    pub fn set_sw_host_variable(&mut self, value: SwVariableRefProxyId) -> &mut Self {
        self.sw_host_variable = Some(value);
        self
    }

    pub fn get_sw_impl_policy(&self) -> Option<SwImplPolicyEnum> {
        self.sw_impl_policy
    }

    pub fn set_sw_impl_policy(&mut self, value: SwImplPolicyEnum) -> &mut Self {
        self.sw_impl_policy = Some(value);
        self
    }

    pub fn get_additional_native_type_qualifier(&self) -> Option<&str> {
        self.additional_native_type_qualifier.as_deref()
    }

    pub fn set_additional_native_type_qualifier(&mut self, value: impl Into<String>) -> &mut Self {
        self.additional_native_type_qualifier = Some(value.into());
        self
    }

    pub fn get_sw_intended_resolution(&self) -> Option<&str> {
        self.sw_intended_resolution.as_deref()
    }

    pub fn set_sw_intended_resolution(&mut self, value: impl Into<String>) -> &mut Self {
        self.sw_intended_resolution = Some(value.into());
        self
    }

    pub fn get_sw_interpolation_method(&self) -> Option<&str> {
        self.sw_interpolation_method.as_deref()
    }

    pub fn set_sw_interpolation_method(&mut self, value: impl Into<String>) -> &mut Self {
        self.sw_interpolation_method = Some(value.into());
        self
    }

    pub fn get_invalid_value(&self) -> Option<ElementRef> {
        self.invalid_value
    }

    pub fn set_invalid_value(&mut self, value: ElementRef) -> &mut Self {
        self.invalid_value = Some(value);
        self
    }

    pub fn get_sw_is_virtual(&self) -> Option<&str> {
        self.sw_is_virtual.as_deref()
    }

    pub fn set_sw_is_virtual(&mut self, value: impl Into<String>) -> &mut Self {
        self.sw_is_virtual = Some(value.into());
        self
    }

    pub fn get_sw_pointer_target_props(&self) -> Option<SwPointerTargetPropsId> {
        self.sw_pointer_target_props
    }

    pub fn set_sw_pointer_target_props(&mut self, value: SwPointerTargetPropsId) -> &mut Self {
        self.sw_pointer_target_props = Some(value);
        self
    }

    pub fn get_sw_record_layout_ref(&self) -> Option<RefTypeId> {
        self.sw_record_layout_ref
    }

    pub fn set_sw_record_layout_ref(&mut self, value: RefTypeId) -> &mut Self {
        self.sw_record_layout_ref = Some(value);
        self
    }

    pub fn get_sw_refresh_timing(&self) -> Option<MultidimensionalTimeId> {
        self.sw_refresh_timing
    }

    pub fn set_sw_refresh_timing(&mut self, value: MultidimensionalTimeId) -> &mut Self {
        self.sw_refresh_timing = Some(value);
        self
    }

    pub fn get_unit_ref(&self) -> Option<RefTypeId> {
        self.unit_ref
    }

    pub fn set_unit_ref(&mut self, value: RefTypeId) -> &mut Self {
        self.unit_ref = Some(value);
        self
    }

    pub fn get_value_axis_data_type_ref(&self) -> Option<RefTypeId> {
        self.value_axis_data_type_ref
    }

    pub fn set_value_axis_data_type_ref(&mut self, value: RefTypeId) -> &mut Self {
        self.value_axis_data_type_ref = Some(value);
        self
    }

    pub fn get_checksum(&self) -> Option<&str> {
        self.base().get_checksum()
    }

    pub fn set_checksum(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_checksum(value);
        self
    }

    pub fn get_timestamp(&self) -> Option<&str> {
        self.base().get_timestamp()
    }

    pub fn set_timestamp(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_timestamp(value);
        self
    }
}

/// spec class `SwDataDependency`
/// This element describes the interdependencies of data objects, e.g. variables and parameters. Use cases: • Calculate the value of a calibration parameter (by the MCD system) from the value(s) of other calibration parameters. • Virtual data - that means the data object is not directly in the ecu and this property describes how the "virtual variable" can be computed from the real ones (by the MCD system).
#[derive(Debug, Default)]
pub struct SwDataDependency {
    base: ARObject,
    sw_data_dependency_formula: Option<CompuGenericMathId>,
    sw_data_dependency_args: Option<SwDataDependencyArgsId>,
}

impl SwDataDependency {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn base(&self) -> &ARObject {
        &self.base
    }

    pub fn base_mut(&mut self) -> &mut ARObject {
        &mut self.base
    }

    pub fn get_sw_data_dependency_formula(&self) -> Option<CompuGenericMathId> {
        self.sw_data_dependency_formula
    }

    pub fn set_sw_data_dependency_formula(&mut self, value: CompuGenericMathId) -> &mut Self {
        self.sw_data_dependency_formula = Some(value);
        self
    }

    pub fn get_sw_data_dependency_args(&self) -> Option<SwDataDependencyArgsId> {
        self.sw_data_dependency_args
    }

    pub fn set_sw_data_dependency_args(&mut self, value: SwDataDependencyArgsId) -> &mut Self {
        self.sw_data_dependency_args = Some(value);
        self
    }

    pub fn get_checksum(&self) -> Option<&str> {
        self.base().get_checksum()
    }

    pub fn set_checksum(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_checksum(value);
        self
    }

    pub fn get_timestamp(&self) -> Option<&str> {
        self.base().get_timestamp()
    }

    pub fn set_timestamp(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_timestamp(value);
        self
    }
}

/// spec class `SwDataDependencyArgs`
/// This element specifies the elements used in a SwDataDependency.
#[derive(Debug, Default)]
pub struct SwDataDependencyArgs {
    base: ARObject,
    sw_calprm_ref: Option<SwCalprmRefProxyId>,
    sw_variable: Option<SwVariableRefProxyId>,
}

impl SwDataDependencyArgs {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn base(&self) -> &ARObject {
        &self.base
    }

    pub fn base_mut(&mut self) -> &mut ARObject {
        &mut self.base
    }

    pub fn get_sw_calprm_ref(&self) -> Option<SwCalprmRefProxyId> {
        self.sw_calprm_ref
    }

    pub fn set_sw_calprm_ref(&mut self, value: SwCalprmRefProxyId) -> &mut Self {
        self.sw_calprm_ref = Some(value);
        self
    }

    pub fn get_sw_variable(&self) -> Option<SwVariableRefProxyId> {
        self.sw_variable
    }

    pub fn set_sw_variable(&mut self, value: SwVariableRefProxyId) -> &mut Self {
        self.sw_variable = Some(value);
        self
    }

    pub fn get_checksum(&self) -> Option<&str> {
        self.base().get_checksum()
    }

    pub fn set_checksum(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_checksum(value);
        self
    }

    pub fn get_timestamp(&self) -> Option<&str> {
        self.base().get_timestamp()
    }

    pub fn set_timestamp(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_timestamp(value);
        self
    }
}

/// spec class `SwPointerTargetProps`
/// This element defines, that the data object (which is specified by the aggregating element) contains a reference to another data object or to a function in the CPU code. This corresponds to a pointer in the C-language. The attributes of this element describe the category and the detailed properties of the target which is either a data description or a function signature.
#[derive(Debug, Default)]
pub struct SwPointerTargetProps {
    base: ARObject,
    function_pointer_signature_ref: Option<RefTypeId>,
    sw_data_def_props: Option<SwDataDefPropsId>,
    target_category: Option<String>,
}

impl SwPointerTargetProps {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn base(&self) -> &ARObject {
        &self.base
    }

    pub fn base_mut(&mut self) -> &mut ARObject {
        &mut self.base
    }

    pub fn get_function_pointer_signature_ref(&self) -> Option<RefTypeId> {
        self.function_pointer_signature_ref
    }

    pub fn set_function_pointer_signature_ref(&mut self, value: RefTypeId) -> &mut Self {
        self.function_pointer_signature_ref = Some(value);
        self
    }

    pub fn get_sw_data_def_props(&self) -> Option<SwDataDefPropsId> {
        self.sw_data_def_props
    }

    pub fn set_sw_data_def_props(&mut self, value: SwDataDefPropsId) -> &mut Self {
        self.sw_data_def_props = Some(value);
        self
    }

    pub fn get_target_category(&self) -> Option<&str> {
        self.target_category.as_deref()
    }

    pub fn set_target_category(&mut self, value: impl Into<String>) -> &mut Self {
        self.target_category = Some(value.into());
        self
    }

    pub fn get_checksum(&self) -> Option<&str> {
        self.base().get_checksum()
    }

    pub fn set_checksum(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_checksum(value);
        self
    }

    pub fn get_timestamp(&self) -> Option<&str> {
        self.base().get_timestamp()
    }

    pub fn set_timestamp(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_timestamp(value);
        self
    }
}

/// spec class `SwTextProps`
/// This meta-class expresses particular properties applicable to strings in variables or calibration parameters.
#[derive(Debug, Default)]
pub struct SwTextProps {
    base: ARObject,
    array_size_semantics: Option<String>,
    base_type_ref: Option<RefTypeId>,
    sw_fill_character: Option<String>,
    sw_max_text_size: Option<String>,
}

impl SwTextProps {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn base(&self) -> &ARObject {
        &self.base
    }

    pub fn base_mut(&mut self) -> &mut ARObject {
        &mut self.base
    }

    pub fn get_array_size_semantics(&self) -> Option<&str> {
        self.array_size_semantics.as_deref()
    }

    pub fn set_array_size_semantics(&mut self, value: impl Into<String>) -> &mut Self {
        self.array_size_semantics = Some(value.into());
        self
    }

    pub fn get_base_type_ref(&self) -> Option<RefTypeId> {
        self.base_type_ref
    }

    pub fn set_base_type_ref(&mut self, value: RefTypeId) -> &mut Self {
        self.base_type_ref = Some(value);
        self
    }

    pub fn get_sw_fill_character(&self) -> Option<&str> {
        self.sw_fill_character.as_deref()
    }

    pub fn set_sw_fill_character(&mut self, value: impl Into<String>) -> &mut Self {
        self.sw_fill_character = Some(value.into());
        self
    }

    pub fn get_sw_max_text_size(&self) -> Option<&str> {
        self.sw_max_text_size.as_deref()
    }

    pub fn set_sw_max_text_size(&mut self, value: impl Into<String>) -> &mut Self {
        self.sw_max_text_size = Some(value.into());
        self
    }

    pub fn get_checksum(&self) -> Option<&str> {
        self.base().get_checksum()
    }

    pub fn set_checksum(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_checksum(value);
        self
    }

    pub fn get_timestamp(&self) -> Option<&str> {
        self.base().get_timestamp()
    }

    pub fn set_timestamp(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_timestamp(value);
        self
    }
}

/// spec class `ValueList`
/// This is a generic list of numerical values.
#[derive(Debug, Default)]
pub struct ValueList {
    base: ARObject,
    v: Option<String>,
    vf: Vec<String>,
}

impl ValueList {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn base(&self) -> &ARObject {
        &self.base
    }

    pub fn base_mut(&mut self) -> &mut ARObject {
        &mut self.base
    }

    pub fn get_v(&self) -> Option<&str> {
        self.v.as_deref()
    }

    pub fn set_v(&mut self, value: impl Into<String>) -> &mut Self {
        self.v = Some(value.into());
        self
    }

    pub fn get_vf(&self) -> &[String] {
        &self.vf
    }

    pub fn push_vf(&mut self, value: String) {
        self.vf.push(value);
    }

    pub fn get_checksum(&self) -> Option<&str> {
        self.base().get_checksum()
    }

    pub fn set_checksum(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_checksum(value);
        self
    }

    pub fn get_timestamp(&self) -> Option<&str> {
        self.base().get_timestamp()
    }

    pub fn set_timestamp(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_timestamp(value);
        self
    }
}

impl Document {
    pub(crate) fn compare_sw_bit_representation(
        &self,
        _other: &Document,
        a: &SwBitRepresentation,
        b: &SwBitRepresentation,
        path: &str,
    ) -> Result<(), String> {
        Self::compare_ar_object(a.base(), b.base(), path)?;
        if a.get_bit_position() != b.get_bit_position() {
            return Err(format!("{path}: BIT_POSITION mismatch"));
        }
        if a.get_number_of_bits() != b.get_number_of_bits() {
            return Err(format!("{path}: NUMBER_OF_BITS mismatch"));
        }
        Ok(())
    }

    pub(crate) fn compare_sw_data_def_props(
        &self,
        other: &Document,
        a: &SwDataDefProps,
        b: &SwDataDefProps,
        path: &str,
    ) -> Result<(), String> {
        Self::compare_ar_object(a.base(), b.base(), path)?;
        if a.get_display_presentation() != b.get_display_presentation() {
            return Err(format!("{path}: DISPLAY_PRESENTATION mismatch"));
        }
        if a.get_step_size() != b.get_step_size() {
            return Err(format!("{path}: STEP_SIZE mismatch"));
        }
        let list_a = a.get_sw_value_block_size_mults();
        let list_b = b.get_sw_value_block_size_mults();
        if list_a.len() != list_b.len() {
            return Err(format!("{path}: SW_VALUE_BLOCK_SIZE_MULTS length mismatch"));
        }
        for (index, (x, y)) in list_a.iter().zip(list_b.iter()).enumerate() {
            if x != y {
                return Err(format!(
                    "{path}.SW_VALUE_BLOCK_SIZE_MULTS[{index}] mismatch"
                ));
            }
        }
        let list_a = a.get_annotations();
        let list_b = b.get_annotations();
        if list_a.len() != list_b.len() {
            return Err(format!("{path}: ANNOTATIONS length mismatch"));
        }
        for (index, (x, y)) in list_a.iter().zip(list_b.iter()).enumerate() {
            let x = self
                .annotations
                .get(*x)
                .ok_or_else(|| format!("{path}.ANNOTATIONS[{index}]: id not found in own arena"))?;
            let y = other.annotations.get(*y).ok_or_else(|| {
                format!("{path}.ANNOTATIONS[{index}]: id not found in other arena")
            })?;
            self.compare_annotation(other, x, y, &format!("{path}.ANNOTATIONS[{index}]"))?;
        }
        if a.get_sw_addr_method_ref() != b.get_sw_addr_method_ref() {
            return Err(format!("{path}: SW_ADDR_METHOD_REF mismatch"));
        }
        if a.get_sw_alignment() != b.get_sw_alignment() {
            return Err(format!("{path}: SW_ALIGNMENT mismatch"));
        }
        if a.get_base_type_ref() != b.get_base_type_ref() {
            return Err(format!("{path}: BASE_TYPE_REF mismatch"));
        }
        if a.get_sw_bit_representation() != b.get_sw_bit_representation() {
            return Err(format!("{path}: SW_BIT_REPRESENTATION mismatch"));
        }
        if a.get_sw_calibration_access() != b.get_sw_calibration_access() {
            return Err(format!("{path}: SW_CALIBRATION_ACCESS mismatch"));
        }
        if a.get_sw_value_block_size() != b.get_sw_value_block_size() {
            return Err(format!("{path}: SW_VALUE_BLOCK_SIZE mismatch"));
        }
        if a.get_sw_calprm_axis_set() != b.get_sw_calprm_axis_set() {
            return Err(format!("{path}: SW_CALPRM_AXIS_SET mismatch"));
        }
        if a.get_sw_text_props() != b.get_sw_text_props() {
            return Err(format!("{path}: SW_TEXT_PROPS mismatch"));
        }
        let list_a = a.get_sw_comparison_variables();
        let list_b = b.get_sw_comparison_variables();
        if list_a.len() != list_b.len() {
            return Err(format!("{path}: SW_COMPARISON_VARIABLES length mismatch"));
        }
        for (index, (x, y)) in list_a.iter().zip(list_b.iter()).enumerate() {
            let x = self.sw_variable_ref_proxys.get(*x).ok_or_else(|| {
                format!("{path}.SW_COMPARISON_VARIABLES[{index}]: id not found in own arena")
            })?;
            let y = other.sw_variable_ref_proxys.get(*y).ok_or_else(|| {
                format!("{path}.SW_COMPARISON_VARIABLES[{index}]: id not found in other arena")
            })?;
            self.compare_sw_variable_ref_proxy(
                other,
                x,
                y,
                &format!("{path}.SW_COMPARISON_VARIABLES[{index}]"),
            )?;
        }
        if a.get_compu_method_ref() != b.get_compu_method_ref() {
            return Err(format!("{path}: COMPU_METHOD_REF mismatch"));
        }
        if a.get_data_constr_ref() != b.get_data_constr_ref() {
            return Err(format!("{path}: DATA_CONSTR_REF mismatch"));
        }
        if a.get_sw_data_dependency() != b.get_sw_data_dependency() {
            return Err(format!("{path}: SW_DATA_DEPENDENCY mismatch"));
        }
        if a.get_display_format() != b.get_display_format() {
            return Err(format!("{path}: DISPLAY_FORMAT mismatch"));
        }
        if a.get_implementation_data_type_ref() != b.get_implementation_data_type_ref() {
            return Err(format!("{path}: IMPLEMENTATION_DATA_TYPE_REF mismatch"));
        }
        if a.get_sw_host_variable() != b.get_sw_host_variable() {
            return Err(format!("{path}: SW_HOST_VARIABLE mismatch"));
        }
        if a.get_sw_impl_policy() != b.get_sw_impl_policy() {
            return Err(format!("{path}: SW_IMPL_POLICY mismatch"));
        }
        if a.get_additional_native_type_qualifier() != b.get_additional_native_type_qualifier() {
            return Err(format!("{path}: ADDITIONAL_NATIVE_TYPE_QUALIFIER mismatch"));
        }
        if a.get_sw_intended_resolution() != b.get_sw_intended_resolution() {
            return Err(format!("{path}: SW_INTENDED_RESOLUTION mismatch"));
        }
        if a.get_sw_interpolation_method() != b.get_sw_interpolation_method() {
            return Err(format!("{path}: SW_INTERPOLATION_METHOD mismatch"));
        }
        if a.get_invalid_value() != b.get_invalid_value() {
            return Err(format!("{path}: INVALID_VALUE mismatch"));
        }
        if a.get_sw_is_virtual() != b.get_sw_is_virtual() {
            return Err(format!("{path}: SW_IS_VIRTUAL mismatch"));
        }
        if a.get_sw_pointer_target_props() != b.get_sw_pointer_target_props() {
            return Err(format!("{path}: SW_POINTER_TARGET_PROPS mismatch"));
        }
        if a.get_sw_record_layout_ref() != b.get_sw_record_layout_ref() {
            return Err(format!("{path}: SW_RECORD_LAYOUT_REF mismatch"));
        }
        if a.get_sw_refresh_timing() != b.get_sw_refresh_timing() {
            return Err(format!("{path}: SW_REFRESH_TIMING mismatch"));
        }
        if a.get_unit_ref() != b.get_unit_ref() {
            return Err(format!("{path}: UNIT_REF mismatch"));
        }
        if a.get_value_axis_data_type_ref() != b.get_value_axis_data_type_ref() {
            return Err(format!("{path}: VALUE_AXIS_DATA_TYPE_REF mismatch"));
        }
        Ok(())
    }

    pub(crate) fn compare_sw_data_dependency(
        &self,
        _other: &Document,
        a: &SwDataDependency,
        b: &SwDataDependency,
        path: &str,
    ) -> Result<(), String> {
        Self::compare_ar_object(a.base(), b.base(), path)?;
        if a.get_sw_data_dependency_formula() != b.get_sw_data_dependency_formula() {
            return Err(format!("{path}: SW_DATA_DEPENDENCY_FORMULA mismatch"));
        }
        if a.get_sw_data_dependency_args() != b.get_sw_data_dependency_args() {
            return Err(format!("{path}: SW_DATA_DEPENDENCY_ARGS mismatch"));
        }
        Ok(())
    }

    pub(crate) fn compare_sw_data_dependency_args(
        &self,
        _other: &Document,
        a: &SwDataDependencyArgs,
        b: &SwDataDependencyArgs,
        path: &str,
    ) -> Result<(), String> {
        Self::compare_ar_object(a.base(), b.base(), path)?;
        if a.get_sw_calprm_ref() != b.get_sw_calprm_ref() {
            return Err(format!("{path}: SW_CALPRM_REF mismatch"));
        }
        if a.get_sw_variable() != b.get_sw_variable() {
            return Err(format!("{path}: SW_VARIABLE mismatch"));
        }
        Ok(())
    }

    pub(crate) fn compare_sw_pointer_target_props(
        &self,
        _other: &Document,
        a: &SwPointerTargetProps,
        b: &SwPointerTargetProps,
        path: &str,
    ) -> Result<(), String> {
        Self::compare_ar_object(a.base(), b.base(), path)?;
        if a.get_function_pointer_signature_ref() != b.get_function_pointer_signature_ref() {
            return Err(format!("{path}: FUNCTION_POINTER_SIGNATURE_REF mismatch"));
        }
        if a.get_sw_data_def_props() != b.get_sw_data_def_props() {
            return Err(format!("{path}: SW_DATA_DEF_PROPS mismatch"));
        }
        if a.get_target_category() != b.get_target_category() {
            return Err(format!("{path}: TARGET_CATEGORY mismatch"));
        }
        Ok(())
    }

    pub(crate) fn compare_sw_text_props(
        &self,
        _other: &Document,
        a: &SwTextProps,
        b: &SwTextProps,
        path: &str,
    ) -> Result<(), String> {
        Self::compare_ar_object(a.base(), b.base(), path)?;
        if a.get_array_size_semantics() != b.get_array_size_semantics() {
            return Err(format!("{path}: ARRAY_SIZE_SEMANTICS mismatch"));
        }
        if a.get_base_type_ref() != b.get_base_type_ref() {
            return Err(format!("{path}: BASE_TYPE_REF mismatch"));
        }
        if a.get_sw_fill_character() != b.get_sw_fill_character() {
            return Err(format!("{path}: SW_FILL_CHARACTER mismatch"));
        }
        if a.get_sw_max_text_size() != b.get_sw_max_text_size() {
            return Err(format!("{path}: SW_MAX_TEXT_SIZE mismatch"));
        }
        Ok(())
    }

    pub(crate) fn compare_value_list(
        &self,
        _other: &Document,
        a: &ValueList,
        b: &ValueList,
        path: &str,
    ) -> Result<(), String> {
        Self::compare_ar_object(a.base(), b.base(), path)?;
        if a.get_v() != b.get_v() {
            return Err(format!("{path}: V mismatch"));
        }
        let list_a = a.get_vf();
        let list_b = b.get_vf();
        if list_a.len() != list_b.len() {
            return Err(format!("{path}: VF length mismatch"));
        }
        for (index, (x, y)) in list_a.iter().zip(list_b.iter()).enumerate() {
            if x != y {
                return Err(format!("{path}.VF[{index}] mismatch"));
            }
        }
        Ok(())
    }
}
