import sys, unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from emit_model import emit_module
from extract import extract_source
from ir import ClassIr, FieldIr
from overrides import Overrides
from placement import Placement

FIXTURE = '''
from x import ARObject, AREnum, NameToken, VerbatimStringPlain
from typing import List, Optional


class Sd(ARObject):
    """This class represents a primitive element in a special data group."""

    def __init__(self):
        super().__init__()
        self.gid: Optional[NameToken] = None
        self.value: Optional[VerbatimStringPlain] = None
        self.xmlSpace: Optional[XmlSpaceEnum] = None


class Sdg(ARObject, VariationPointCapable):
    def __init__(self):
        super().__init__()
        self.gid: Optional[NameToken] = None
        self.sdgCaption: Optional[SdgCaption] = None
        self.sdgContentsType: Optional[SdgContents] = None


class SdgContents(ARObject):
    def __init__(self):
        super().__init__()
        self.sd: List[Sd] = []
        self.sdf: List[Sdf] = []
        self.sdg: List[Sdg] = []


class BindingTimeEnum(AREnum):
    CODE_GENERATION_TIME = "codeGenerationTime"
    LINK_TIME = "linkTime"
'''

# placement for the fixture; SdgCaption/Sdf live in another module, the pinned
# base chain lives at its real spec path
PLACEMENT = Placement({
    "Sd": "M2::Test::SpecialData",
    "Sdg": "M2::Test::SpecialData",
    "SdgContents": "M2::Test::SpecialData",
    "SdgCaption": "M2::Other",
    "Sdf": "M2::Other",
    "ApplicationSwComponentType": "M2::Swc",
    "ARObject": "M2::AUTOSARTemplates::GenericStructure::GeneralTemplateClasses::ArObject",
    "ARPackage": "M2::AUTOSARTemplates::GenericStructure::GeneralTemplateClasses::ARPackage",
    "CollectableElement": "M2::AUTOSARTemplates::GenericStructure::GeneralTemplateClasses::ElementCollection",
})


class TestEmitModule(unittest.TestCase):
    def setUp(self):
        self.ir = extract_source(FIXTURE, "m")
        # classes referenced by the fixture but defined in other py files
        arobject = ClassIr(name="ARObject", module_py="m", bases=[])
        arobject.fields = [
            FieldIr(name="checksum", type_expr="Optional[String]", kind="optional", inner="String"),
            FieldIr(name="timestamp", type_expr="Optional[DateTime]", kind="optional", inner="DateTime"),
        ]
        self.ir.add(arobject)
        self.ir.add(ClassIr(name="Sdf", module_py="m", bases=["ARObject"]))
        self.ir.add(ClassIr(name="SdgCaption", module_py="m", bases=["ARObject"]))
        self.ir.add(ClassIr(name="XmlSpaceEnum", module_py="m", bases=["AREnum"], is_enum=True))
        self.ir.add(ClassIr(name="NameToken", module_py="m", bases=["ARLiteral"], is_primitive=True))
        self.overrides = Overrides.default()

    def test_enum_only_module_has_no_key_types(self):
        out = emit_module(self.ir, self.overrides, PLACEMENT,
                          [self.ir.get("BindingTimeEnum")], ["m2", "test"])
        self.assertNotIn("new_key_type!", out)
        self.assertNotIn("use crate::Document;", out)
        self.assertIn("#[derive(Debug, Clone, Copy, PartialEq, Eq)]", out)
        self.assertIn("pub enum BindingTimeEnum {", out)
        self.assertIn('CodeGenerationTime => "codeGenerationTime"', out)

    def test_sd_struct_golden(self):
        out = emit_module(self.ir, self.overrides, PLACEMENT,
                          [self.ir.get("Sd")], ["m2", "test"])
        self.assertIn("// @generated by tools/py2rust", out)
        self.assertIn("pub struct Sd {", out)
        self.assertIn("base: ARObject,", out)
        self.assertIn("gid: Option<String>,", out)
        self.assertIn("xml_space: Option<XmlSpace>,", out)
        self.assertIn("pub fn get_gid(&self) -> Option<&str>", out)
        self.assertIn("pub fn set_gid(&mut self, value: impl Into<String>) -> &mut Self", out)
        self.assertIn("pub fn get_xml_space(&self) -> Option<XmlSpace>", out)
        self.assertIn("use crate::m2::autosar_templates::generic_structure::general_template_classes::ar_object::ARObject;",
                      out)
        self.assertIn("use crate::Document;", out)

    def test_link_fields_key_types_and_push_accessors(self):
        out = emit_module(self.ir, self.overrides, PLACEMENT,
                          [self.ir.get("Sdg"), self.ir.get("SdgContents")], ["m2", "test"])
        self.assertIn("pub struct SdgId;", out)
        self.assertIn("pub struct SdgContentsId;", out)
        self.assertIn("sdg_caption: Option<SdgCaptionId>,", out)
        self.assertIn("pub fn get_sd(&self) -> &[SdId]", out)
        self.assertIn("pub fn push_sd(&mut self, value: SdId)", out)
        self.assertIn("use crate::m2::other::SdgCaptionId;", out)


    def test_inherited_accessors_are_forwarded(self):
        out = emit_module(self.ir, self.overrides, PLACEMENT,
                          [self.ir.get("Sd")], ["m2", "test"])
        # ARObject's checksum/timestamp arrive through the base chain
        self.assertIn("pub fn get_checksum(&self) -> Option<&str> {", out)
        self.assertIn("self.base().get_checksum()", out)
        self.assertIn("pub fn set_checksum(&mut self, value: impl Into<String>) -> &mut Self", out)

    def test_parent_forwarder_from_referrable_template(self):
        self.ir.add(ClassIr(name="Referrable", module_py="m", bases=["ARObject"]))
        child = ClassIr(name="Child", module_py="m", bases=["Referrable"])
        self.ir.add(child)
        out = emit_module(self.ir, self.overrides, PLACEMENT, [child], ["m2", "test"])
        self.assertIn("pub fn set_parent(&mut self, parent: Option<ElementRef>) -> &mut Self", out)
        self.assertIn("self.base().set_parent(parent);", out)
        self.assertIn("use crate::m2::autosar_templates::generic_structure::general_template_classes::ar_object::ElementRef;",
                      out)


from emit_document import build_element_variants, emit_document_root, emit_equality, emit_registry


class TestEmitDocument(unittest.TestCase):
    def setUp(self):
        ir = extract_source(FIXTURE, "m")
        arobject = ClassIr(name="ARObject", module_py="m", bases=[])
        ir.add(arobject)
        ir.add(ClassIr(name="Sdf", module_py="m", bases=["ARObject"]))
        ir.add(ClassIr(name="ApplicationSwComponentType", module_py="m", bases=["ARObject"]))
        arpackage = ClassIr(name="ARPackage", module_py="m", bases=["CollectableElement"])
        arpackage.creates = {
            "createARPackage": "ARPackage",
            "createApplicationSwComponentType": "ApplicationSwComponentType",
        }
        ir.add(arpackage)
        self.ir = ir

    def test_element_variants_from_create_directory(self):
        variants = build_element_variants(self.ir)
        self.assertEqual(variants, ["ARPackage", "ApplicationSwComponentType"])

    def test_registry_maps_kebab_tags(self):
        code = emit_registry(self.ir, Overrides.default(), PLACEMENT, build_element_variants(self.ir))
        self.assertIn('"APPLICATION-SW-COMPONENT-TYPE" =>', code)
        self.assertIn("ElementRef::ApplicationSwComponentType(d.add_application_sw_component_type(p, n))", code)
        self.assertIn('"AR-PACKAGE" =>', code)

    def test_equality_emits_scalar_and_link_compare(self):
        code = emit_equality(self.ir, Overrides.default(), self.ir.get("SdgContents"))
        self.assertIn("fn compare_sdg_contents(", code)
        self.assertIn("let list_a = a.get_sd();", code)
        self.assertIn("if list_a.len() != list_b.len() {", code)
        self.assertIn('format!("{path}.SD[{index}]: id not found in own arena"', code)
        self.assertIn("self.compare_sd(other, x, y,", code)

    def test_document_root_surgery(self):
        code = emit_document_root(self.ir, Overrides.default(), PLACEMENT)
        # P0 compares that moved to generated modules are gone as definitions…
        self.assertNotIn("fn compare_admin_data(", code)
        self.assertNotIn("fn compare_sdg_contents(", code)
        # …but the assert skeleton still dispatches to them
        self.assertIn('self.compare_admin_data(other, admin_a, admin_b, "ADMIN-DATA")', code)
        self.assertIn("fn compare_ar_package(", code)  # P0-kept
        # uniform resolver + arena for a generated class
        self.assertIn("pub fn get_sdg_contents(&self, id: SdgContentsId) -> Option<&SdgContents>", code)
        self.assertIn("pub(crate) sdgs: SlotMap<SdgId, Sdg>,", code)
        # element factory generated, ARPackage factory kept
        self.assertIn("pub fn add_application_sw_component_type(", code)
        self.assertIn("pub fn add_ar_package(", code)
        # P0 tests survive the surgery
        self.assertIn("fn add_ar_package_links_parent_and_root(", code)
        self.assertIn("#[cfg(test)]", code)


if __name__ == "__main__":
    unittest.main()
