// @generated by tools/py2rust from py-armodel models/M2 (see PY_ARMODEL_VERSION). Do not edit.

//! generated from spec package: m2::autosar_templates::generic_structure::life_cycles

use slotmap::new_key_type;

new_key_type! {
    pub struct LifeCycleInfoId;
    pub struct LifeCycleInfoSetId;
    pub struct LifeCyclePeriodId;
    pub struct LifeCycleStateId;
    pub struct LifeCycleStateDefinitionGroupId;
}

use crate::m2::autosar_templates::generic_structure::general_template_classes::ar_package::ARElement;
use crate::m2::autosar_templates::generic_structure::general_template_classes::ar_object::ARObject;
use crate::m2::msr::asam_hdo::admin_data::AdminDataId;
use crate::m2::msr::documentation::annotation::AnnotationId;
use crate::m2::autosar_templates::common_structure::standardization_template::abstract_blueprint_structure::AtpBlueprint;
use crate::m2::msr::documentation::text_model::block_elements::DocumentationBlockId;
use crate::m2::autosar_templates::generic_structure::general_template_classes::ar_object::ElementRef;
use crate::m2::msr::documentation::text_model::multilanguage_data::MultiLanguageOverviewParagraphId;
use crate::m2::msr::documentation::text_model::multilanguage_data::MultilanguageLongNameId;
use crate::m2::autosar_templates::generic_structure::general_template_classes::identifiable::ShortNameFragmentId;
use crate::Document;

/// spec class `LifeCycleInfo`
/// LifeCycleInfo describes the life cycle state of an element together with additional information like what to use instead
#[derive(Debug, Default)]
pub struct LifeCycleInfo {
    base: ARObject,
    lc_object_ref: Option<String>,
    lc_state_ref: Option<String>,
    period_begin: Option<LifeCyclePeriodId>,
    period_end: Option<LifeCyclePeriodId>,
    remark: Option<DocumentationBlockId>,
    use_instead_refs: Vec<String>,
}

impl LifeCycleInfo {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn base(&self) -> &ARObject {
        &self.base
    }

    pub fn base_mut(&mut self) -> &mut ARObject {
        &mut self.base
    }

    pub fn get_lc_object_ref(&self) -> Option<&str> {
        self.lc_object_ref.as_deref()
    }

    pub fn set_lc_object_ref(&mut self, value: impl Into<String>) -> &mut Self {
        self.lc_object_ref = Some(value.into());
        self
    }

    pub fn get_lc_state_ref(&self) -> Option<&str> {
        self.lc_state_ref.as_deref()
    }

    pub fn set_lc_state_ref(&mut self, value: impl Into<String>) -> &mut Self {
        self.lc_state_ref = Some(value.into());
        self
    }

    pub fn get_period_begin(&self) -> Option<LifeCyclePeriodId> {
        self.period_begin
    }

    pub fn set_period_begin(&mut self, value: LifeCyclePeriodId) -> &mut Self {
        self.period_begin = Some(value);
        self
    }

    pub fn get_period_end(&self) -> Option<LifeCyclePeriodId> {
        self.period_end
    }

    pub fn set_period_end(&mut self, value: LifeCyclePeriodId) -> &mut Self {
        self.period_end = Some(value);
        self
    }

    pub fn get_remark(&self) -> Option<DocumentationBlockId> {
        self.remark
    }

    pub fn set_remark(&mut self, value: DocumentationBlockId) -> &mut Self {
        self.remark = Some(value);
        self
    }

    pub fn get_use_instead_refs(&self) -> &[String] {
        &self.use_instead_refs
    }

    pub fn push_use_instead_ref(&mut self, value: String) {
        self.use_instead_refs.push(value);
    }

    pub fn get_checksum(&self) -> Option<&str> {
        self.base().get_checksum()
    }

    pub fn set_checksum(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_checksum(value);
        self
    }

    pub fn get_timestamp(&self) -> Option<&str> {
        self.base().get_timestamp()
    }

    pub fn set_timestamp(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_timestamp(value);
        self
    }
}

/// spec class `LifeCycleInfoSet`
/// This meta class represents the ability to attach a life cycle information to a particular set of elements. The information can be defined for a particular period. This supports the definition of transition plans. If no period is specified, the life cycle state applies forever. Tags: atp.recommendedPackage=LifeCycleInfoSets
#[derive(Debug, Default)]
pub struct LifeCycleInfoSet {
    base: ARElement,
    default_lc_state_ref: Option<String>,
    default_period_begin: Option<LifeCyclePeriodId>,
    default_period_end: Option<LifeCyclePeriodId>,
    life_cycle_infos: Vec<LifeCycleInfoId>,
    used_life_cycle_state_definition_group_ref: Option<String>,
}

impl LifeCycleInfoSet {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn base(&self) -> &ARElement {
        &self.base
    }

    pub fn base_mut(&mut self) -> &mut ARElement {
        &mut self.base
    }

    pub fn get_default_lc_state_ref(&self) -> Option<&str> {
        self.default_lc_state_ref.as_deref()
    }

    pub fn set_default_lc_state_ref(&mut self, value: impl Into<String>) -> &mut Self {
        self.default_lc_state_ref = Some(value.into());
        self
    }

    pub fn get_default_period_begin(&self) -> Option<LifeCyclePeriodId> {
        self.default_period_begin
    }

    pub fn set_default_period_begin(&mut self, value: LifeCyclePeriodId) -> &mut Self {
        self.default_period_begin = Some(value);
        self
    }

    pub fn get_default_period_end(&self) -> Option<LifeCyclePeriodId> {
        self.default_period_end
    }

    pub fn set_default_period_end(&mut self, value: LifeCyclePeriodId) -> &mut Self {
        self.default_period_end = Some(value);
        self
    }

    pub fn get_life_cycle_infos(&self) -> &[LifeCycleInfoId] {
        &self.life_cycle_infos
    }

    pub fn push_life_cycle_info(&mut self, value: LifeCycleInfoId) {
        self.life_cycle_infos.push(value);
    }

    pub fn get_used_life_cycle_state_definition_group_ref(&self) -> Option<&str> {
        self.used_life_cycle_state_definition_group_ref.as_deref()
    }

    pub fn set_used_life_cycle_state_definition_group_ref(
        &mut self,
        value: impl Into<String>,
    ) -> &mut Self {
        self.used_life_cycle_state_definition_group_ref = Some(value.into());
        self
    }

    pub fn get_admin_data(&self) -> Option<AdminDataId> {
        self.base().base().base().base().get_admin_data()
    }

    pub fn set_admin_data(&mut self, value: AdminDataId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_admin_data(value);
        self
    }

    pub fn remove_admin_data(&mut self) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .remove_admin_data();
        self
    }

    pub fn get_annotations(&self) -> &[AnnotationId] {
        self.base().base().base().base().get_annotations()
    }

    pub fn push_annotation(&mut self, value: AnnotationId) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .push_annotation(value)
    }

    pub fn get_category(&self) -> Option<&str> {
        self.base().base().base().base().get_category()
    }

    pub fn set_category(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_category(value);
        self
    }

    pub fn get_desc(&self) -> Option<MultiLanguageOverviewParagraphId> {
        self.base().base().base().base().get_desc()
    }

    pub fn set_desc(&mut self, value: MultiLanguageOverviewParagraphId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_desc(value);
        self
    }

    pub fn get_introduction(&self) -> Option<DocumentationBlockId> {
        self.base().base().base().base().get_introduction()
    }

    pub fn set_introduction(&mut self, value: DocumentationBlockId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_introduction(value);
        self
    }

    pub fn get_uuid(&self) -> Option<&str> {
        self.base().base().base().base().get_uuid()
    }

    pub fn set_uuid(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_uuid(value);
        self
    }

    pub fn get_elements(&self) -> &[ElementRef] {
        self.base().base().base().base().get_elements()
    }

    pub fn push_element(&mut self, value: ElementRef) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .push_element(value)
    }

    pub fn get_long_name(&self) -> Option<MultilanguageLongNameId> {
        self.base().base().base().base().base().get_long_name()
    }

    pub fn set_long_name(&mut self, value: MultilanguageLongNameId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_long_name(value);
        self
    }

    pub fn get_short_name_fragments(&self) -> &[ShortNameFragmentId] {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_short_name_fragments()
    }

    pub fn push_short_name_fragment(&mut self, value: ShortNameFragmentId) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .push_short_name_fragment(value)
    }

    pub fn get_short_name(&self) -> Option<&str> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_short_name()
    }

    pub fn set_short_name(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_short_name(value);
        self
    }

    pub fn get_checksum(&self) -> Option<&str> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_checksum()
    }

    pub fn set_checksum(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_checksum(value);
        self
    }

    pub fn get_timestamp(&self) -> Option<&str> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_timestamp()
    }

    pub fn set_timestamp(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_timestamp(value);
        self
    }

    pub fn get_parent(&self) -> Option<ElementRef> {
        self.base().base().base().base().base().base().get_parent()
    }

    pub fn set_parent(&mut self, parent: Option<ElementRef>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_parent(parent);
        self
    }
}

/// spec class `LifeCyclePeriod`
/// This meta class represents the ability to specify a point of time within a specified period, e.g. the starting or end point, in which a specific life cycle state is valid/applies to.
#[derive(Debug, Default)]
pub struct LifeCyclePeriod {
    base: ARObject,
    ar_release_version: Option<String>,
    date: Option<String>,
    product_release: Option<String>,
}

impl LifeCyclePeriod {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn base(&self) -> &ARObject {
        &self.base
    }

    pub fn base_mut(&mut self) -> &mut ARObject {
        &mut self.base
    }

    pub fn get_ar_release_version(&self) -> Option<&str> {
        self.ar_release_version.as_deref()
    }

    pub fn set_ar_release_version(&mut self, value: impl Into<String>) -> &mut Self {
        self.ar_release_version = Some(value.into());
        self
    }

    pub fn get_date(&self) -> Option<&str> {
        self.date.as_deref()
    }

    pub fn set_date(&mut self, value: impl Into<String>) -> &mut Self {
        self.date = Some(value.into());
        self
    }

    pub fn get_product_release(&self) -> Option<&str> {
        self.product_release.as_deref()
    }

    pub fn set_product_release(&mut self, value: impl Into<String>) -> &mut Self {
        self.product_release = Some(value.into());
        self
    }

    pub fn get_checksum(&self) -> Option<&str> {
        self.base().get_checksum()
    }

    pub fn set_checksum(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_checksum(value);
        self
    }

    pub fn get_timestamp(&self) -> Option<&str> {
        self.base().get_timestamp()
    }

    pub fn set_timestamp(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_timestamp(value);
        self
    }
}

/// spec class `LifeCycleState`
/// This meta class represents one particular state in the LifeCycle.
#[derive(Debug, Default)]
pub struct LifeCycleState {
    base: AtpBlueprint,
}

impl LifeCycleState {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn base(&self) -> &AtpBlueprint {
        &self.base
    }

    pub fn base_mut(&mut self) -> &mut AtpBlueprint {
        &mut self.base
    }

    pub fn get_blueprint_policys(&self) -> &[ElementRef] {
        self.base().get_blueprint_policys()
    }

    pub fn push_blueprint_policy(&mut self, value: ElementRef) {
        self.base_mut().push_blueprint_policy(value)
    }

    pub fn get_admin_data(&self) -> Option<AdminDataId> {
        self.base().base().get_admin_data()
    }

    pub fn set_admin_data(&mut self, value: AdminDataId) -> &mut Self {
        self.base_mut().base_mut().set_admin_data(value);
        self
    }

    pub fn remove_admin_data(&mut self) -> &mut Self {
        self.base_mut().base_mut().remove_admin_data();
        self
    }

    pub fn get_annotations(&self) -> &[AnnotationId] {
        self.base().base().get_annotations()
    }

    pub fn push_annotation(&mut self, value: AnnotationId) {
        self.base_mut().base_mut().push_annotation(value)
    }

    pub fn get_category(&self) -> Option<&str> {
        self.base().base().get_category()
    }

    pub fn set_category(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().base_mut().set_category(value);
        self
    }

    pub fn get_desc(&self) -> Option<MultiLanguageOverviewParagraphId> {
        self.base().base().get_desc()
    }

    pub fn set_desc(&mut self, value: MultiLanguageOverviewParagraphId) -> &mut Self {
        self.base_mut().base_mut().set_desc(value);
        self
    }

    pub fn get_introduction(&self) -> Option<DocumentationBlockId> {
        self.base().base().get_introduction()
    }

    pub fn set_introduction(&mut self, value: DocumentationBlockId) -> &mut Self {
        self.base_mut().base_mut().set_introduction(value);
        self
    }

    pub fn get_uuid(&self) -> Option<&str> {
        self.base().base().get_uuid()
    }

    pub fn set_uuid(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().base_mut().set_uuid(value);
        self
    }

    pub fn get_elements(&self) -> &[ElementRef] {
        self.base().base().get_elements()
    }

    pub fn push_element(&mut self, value: ElementRef) {
        self.base_mut().base_mut().push_element(value)
    }

    pub fn get_long_name(&self) -> Option<MultilanguageLongNameId> {
        self.base().base().base().get_long_name()
    }

    pub fn set_long_name(&mut self, value: MultilanguageLongNameId) -> &mut Self {
        self.base_mut().base_mut().base_mut().set_long_name(value);
        self
    }

    pub fn get_short_name_fragments(&self) -> &[ShortNameFragmentId] {
        self.base().base().base().base().get_short_name_fragments()
    }

    pub fn push_short_name_fragment(&mut self, value: ShortNameFragmentId) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .push_short_name_fragment(value)
    }

    pub fn get_short_name(&self) -> Option<&str> {
        self.base().base().base().base().get_short_name()
    }

    pub fn set_short_name(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_short_name(value);
        self
    }

    pub fn get_checksum(&self) -> Option<&str> {
        self.base().base().base().base().base().get_checksum()
    }

    pub fn set_checksum(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_checksum(value);
        self
    }

    pub fn get_timestamp(&self) -> Option<&str> {
        self.base().base().base().base().base().get_timestamp()
    }

    pub fn set_timestamp(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_timestamp(value);
        self
    }

    pub fn get_parent(&self) -> Option<ElementRef> {
        self.base().base().base().base().get_parent()
    }

    pub fn set_parent(&mut self, parent: Option<ElementRef>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_parent(parent);
        self
    }
}

/// spec class `LifeCycleStateDefinitionGroup`
/// This meta class represents the ability to define the states and properties of one particular life cycle. Tags: atp.recommendedPackage=LifeCycleStateDefintionGroups
#[derive(Debug, Default)]
pub struct LifeCycleStateDefinitionGroup {
    base: ARElement,
    lc_states: Vec<LifeCycleStateId>,
}

impl LifeCycleStateDefinitionGroup {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn base(&self) -> &ARElement {
        &self.base
    }

    pub fn base_mut(&mut self) -> &mut ARElement {
        &mut self.base
    }

    pub fn get_lc_states(&self) -> &[LifeCycleStateId] {
        &self.lc_states
    }

    pub fn push_lc_state(&mut self, value: LifeCycleStateId) {
        self.lc_states.push(value);
    }

    pub fn get_admin_data(&self) -> Option<AdminDataId> {
        self.base().base().base().base().get_admin_data()
    }

    pub fn set_admin_data(&mut self, value: AdminDataId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_admin_data(value);
        self
    }

    pub fn remove_admin_data(&mut self) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .remove_admin_data();
        self
    }

    pub fn get_annotations(&self) -> &[AnnotationId] {
        self.base().base().base().base().get_annotations()
    }

    pub fn push_annotation(&mut self, value: AnnotationId) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .push_annotation(value)
    }

    pub fn get_category(&self) -> Option<&str> {
        self.base().base().base().base().get_category()
    }

    pub fn set_category(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_category(value);
        self
    }

    pub fn get_desc(&self) -> Option<MultiLanguageOverviewParagraphId> {
        self.base().base().base().base().get_desc()
    }

    pub fn set_desc(&mut self, value: MultiLanguageOverviewParagraphId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_desc(value);
        self
    }

    pub fn get_introduction(&self) -> Option<DocumentationBlockId> {
        self.base().base().base().base().get_introduction()
    }

    pub fn set_introduction(&mut self, value: DocumentationBlockId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_introduction(value);
        self
    }

    pub fn get_uuid(&self) -> Option<&str> {
        self.base().base().base().base().get_uuid()
    }

    pub fn set_uuid(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_uuid(value);
        self
    }

    pub fn get_elements(&self) -> &[ElementRef] {
        self.base().base().base().base().get_elements()
    }

    pub fn push_element(&mut self, value: ElementRef) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .push_element(value)
    }

    pub fn get_long_name(&self) -> Option<MultilanguageLongNameId> {
        self.base().base().base().base().base().get_long_name()
    }

    pub fn set_long_name(&mut self, value: MultilanguageLongNameId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_long_name(value);
        self
    }

    pub fn get_short_name_fragments(&self) -> &[ShortNameFragmentId] {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_short_name_fragments()
    }

    pub fn push_short_name_fragment(&mut self, value: ShortNameFragmentId) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .push_short_name_fragment(value)
    }

    pub fn get_short_name(&self) -> Option<&str> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_short_name()
    }

    pub fn set_short_name(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_short_name(value);
        self
    }

    pub fn get_checksum(&self) -> Option<&str> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_checksum()
    }

    pub fn set_checksum(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_checksum(value);
        self
    }

    pub fn get_timestamp(&self) -> Option<&str> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_timestamp()
    }

    pub fn set_timestamp(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_timestamp(value);
        self
    }

    pub fn get_parent(&self) -> Option<ElementRef> {
        self.base().base().base().base().base().base().get_parent()
    }

    pub fn set_parent(&mut self, parent: Option<ElementRef>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_parent(parent);
        self
    }
}

impl Document {
    pub(crate) fn compare_life_cycle_info(
        &self,
        _other: &Document,
        a: &LifeCycleInfo,
        b: &LifeCycleInfo,
        path: &str,
    ) -> Result<(), String> {
        Self::compare_ar_object(a.base(), b.base(), path)?;
        if a.get_lc_object_ref() != b.get_lc_object_ref() {
            return Err(format!("{path}: LC_OBJECT_REF mismatch"));
        }
        if a.get_lc_state_ref() != b.get_lc_state_ref() {
            return Err(format!("{path}: LC_STATE_REF mismatch"));
        }
        if a.get_period_begin() != b.get_period_begin() {
            return Err(format!("{path}: PERIOD_BEGIN mismatch"));
        }
        if a.get_period_end() != b.get_period_end() {
            return Err(format!("{path}: PERIOD_END mismatch"));
        }
        if a.get_remark() != b.get_remark() {
            return Err(format!("{path}: REMARK mismatch"));
        }
        let list_a = a.get_use_instead_refs();
        let list_b = b.get_use_instead_refs();
        if list_a.len() != list_b.len() {
            return Err(format!("{path}: USE_INSTEAD_REFS length mismatch"));
        }
        for (index, (x, y)) in list_a.iter().zip(list_b.iter()).enumerate() {
            if x != y {
                return Err(format!("{path}.USE_INSTEAD_REFS[{index}] mismatch"));
            }
        }
        Ok(())
    }

    pub(crate) fn compare_life_cycle_info_set(
        &self,
        other: &Document,
        a: &LifeCycleInfoSet,
        b: &LifeCycleInfoSet,
        path: &str,
    ) -> Result<(), String> {
        self.compare_ar_element(other, a.base(), b.base(), path)?;
        if a.get_default_lc_state_ref() != b.get_default_lc_state_ref() {
            return Err(format!("{path}: DEFAULT_LC_STATE_REF mismatch"));
        }
        if a.get_default_period_begin() != b.get_default_period_begin() {
            return Err(format!("{path}: DEFAULT_PERIOD_BEGIN mismatch"));
        }
        if a.get_default_period_end() != b.get_default_period_end() {
            return Err(format!("{path}: DEFAULT_PERIOD_END mismatch"));
        }
        let list_a = a.get_life_cycle_infos();
        let list_b = b.get_life_cycle_infos();
        if list_a.len() != list_b.len() {
            return Err(format!("{path}: LIFE_CYCLE_INFOS length mismatch"));
        }
        for (index, (x, y)) in list_a.iter().zip(list_b.iter()).enumerate() {
            let x = self.life_cycle_infos.get(*x).ok_or_else(|| {
                format!("{path}.LIFE_CYCLE_INFOS[{index}]: id not found in own arena")
            })?;
            let y = other.life_cycle_infos.get(*y).ok_or_else(|| {
                format!("{path}.LIFE_CYCLE_INFOS[{index}]: id not found in other arena")
            })?;
            self.compare_life_cycle_info(
                other,
                x,
                y,
                &format!("{path}.LIFE_CYCLE_INFOS[{index}]"),
            )?;
        }
        if a.get_used_life_cycle_state_definition_group_ref()
            != b.get_used_life_cycle_state_definition_group_ref()
        {
            return Err(format!(
                "{path}: USED_LIFE_CYCLE_STATE_DEFINITION_GROUP_REF mismatch"
            ));
        }
        Ok(())
    }

    pub(crate) fn compare_life_cycle_period(
        &self,
        _other: &Document,
        a: &LifeCyclePeriod,
        b: &LifeCyclePeriod,
        path: &str,
    ) -> Result<(), String> {
        Self::compare_ar_object(a.base(), b.base(), path)?;
        if a.get_ar_release_version() != b.get_ar_release_version() {
            return Err(format!("{path}: AR_RELEASE_VERSION mismatch"));
        }
        if a.get_date() != b.get_date() {
            return Err(format!("{path}: DATE mismatch"));
        }
        if a.get_product_release() != b.get_product_release() {
            return Err(format!("{path}: PRODUCT_RELEASE mismatch"));
        }
        Ok(())
    }

    pub(crate) fn compare_life_cycle_state(
        &self,
        other: &Document,
        a: &LifeCycleState,
        b: &LifeCycleState,
        path: &str,
    ) -> Result<(), String> {
        self.compare_atp_blueprint(other, a.base(), b.base(), path)?;
        Ok(())
    }

    pub(crate) fn compare_life_cycle_state_definition_group(
        &self,
        other: &Document,
        a: &LifeCycleStateDefinitionGroup,
        b: &LifeCycleStateDefinitionGroup,
        path: &str,
    ) -> Result<(), String> {
        self.compare_ar_element(other, a.base(), b.base(), path)?;
        let list_a = a.get_lc_states();
        let list_b = b.get_lc_states();
        if list_a.len() != list_b.len() {
            return Err(format!("{path}: LC_STATES length mismatch"));
        }
        for (index, (x, y)) in list_a.iter().zip(list_b.iter()).enumerate() {
            let x = self
                .life_cycle_states
                .get(*x)
                .ok_or_else(|| format!("{path}.LC_STATES[{index}]: id not found in own arena"))?;
            let y = other
                .life_cycle_states
                .get(*y)
                .ok_or_else(|| format!("{path}.LC_STATES[{index}]: id not found in other arena"))?;
            self.compare_life_cycle_state(other, x, y, &format!("{path}.LC_STATES[{index}]"))?;
        }
        Ok(())
    }
}
