// @generated by tools/py2rust from py-armodel models/M2 (see PY_ARMODEL_VERSION). Do not edit.

//! generated from spec package: m2::autosar_templates::generic_structure::view_map_set

use slotmap::new_key_type;

new_key_type! {
    pub struct ViewMapId;
    pub struct ViewMapSetId;
}

use crate::m2::autosar_templates::generic_structure::general_template_classes::any_instance_ref::AnyInstanceRefId;
use crate::m2::autosar_templates::generic_structure::general_template_classes::ar_object::ElementRef;
use crate::m2::autosar_templates::generic_structure::general_template_classes::identifiable::Identifiable;
use crate::m2::autosar_templates::generic_structure::general_template_classes::identifiable::ShortNameFragmentId;
use crate::m2::msr::asam_hdo::admin_data::AdminDataId;
use crate::m2::msr::documentation::annotation::AnnotationId;
use crate::m2::msr::documentation::text_model::block_elements::DocumentationBlockId;
use crate::m2::msr::documentation::text_model::multilanguage_data::MultiLanguageOverviewParagraphId;
use crate::m2::msr::documentation::text_model::multilanguage_data::MultilanguageLongNameId;
use crate::Document;

/// spec class `ViewMap`
/// The ViewMap allows to relate any number of elements on the "first" side to any number of elements on the "second" side. Since the ViewMap does not address a specific mapping use-case the roles "first" and "second" shall imply this generality. This mapping allows to trace transformations of artifacts within the AUTOSAR environment. The references to the mapped elements can be plain references and/or InstanceRefs.
#[derive(Debug, Default)]
pub struct ViewMap {
    base: Identifiable,
    first_element_refs: Vec<String>,
    first_element_i_refs: Vec<AnyInstanceRefId>,
    role: Option<String>,
    second_element_refs: Vec<String>,
    second_element_i_refs: Vec<AnyInstanceRefId>,
}

impl ViewMap {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn base(&self) -> &Identifiable {
        &self.base
    }

    pub fn base_mut(&mut self) -> &mut Identifiable {
        &mut self.base
    }

    pub fn get_first_element_refs(&self) -> &[String] {
        &self.first_element_refs
    }

    pub fn push_first_element_ref(&mut self, value: String) {
        self.first_element_refs.push(value);
    }

    pub fn get_first_element_i_refs(&self) -> &[AnyInstanceRefId] {
        &self.first_element_i_refs
    }

    pub fn push_first_element_i_ref(&mut self, value: AnyInstanceRefId) {
        self.first_element_i_refs.push(value);
    }

    pub fn get_role(&self) -> Option<&str> {
        self.role.as_deref()
    }

    pub fn set_role(&mut self, value: impl Into<String>) -> &mut Self {
        self.role = Some(value.into());
        self
    }

    pub fn get_second_element_refs(&self) -> &[String] {
        &self.second_element_refs
    }

    pub fn push_second_element_ref(&mut self, value: String) {
        self.second_element_refs.push(value);
    }

    pub fn get_second_element_i_refs(&self) -> &[AnyInstanceRefId] {
        &self.second_element_i_refs
    }

    pub fn push_second_element_i_ref(&mut self, value: AnyInstanceRefId) {
        self.second_element_i_refs.push(value);
    }

    pub fn get_admin_data(&self) -> Option<AdminDataId> {
        self.base().get_admin_data()
    }

    pub fn set_admin_data(&mut self, value: AdminDataId) -> &mut Self {
        self.base_mut().set_admin_data(value);
        self
    }

    pub fn remove_admin_data(&mut self) -> &mut Self {
        self.base_mut().remove_admin_data();
        self
    }

    pub fn get_annotations(&self) -> &[AnnotationId] {
        self.base().get_annotations()
    }

    pub fn push_annotation(&mut self, value: AnnotationId) {
        self.base_mut().push_annotation(value)
    }

    pub fn get_category(&self) -> Option<&str> {
        self.base().get_category()
    }

    pub fn set_category(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_category(value);
        self
    }

    pub fn get_desc(&self) -> Option<MultiLanguageOverviewParagraphId> {
        self.base().get_desc()
    }

    pub fn set_desc(&mut self, value: MultiLanguageOverviewParagraphId) -> &mut Self {
        self.base_mut().set_desc(value);
        self
    }

    pub fn get_introduction(&self) -> Option<DocumentationBlockId> {
        self.base().get_introduction()
    }

    pub fn set_introduction(&mut self, value: DocumentationBlockId) -> &mut Self {
        self.base_mut().set_introduction(value);
        self
    }

    pub fn get_uuid(&self) -> Option<&str> {
        self.base().get_uuid()
    }

    pub fn set_uuid(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_uuid(value);
        self
    }

    pub fn get_elements(&self) -> &[ElementRef] {
        self.base().get_elements()
    }

    pub fn push_element(&mut self, value: ElementRef) {
        self.base_mut().push_element(value)
    }

    pub fn get_long_name(&self) -> Option<MultilanguageLongNameId> {
        self.base().base().get_long_name()
    }

    pub fn set_long_name(&mut self, value: MultilanguageLongNameId) -> &mut Self {
        self.base_mut().base_mut().set_long_name(value);
        self
    }

    pub fn get_short_name_fragments(&self) -> &[ShortNameFragmentId] {
        self.base().base().base().get_short_name_fragments()
    }

    pub fn push_short_name_fragment(&mut self, value: ShortNameFragmentId) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .push_short_name_fragment(value)
    }

    pub fn get_short_name(&self) -> Option<&str> {
        self.base().base().base().get_short_name()
    }

    pub fn set_short_name(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().base_mut().base_mut().set_short_name(value);
        self
    }

    pub fn get_checksum(&self) -> Option<&str> {
        self.base().base().base().base().get_checksum()
    }

    pub fn set_checksum(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_checksum(value);
        self
    }

    pub fn get_timestamp(&self) -> Option<&str> {
        self.base().base().base().base().get_timestamp()
    }

    pub fn set_timestamp(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_timestamp(value);
        self
    }

    pub fn get_parent(&self) -> Option<ElementRef> {
        self.base().base().base().get_parent()
    }

    pub fn set_parent(&mut self, parent: Option<ElementRef>) -> &mut Self {
        self.base_mut().base_mut().base_mut().set_parent(parent);
        self
    }
}

/// spec class `ViewMapSet`
/// Collection of ViewMaps that are used to establish relationships between different AUTOSAR artifacts. Tags: atp.recommendedPackage=ViewMapSets
#[derive(Debug, Default)]
pub struct ViewMapSet {
    base: Identifiable,
    view_maps: Vec<ViewMapId>,
}

impl ViewMapSet {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn base(&self) -> &Identifiable {
        &self.base
    }

    pub fn base_mut(&mut self) -> &mut Identifiable {
        &mut self.base
    }

    pub fn get_view_maps(&self) -> &[ViewMapId] {
        &self.view_maps
    }

    pub fn push_view_map(&mut self, value: ViewMapId) {
        self.view_maps.push(value);
    }

    pub fn get_admin_data(&self) -> Option<AdminDataId> {
        self.base().get_admin_data()
    }

    pub fn set_admin_data(&mut self, value: AdminDataId) -> &mut Self {
        self.base_mut().set_admin_data(value);
        self
    }

    pub fn remove_admin_data(&mut self) -> &mut Self {
        self.base_mut().remove_admin_data();
        self
    }

    pub fn get_annotations(&self) -> &[AnnotationId] {
        self.base().get_annotations()
    }

    pub fn push_annotation(&mut self, value: AnnotationId) {
        self.base_mut().push_annotation(value)
    }

    pub fn get_category(&self) -> Option<&str> {
        self.base().get_category()
    }

    pub fn set_category(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_category(value);
        self
    }

    pub fn get_desc(&self) -> Option<MultiLanguageOverviewParagraphId> {
        self.base().get_desc()
    }

    pub fn set_desc(&mut self, value: MultiLanguageOverviewParagraphId) -> &mut Self {
        self.base_mut().set_desc(value);
        self
    }

    pub fn get_introduction(&self) -> Option<DocumentationBlockId> {
        self.base().get_introduction()
    }

    pub fn set_introduction(&mut self, value: DocumentationBlockId) -> &mut Self {
        self.base_mut().set_introduction(value);
        self
    }

    pub fn get_uuid(&self) -> Option<&str> {
        self.base().get_uuid()
    }

    pub fn set_uuid(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_uuid(value);
        self
    }

    pub fn get_elements(&self) -> &[ElementRef] {
        self.base().get_elements()
    }

    pub fn push_element(&mut self, value: ElementRef) {
        self.base_mut().push_element(value)
    }

    pub fn get_long_name(&self) -> Option<MultilanguageLongNameId> {
        self.base().base().get_long_name()
    }

    pub fn set_long_name(&mut self, value: MultilanguageLongNameId) -> &mut Self {
        self.base_mut().base_mut().set_long_name(value);
        self
    }

    pub fn get_short_name_fragments(&self) -> &[ShortNameFragmentId] {
        self.base().base().base().get_short_name_fragments()
    }

    pub fn push_short_name_fragment(&mut self, value: ShortNameFragmentId) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .push_short_name_fragment(value)
    }

    pub fn get_short_name(&self) -> Option<&str> {
        self.base().base().base().get_short_name()
    }

    pub fn set_short_name(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().base_mut().base_mut().set_short_name(value);
        self
    }

    pub fn get_checksum(&self) -> Option<&str> {
        self.base().base().base().base().get_checksum()
    }

    pub fn set_checksum(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_checksum(value);
        self
    }

    pub fn get_timestamp(&self) -> Option<&str> {
        self.base().base().base().base().get_timestamp()
    }

    pub fn set_timestamp(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_timestamp(value);
        self
    }

    pub fn get_parent(&self) -> Option<ElementRef> {
        self.base().base().base().get_parent()
    }

    pub fn set_parent(&mut self, parent: Option<ElementRef>) -> &mut Self {
        self.base_mut().base_mut().base_mut().set_parent(parent);
        self
    }
}

impl Document {
    pub(crate) fn compare_view_map(
        &self,
        other: &Document,
        a: &ViewMap,
        b: &ViewMap,
        path: &str,
    ) -> Result<(), String> {
        self.compare_identifiable(other, a.base(), b.base(), path)?;
        let list_a = a.get_first_element_refs();
        let list_b = b.get_first_element_refs();
        if list_a.len() != list_b.len() {
            return Err(format!("{path}: FIRST_ELEMENT_REFS length mismatch"));
        }
        for (index, (x, y)) in list_a.iter().zip(list_b.iter()).enumerate() {
            if x != y {
                return Err(format!("{path}.FIRST_ELEMENT_REFS[{index}] mismatch"));
            }
        }
        let list_a = a.get_first_element_i_refs();
        let list_b = b.get_first_element_i_refs();
        if list_a.len() != list_b.len() {
            return Err(format!("{path}: FIRST_ELEMENT_I_REFS length mismatch"));
        }
        for (index, (x, y)) in list_a.iter().zip(list_b.iter()).enumerate() {
            let x = self.any_instance_refs.get(*x).ok_or_else(|| {
                format!("{path}.FIRST_ELEMENT_I_REFS[{index}]: id not found in own arena")
            })?;
            let y = other.any_instance_refs.get(*y).ok_or_else(|| {
                format!("{path}.FIRST_ELEMENT_I_REFS[{index}]: id not found in other arena")
            })?;
            self.compare_any_instance_ref(
                other,
                x,
                y,
                &format!("{path}.FIRST_ELEMENT_I_REFS[{index}]"),
            )?;
        }
        if a.get_role() != b.get_role() {
            return Err(format!("{path}: ROLE mismatch"));
        }
        let list_a = a.get_second_element_refs();
        let list_b = b.get_second_element_refs();
        if list_a.len() != list_b.len() {
            return Err(format!("{path}: SECOND_ELEMENT_REFS length mismatch"));
        }
        for (index, (x, y)) in list_a.iter().zip(list_b.iter()).enumerate() {
            if x != y {
                return Err(format!("{path}.SECOND_ELEMENT_REFS[{index}] mismatch"));
            }
        }
        let list_a = a.get_second_element_i_refs();
        let list_b = b.get_second_element_i_refs();
        if list_a.len() != list_b.len() {
            return Err(format!("{path}: SECOND_ELEMENT_I_REFS length mismatch"));
        }
        for (index, (x, y)) in list_a.iter().zip(list_b.iter()).enumerate() {
            let x = self.any_instance_refs.get(*x).ok_or_else(|| {
                format!("{path}.SECOND_ELEMENT_I_REFS[{index}]: id not found in own arena")
            })?;
            let y = other.any_instance_refs.get(*y).ok_or_else(|| {
                format!("{path}.SECOND_ELEMENT_I_REFS[{index}]: id not found in other arena")
            })?;
            self.compare_any_instance_ref(
                other,
                x,
                y,
                &format!("{path}.SECOND_ELEMENT_I_REFS[{index}]"),
            )?;
        }
        Ok(())
    }

    pub(crate) fn compare_view_map_set(
        &self,
        other: &Document,
        a: &ViewMapSet,
        b: &ViewMapSet,
        path: &str,
    ) -> Result<(), String> {
        self.compare_identifiable(other, a.base(), b.base(), path)?;
        let list_a = a.get_view_maps();
        let list_b = b.get_view_maps();
        if list_a.len() != list_b.len() {
            return Err(format!("{path}: VIEW_MAPS length mismatch"));
        }
        for (index, (x, y)) in list_a.iter().zip(list_b.iter()).enumerate() {
            let x = self
                .view_maps
                .get(*x)
                .ok_or_else(|| format!("{path}.VIEW_MAPS[{index}]: id not found in own arena"))?;
            let y = other
                .view_maps
                .get(*y)
                .ok_or_else(|| format!("{path}.VIEW_MAPS[{index}]: id not found in other arena"))?;
            self.compare_view_map(other, x, y, &format!("{path}.VIEW_MAPS[{index}]"))?;
        }
        Ok(())
    }
}
