// @generated by tools/py2rust from py-armodel models/M2 (see PY_ARMODEL_VERSION). Do not edit.

//! generated from spec package: m2::autosar_templates::common_structure::standardization_template::blueprint_dedicated::port_interface_blueprint

use slotmap::new_key_type;

new_key_type! {
    pub struct PortInterfaceBlueprintMappingId;
}

use crate::m2::autosar_templates::common_structure::standardization_template::abstract_blueprint_structure::AtpBlueprintMapping;
use crate::Document;

/// spec class `PortInterfaceBlueprintMapping`
/// This meta-class represents the ability to map two PortInterfaces of which one acts as the blueprint for the other.
#[derive(Debug, Default)]
pub struct PortInterfaceBlueprintMapping {
    base: AtpBlueprintMapping,
    port_interface_blueprint_ref: Option<String>,
    derived_port_interface_ref: Option<String>,
}

impl PortInterfaceBlueprintMapping {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn base(&self) -> &AtpBlueprintMapping {
        &self.base
    }

    pub fn base_mut(&mut self) -> &mut AtpBlueprintMapping {
        &mut self.base
    }

    pub fn get_port_interface_blueprint_ref(&self) -> Option<&str> {
        self.port_interface_blueprint_ref.as_deref()
    }

    pub fn set_port_interface_blueprint_ref(&mut self, value: impl Into<String>) -> &mut Self {
        self.port_interface_blueprint_ref = Some(value.into());
        self
    }

    pub fn get_derived_port_interface_ref(&self) -> Option<&str> {
        self.derived_port_interface_ref.as_deref()
    }

    pub fn set_derived_port_interface_ref(&mut self, value: impl Into<String>) -> &mut Self {
        self.derived_port_interface_ref = Some(value.into());
        self
    }

    pub fn get_atp_blueprint_ref(&self) -> Option<&str> {
        self.base().get_atp_blueprint_ref()
    }

    pub fn set_atp_blueprint_ref(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_atp_blueprint_ref(value);
        self
    }

    pub fn get_atp_blueprinted_element_ref(&self) -> Option<&str> {
        self.base().get_atp_blueprinted_element_ref()
    }

    pub fn set_atp_blueprinted_element_ref(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_atp_blueprinted_element_ref(value);
        self
    }

    pub fn get_checksum(&self) -> Option<&str> {
        self.base().base().get_checksum()
    }

    pub fn set_checksum(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().base_mut().set_checksum(value);
        self
    }

    pub fn get_timestamp(&self) -> Option<&str> {
        self.base().base().get_timestamp()
    }

    pub fn set_timestamp(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().base_mut().set_timestamp(value);
        self
    }
}

impl Document {
    pub(crate) fn compare_port_interface_blueprint_mapping(
        &self,
        other: &Document,
        a: &PortInterfaceBlueprintMapping,
        b: &PortInterfaceBlueprintMapping,
        path: &str,
    ) -> Result<(), String> {
        self.compare_atp_blueprint_mapping(other, a.base(), b.base(), path)?;
        if a.get_port_interface_blueprint_ref() != b.get_port_interface_blueprint_ref() {
            return Err(format!("{path}: PORT_INTERFACE_BLUEPRINT_REF mismatch"));
        }
        if a.get_derived_port_interface_ref() != b.get_derived_port_interface_ref() {
            return Err(format!("{path}: DERIVED_PORT_INTERFACE_REF mismatch"));
        }
        Ok(())
    }
}
