// @generated by tools/py2rust from py-armodel models/M2 (see PY_ARMODEL_VERSION). Do not edit.

//! generated from spec package: m2::autosar_templates::common_structure::timing::timing_constraint::execution_order_constraint

use slotmap::new_key_type;

new_key_type! {
    pub struct EOCEventRefId;
    pub struct EOCExecutableEntityRefId;
    pub struct EOCExecutableEntityRefGroupId;
    pub struct ExecutionOrderConstraintId;
}

use crate::m2::autosar_templates::common_structure::timing::timing_constraint::TimingConstraint;
use crate::m2::autosar_templates::generic_structure::general_template_classes::ar_object::ElementRef;
use crate::m2::autosar_templates::generic_structure::general_template_classes::identifiable::Identifiable;
use crate::m2::autosar_templates::generic_structure::general_template_classes::identifiable::ShortNameFragmentId;
use crate::m2::autosar_templates::generic_structure::general_template_classes::primitive_types::RefTypeId;
use crate::m2::autosar_templates::sw_component_template::composition::instance_refs::ComponentInCompositionInstanceRefId;
use crate::m2::msr::asam_hdo::admin_data::AdminDataId;
use crate::m2::msr::documentation::annotation::AnnotationId;
use crate::m2::msr::documentation::text_model::block_elements::DocumentationBlockId;
use crate::m2::msr::documentation::text_model::multilanguage_data::MultiLanguageOverviewParagraphId;
use crate::m2::msr::documentation::text_model::multilanguage_data::MultilanguageLongNameId;
use crate::Document;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ExecutionOrderConstraintTypeEnum {
    HierarchicalEoc,
    OrdinaryEoc,
    RepetitiveEoc,
}

impl ExecutionOrderConstraintTypeEnum {
    pub fn as_str(&self) -> &'static str {
        match self {
            ExecutionOrderConstraintTypeEnum::HierarchicalEoc => "hierarchicalEOC",
            ExecutionOrderConstraintTypeEnum::OrdinaryEoc => "ordinaryEOC",
            ExecutionOrderConstraintTypeEnum::RepetitiveEoc => "repetitiveEOC",
        }
    }
}

impl TryFrom<&str> for ExecutionOrderConstraintTypeEnum {
    type Error = ();

    fn try_from(value: &str) -> Result<Self, ()> {
        match value {
            "hierarchicalEOC" => Ok(ExecutionOrderConstraintTypeEnum::HierarchicalEoc),
            "ordinaryEOC" => Ok(ExecutionOrderConstraintTypeEnum::OrdinaryEoc),
            "repetitiveEOC" => Ok(ExecutionOrderConstraintTypeEnum::RepetitiveEoc),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LetDataExchangeParadigmEnum {
    InterLetOnly,
    IntraLetEoc,
}

impl LetDataExchangeParadigmEnum {
    pub fn as_str(&self) -> &'static str {
        match self {
            LetDataExchangeParadigmEnum::InterLetOnly => "interLetOnly",
            LetDataExchangeParadigmEnum::IntraLetEoc => "intraLetEOC",
        }
    }
}

impl TryFrom<&str> for LetDataExchangeParadigmEnum {
    type Error = ();

    fn try_from(value: &str) -> Result<Self, ()> {
        match value {
            "interLetOnly" => Ok(LetDataExchangeParadigmEnum::InterLetOnly),
            "intraLetEOC" => Ok(LetDataExchangeParadigmEnum::IntraLetEoc),
            _ => Err(()),
        }
    }
}

/// spec class `EOCEventRef`
/// This is used to define a reference to an RTE or BSW Event.
#[derive(Debug, Default)]
pub struct EOCEventRef {
    base: EOCExecutableEntityRefAbstract,
    bsw_module_instance_ref: Option<RefTypeId>,
    component_i_ref: Option<ComponentInCompositionInstanceRefId>,
    event_ref: Option<RefTypeId>,
    successor_refs: Vec<RefTypeId>,
}

impl EOCEventRef {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn base(&self) -> &EOCExecutableEntityRefAbstract {
        &self.base
    }

    pub fn base_mut(&mut self) -> &mut EOCExecutableEntityRefAbstract {
        &mut self.base
    }

    pub fn get_bsw_module_instance_ref(&self) -> Option<RefTypeId> {
        self.bsw_module_instance_ref
    }

    pub fn set_bsw_module_instance_ref(&mut self, value: RefTypeId) -> &mut Self {
        self.bsw_module_instance_ref = Some(value);
        self
    }

    pub fn get_component_i_ref(&self) -> Option<ComponentInCompositionInstanceRefId> {
        self.component_i_ref
    }

    pub fn set_component_i_ref(&mut self, value: ComponentInCompositionInstanceRefId) -> &mut Self {
        self.component_i_ref = Some(value);
        self
    }

    pub fn get_event_ref(&self) -> Option<RefTypeId> {
        self.event_ref
    }

    pub fn set_event_ref(&mut self, value: RefTypeId) -> &mut Self {
        self.event_ref = Some(value);
        self
    }

    pub fn get_successor_refs(&self) -> &[RefTypeId] {
        &self.successor_refs
    }

    pub fn push_successor_ref(&mut self, value: RefTypeId) {
        self.successor_refs.push(value);
    }

    pub fn get_direct_successor_refs(&self) -> &[RefTypeId] {
        self.base().get_direct_successor_refs()
    }

    pub fn push_direct_successor_ref(&mut self, value: RefTypeId) {
        self.base_mut().push_direct_successor_ref(value)
    }

    pub fn get_admin_data(&self) -> Option<AdminDataId> {
        self.base().base().get_admin_data()
    }

    pub fn set_admin_data(&mut self, value: AdminDataId) -> &mut Self {
        self.base_mut().base_mut().set_admin_data(value);
        self
    }

    pub fn remove_admin_data(&mut self) -> &mut Self {
        self.base_mut().base_mut().remove_admin_data();
        self
    }

    pub fn get_annotations(&self) -> &[AnnotationId] {
        self.base().base().get_annotations()
    }

    pub fn push_annotation(&mut self, value: AnnotationId) {
        self.base_mut().base_mut().push_annotation(value)
    }

    pub fn get_category(&self) -> Option<&str> {
        self.base().base().get_category()
    }

    pub fn set_category(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().base_mut().set_category(value);
        self
    }

    pub fn get_desc(&self) -> Option<MultiLanguageOverviewParagraphId> {
        self.base().base().get_desc()
    }

    pub fn set_desc(&mut self, value: MultiLanguageOverviewParagraphId) -> &mut Self {
        self.base_mut().base_mut().set_desc(value);
        self
    }

    pub fn get_introduction(&self) -> Option<DocumentationBlockId> {
        self.base().base().get_introduction()
    }

    pub fn set_introduction(&mut self, value: DocumentationBlockId) -> &mut Self {
        self.base_mut().base_mut().set_introduction(value);
        self
    }

    pub fn get_uuid(&self) -> Option<&str> {
        self.base().base().get_uuid()
    }

    pub fn set_uuid(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().base_mut().set_uuid(value);
        self
    }

    pub fn get_elements(&self) -> &[ElementRef] {
        self.base().base().get_elements()
    }

    pub fn push_element(&mut self, value: ElementRef) {
        self.base_mut().base_mut().push_element(value)
    }

    pub fn get_long_name(&self) -> Option<MultilanguageLongNameId> {
        self.base().base().base().get_long_name()
    }

    pub fn set_long_name(&mut self, value: MultilanguageLongNameId) -> &mut Self {
        self.base_mut().base_mut().base_mut().set_long_name(value);
        self
    }

    pub fn get_short_name_fragments(&self) -> &[ShortNameFragmentId] {
        self.base().base().base().base().get_short_name_fragments()
    }

    pub fn push_short_name_fragment(&mut self, value: ShortNameFragmentId) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .push_short_name_fragment(value)
    }

    pub fn get_short_name(&self) -> Option<&str> {
        self.base().base().base().base().get_short_name()
    }

    pub fn set_short_name(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_short_name(value);
        self
    }

    pub fn get_checksum(&self) -> Option<&str> {
        self.base().base().base().base().base().get_checksum()
    }

    pub fn set_checksum(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_checksum(value);
        self
    }

    pub fn get_timestamp(&self) -> Option<&str> {
        self.base().base().base().base().base().get_timestamp()
    }

    pub fn set_timestamp(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_timestamp(value);
        self
    }

    pub fn get_parent(&self) -> Option<ElementRef> {
        self.base().base().base().base().get_parent()
    }

    pub fn set_parent(&mut self, parent: Option<ElementRef>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_parent(parent);
        self
    }
}

/// spec class `EOCExecutableEntityRef`
/// This is used to define a reference to an ExecutableEntity. If the ExecutionOrderConstraint is defined on VFB, System or ECU level, a reference to the SwComponentPrototype, via the ComponentInCompositionInstanceRef, the referenced ExecutableEntity belongs to, shall be provided as context information.
#[derive(Debug, Default)]
pub struct EOCExecutableEntityRef {
    base: EOCExecutableEntityRefAbstract,
    bsw_module_instance_ref: Option<RefTypeId>,
    component_i_ref: Option<ComponentInCompositionInstanceRefId>,
    executable_ref: Option<RefTypeId>,
    successor_refs: Vec<RefTypeId>,
}

impl EOCExecutableEntityRef {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn base(&self) -> &EOCExecutableEntityRefAbstract {
        &self.base
    }

    pub fn base_mut(&mut self) -> &mut EOCExecutableEntityRefAbstract {
        &mut self.base
    }

    pub fn get_bsw_module_instance_ref(&self) -> Option<RefTypeId> {
        self.bsw_module_instance_ref
    }

    pub fn set_bsw_module_instance_ref(&mut self, value: RefTypeId) -> &mut Self {
        self.bsw_module_instance_ref = Some(value);
        self
    }

    pub fn get_component_i_ref(&self) -> Option<ComponentInCompositionInstanceRefId> {
        self.component_i_ref
    }

    pub fn set_component_i_ref(&mut self, value: ComponentInCompositionInstanceRefId) -> &mut Self {
        self.component_i_ref = Some(value);
        self
    }

    pub fn get_executable_ref(&self) -> Option<RefTypeId> {
        self.executable_ref
    }

    pub fn set_executable_ref(&mut self, value: RefTypeId) -> &mut Self {
        self.executable_ref = Some(value);
        self
    }

    pub fn get_successor_refs(&self) -> &[RefTypeId] {
        &self.successor_refs
    }

    pub fn push_successor_ref(&mut self, value: RefTypeId) {
        self.successor_refs.push(value);
    }

    pub fn get_direct_successor_refs(&self) -> &[RefTypeId] {
        self.base().get_direct_successor_refs()
    }

    pub fn push_direct_successor_ref(&mut self, value: RefTypeId) {
        self.base_mut().push_direct_successor_ref(value)
    }

    pub fn get_admin_data(&self) -> Option<AdminDataId> {
        self.base().base().get_admin_data()
    }

    pub fn set_admin_data(&mut self, value: AdminDataId) -> &mut Self {
        self.base_mut().base_mut().set_admin_data(value);
        self
    }

    pub fn remove_admin_data(&mut self) -> &mut Self {
        self.base_mut().base_mut().remove_admin_data();
        self
    }

    pub fn get_annotations(&self) -> &[AnnotationId] {
        self.base().base().get_annotations()
    }

    pub fn push_annotation(&mut self, value: AnnotationId) {
        self.base_mut().base_mut().push_annotation(value)
    }

    pub fn get_category(&self) -> Option<&str> {
        self.base().base().get_category()
    }

    pub fn set_category(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().base_mut().set_category(value);
        self
    }

    pub fn get_desc(&self) -> Option<MultiLanguageOverviewParagraphId> {
        self.base().base().get_desc()
    }

    pub fn set_desc(&mut self, value: MultiLanguageOverviewParagraphId) -> &mut Self {
        self.base_mut().base_mut().set_desc(value);
        self
    }

    pub fn get_introduction(&self) -> Option<DocumentationBlockId> {
        self.base().base().get_introduction()
    }

    pub fn set_introduction(&mut self, value: DocumentationBlockId) -> &mut Self {
        self.base_mut().base_mut().set_introduction(value);
        self
    }

    pub fn get_uuid(&self) -> Option<&str> {
        self.base().base().get_uuid()
    }

    pub fn set_uuid(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().base_mut().set_uuid(value);
        self
    }

    pub fn get_elements(&self) -> &[ElementRef] {
        self.base().base().get_elements()
    }

    pub fn push_element(&mut self, value: ElementRef) {
        self.base_mut().base_mut().push_element(value)
    }

    pub fn get_long_name(&self) -> Option<MultilanguageLongNameId> {
        self.base().base().base().get_long_name()
    }

    pub fn set_long_name(&mut self, value: MultilanguageLongNameId) -> &mut Self {
        self.base_mut().base_mut().base_mut().set_long_name(value);
        self
    }

    pub fn get_short_name_fragments(&self) -> &[ShortNameFragmentId] {
        self.base().base().base().base().get_short_name_fragments()
    }

    pub fn push_short_name_fragment(&mut self, value: ShortNameFragmentId) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .push_short_name_fragment(value)
    }

    pub fn get_short_name(&self) -> Option<&str> {
        self.base().base().base().base().get_short_name()
    }

    pub fn set_short_name(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_short_name(value);
        self
    }

    pub fn get_checksum(&self) -> Option<&str> {
        self.base().base().base().base().base().get_checksum()
    }

    pub fn set_checksum(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_checksum(value);
        self
    }

    pub fn get_timestamp(&self) -> Option<&str> {
        self.base().base().base().base().base().get_timestamp()
    }

    pub fn set_timestamp(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_timestamp(value);
        self
    }

    pub fn get_parent(&self) -> Option<ElementRef> {
        self.base().base().base().base().get_parent()
    }

    pub fn set_parent(&mut self, parent: Option<ElementRef>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_parent(parent);
        self
    }
}

/// spec class `EOCExecutableEntityRefAbstract` (abstract)
/// This is the abstractions for Execution Order Constraint Executable Entity References (leaves) and Execution Order Constraint Executable Entity Reference Groups (composites).
#[derive(Debug, Default)]
pub struct EOCExecutableEntityRefAbstract {
    base: Identifiable,
    direct_successor_refs: Vec<RefTypeId>,
}

impl EOCExecutableEntityRefAbstract {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn base(&self) -> &Identifiable {
        &self.base
    }

    pub fn base_mut(&mut self) -> &mut Identifiable {
        &mut self.base
    }

    pub fn get_direct_successor_refs(&self) -> &[RefTypeId] {
        &self.direct_successor_refs
    }

    pub fn push_direct_successor_ref(&mut self, value: RefTypeId) {
        self.direct_successor_refs.push(value);
    }

    pub fn get_admin_data(&self) -> Option<AdminDataId> {
        self.base().get_admin_data()
    }

    pub fn set_admin_data(&mut self, value: AdminDataId) -> &mut Self {
        self.base_mut().set_admin_data(value);
        self
    }

    pub fn remove_admin_data(&mut self) -> &mut Self {
        self.base_mut().remove_admin_data();
        self
    }

    pub fn get_annotations(&self) -> &[AnnotationId] {
        self.base().get_annotations()
    }

    pub fn push_annotation(&mut self, value: AnnotationId) {
        self.base_mut().push_annotation(value)
    }

    pub fn get_category(&self) -> Option<&str> {
        self.base().get_category()
    }

    pub fn set_category(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_category(value);
        self
    }

    pub fn get_desc(&self) -> Option<MultiLanguageOverviewParagraphId> {
        self.base().get_desc()
    }

    pub fn set_desc(&mut self, value: MultiLanguageOverviewParagraphId) -> &mut Self {
        self.base_mut().set_desc(value);
        self
    }

    pub fn get_introduction(&self) -> Option<DocumentationBlockId> {
        self.base().get_introduction()
    }

    pub fn set_introduction(&mut self, value: DocumentationBlockId) -> &mut Self {
        self.base_mut().set_introduction(value);
        self
    }

    pub fn get_uuid(&self) -> Option<&str> {
        self.base().get_uuid()
    }

    pub fn set_uuid(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_uuid(value);
        self
    }

    pub fn get_elements(&self) -> &[ElementRef] {
        self.base().get_elements()
    }

    pub fn push_element(&mut self, value: ElementRef) {
        self.base_mut().push_element(value)
    }

    pub fn get_long_name(&self) -> Option<MultilanguageLongNameId> {
        self.base().base().get_long_name()
    }

    pub fn set_long_name(&mut self, value: MultilanguageLongNameId) -> &mut Self {
        self.base_mut().base_mut().set_long_name(value);
        self
    }

    pub fn get_short_name_fragments(&self) -> &[ShortNameFragmentId] {
        self.base().base().base().get_short_name_fragments()
    }

    pub fn push_short_name_fragment(&mut self, value: ShortNameFragmentId) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .push_short_name_fragment(value)
    }

    pub fn get_short_name(&self) -> Option<&str> {
        self.base().base().base().get_short_name()
    }

    pub fn set_short_name(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().base_mut().base_mut().set_short_name(value);
        self
    }

    pub fn get_checksum(&self) -> Option<&str> {
        self.base().base().base().base().get_checksum()
    }

    pub fn set_checksum(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_checksum(value);
        self
    }

    pub fn get_timestamp(&self) -> Option<&str> {
        self.base().base().base().base().get_timestamp()
    }

    pub fn set_timestamp(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_timestamp(value);
        self
    }

    pub fn get_parent(&self) -> Option<ElementRef> {
        self.base().base().base().get_parent()
    }

    pub fn set_parent(&mut self, parent: Option<ElementRef>) -> &mut Self {
        self.base_mut().base_mut().base_mut().set_parent(parent);
        self
    }
}

/// spec class `EOCExecutableEntityRefGroup`
/// This is used to specify a group (composite) consisting of Execution Order Constraint Executable Entity References (leaves) and/or further Execution Order Constraint Executable Entity Reference Groups (composite).
#[derive(Debug, Default)]
pub struct EOCExecutableEntityRefGroup {
    base: EOCExecutableEntityRefAbstract,
    let_data_exchange_paradigm: Option<LetDataExchangeParadigmEnum>,
    let_interval_refs: Vec<RefTypeId>,
    max_cycle_repetitions: Option<String>,
    max_cycles: Option<String>,
    max_slots: Option<String>,
    max_slots_per_cycle: Option<String>,
    nested_element_refs: Vec<RefTypeId>,
    successor_refs: Vec<RefTypeId>,
    triggering_event_ref: Option<RefTypeId>,
}

impl EOCExecutableEntityRefGroup {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn base(&self) -> &EOCExecutableEntityRefAbstract {
        &self.base
    }

    pub fn base_mut(&mut self) -> &mut EOCExecutableEntityRefAbstract {
        &mut self.base
    }

    pub fn get_let_data_exchange_paradigm(&self) -> Option<LetDataExchangeParadigmEnum> {
        self.let_data_exchange_paradigm
    }

    pub fn set_let_data_exchange_paradigm(
        &mut self,
        value: LetDataExchangeParadigmEnum,
    ) -> &mut Self {
        self.let_data_exchange_paradigm = Some(value);
        self
    }

    pub fn get_let_interval_refs(&self) -> &[RefTypeId] {
        &self.let_interval_refs
    }

    pub fn push_let_interval_ref(&mut self, value: RefTypeId) {
        self.let_interval_refs.push(value);
    }

    pub fn get_max_cycle_repetitions(&self) -> Option<&str> {
        self.max_cycle_repetitions.as_deref()
    }

    pub fn set_max_cycle_repetitions(&mut self, value: impl Into<String>) -> &mut Self {
        self.max_cycle_repetitions = Some(value.into());
        self
    }

    pub fn get_max_cycles(&self) -> Option<&str> {
        self.max_cycles.as_deref()
    }

    pub fn set_max_cycles(&mut self, value: impl Into<String>) -> &mut Self {
        self.max_cycles = Some(value.into());
        self
    }

    pub fn get_max_slots(&self) -> Option<&str> {
        self.max_slots.as_deref()
    }

    pub fn set_max_slots(&mut self, value: impl Into<String>) -> &mut Self {
        self.max_slots = Some(value.into());
        self
    }

    pub fn get_max_slots_per_cycle(&self) -> Option<&str> {
        self.max_slots_per_cycle.as_deref()
    }

    pub fn set_max_slots_per_cycle(&mut self, value: impl Into<String>) -> &mut Self {
        self.max_slots_per_cycle = Some(value.into());
        self
    }

    pub fn get_nested_element_refs(&self) -> &[RefTypeId] {
        &self.nested_element_refs
    }

    pub fn push_nested_element_ref(&mut self, value: RefTypeId) {
        self.nested_element_refs.push(value);
    }

    pub fn get_successor_refs(&self) -> &[RefTypeId] {
        &self.successor_refs
    }

    pub fn push_successor_ref(&mut self, value: RefTypeId) {
        self.successor_refs.push(value);
    }

    pub fn get_triggering_event_ref(&self) -> Option<RefTypeId> {
        self.triggering_event_ref
    }

    pub fn set_triggering_event_ref(&mut self, value: RefTypeId) -> &mut Self {
        self.triggering_event_ref = Some(value);
        self
    }

    pub fn get_direct_successor_refs(&self) -> &[RefTypeId] {
        self.base().get_direct_successor_refs()
    }

    pub fn push_direct_successor_ref(&mut self, value: RefTypeId) {
        self.base_mut().push_direct_successor_ref(value)
    }

    pub fn get_admin_data(&self) -> Option<AdminDataId> {
        self.base().base().get_admin_data()
    }

    pub fn set_admin_data(&mut self, value: AdminDataId) -> &mut Self {
        self.base_mut().base_mut().set_admin_data(value);
        self
    }

    pub fn remove_admin_data(&mut self) -> &mut Self {
        self.base_mut().base_mut().remove_admin_data();
        self
    }

    pub fn get_annotations(&self) -> &[AnnotationId] {
        self.base().base().get_annotations()
    }

    pub fn push_annotation(&mut self, value: AnnotationId) {
        self.base_mut().base_mut().push_annotation(value)
    }

    pub fn get_category(&self) -> Option<&str> {
        self.base().base().get_category()
    }

    pub fn set_category(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().base_mut().set_category(value);
        self
    }

    pub fn get_desc(&self) -> Option<MultiLanguageOverviewParagraphId> {
        self.base().base().get_desc()
    }

    pub fn set_desc(&mut self, value: MultiLanguageOverviewParagraphId) -> &mut Self {
        self.base_mut().base_mut().set_desc(value);
        self
    }

    pub fn get_introduction(&self) -> Option<DocumentationBlockId> {
        self.base().base().get_introduction()
    }

    pub fn set_introduction(&mut self, value: DocumentationBlockId) -> &mut Self {
        self.base_mut().base_mut().set_introduction(value);
        self
    }

    pub fn get_uuid(&self) -> Option<&str> {
        self.base().base().get_uuid()
    }

    pub fn set_uuid(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().base_mut().set_uuid(value);
        self
    }

    pub fn get_elements(&self) -> &[ElementRef] {
        self.base().base().get_elements()
    }

    pub fn push_element(&mut self, value: ElementRef) {
        self.base_mut().base_mut().push_element(value)
    }

    pub fn get_long_name(&self) -> Option<MultilanguageLongNameId> {
        self.base().base().base().get_long_name()
    }

    pub fn set_long_name(&mut self, value: MultilanguageLongNameId) -> &mut Self {
        self.base_mut().base_mut().base_mut().set_long_name(value);
        self
    }

    pub fn get_short_name_fragments(&self) -> &[ShortNameFragmentId] {
        self.base().base().base().base().get_short_name_fragments()
    }

    pub fn push_short_name_fragment(&mut self, value: ShortNameFragmentId) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .push_short_name_fragment(value)
    }

    pub fn get_short_name(&self) -> Option<&str> {
        self.base().base().base().base().get_short_name()
    }

    pub fn set_short_name(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_short_name(value);
        self
    }

    pub fn get_checksum(&self) -> Option<&str> {
        self.base().base().base().base().base().get_checksum()
    }

    pub fn set_checksum(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_checksum(value);
        self
    }

    pub fn get_timestamp(&self) -> Option<&str> {
        self.base().base().base().base().base().get_timestamp()
    }

    pub fn set_timestamp(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_timestamp(value);
        self
    }

    pub fn get_parent(&self) -> Option<ElementRef> {
        self.base().base().base().base().get_parent()
    }

    pub fn set_parent(&mut self, parent: Option<ElementRef>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_parent(parent);
        self
    }
}

/// spec class `ExecutionOrderConstraint`
/// This constraint is used to restrict the order of execution for a set of ExecutableEntity s. The ExecutionOrderConstraint can be used in any timing view. The various scopes for ExecutionOrderConstraint are described below. Generally, each ExecutionOrder Constraint has a scope of software components and can reference all ExecutableEntity s available in the corresponding internal behavior (RunnableEntity and BswModuleEntity) either directly or by the events activating respectively starting them (RteEvent and BswEvent). On VFB level an ExecutionOrderConstraint can be specified for RunnableEntities part of the composition hierarchy referenced by the VfbTiming. On SW-C level an ExecutionOrderConstraint can be specified for RunnableEntities part of the Internal Behavior referenced by the SwcTiming. On System level an ExecutionOrderConstraint can be specified for RunnableEntities part of the composition hierarchy of the system referenced by the SystemTiming. On BSW Module level, an ExectionOrderConstraint can be specified for BswModuleEntities part of an BswInternalBehavior referenced by the BswModuleTiming. On ECU level an ExecutionOrderConstraint can be specified for all ExecutableEntity s and Events available via the EcucValueCollection, covering ECU Extract and BSW Module Configuration, referenced by the EcuTiming.
#[derive(Debug, Default)]
pub struct ExecutionOrderConstraint {
    base: TimingConstraint,
    base_composition_ref: Option<RefTypeId>,
    execution_order_constraint_type: Option<ExecutionOrderConstraintTypeEnum>,
    ignore_order_allowed: Option<String>,
    is_event: Option<String>,
    ordered_elements: Vec<ElementRef>,
    permit_multiple_references_to_ee: Option<String>,
}

impl ExecutionOrderConstraint {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn base(&self) -> &TimingConstraint {
        &self.base
    }

    pub fn base_mut(&mut self) -> &mut TimingConstraint {
        &mut self.base
    }

    pub fn get_base_composition_ref(&self) -> Option<RefTypeId> {
        self.base_composition_ref
    }

    pub fn set_base_composition_ref(&mut self, value: RefTypeId) -> &mut Self {
        self.base_composition_ref = Some(value);
        self
    }

    pub fn get_execution_order_constraint_type(&self) -> Option<ExecutionOrderConstraintTypeEnum> {
        self.execution_order_constraint_type
    }

    pub fn set_execution_order_constraint_type(
        &mut self,
        value: ExecutionOrderConstraintTypeEnum,
    ) -> &mut Self {
        self.execution_order_constraint_type = Some(value);
        self
    }

    pub fn get_ignore_order_allowed(&self) -> Option<&str> {
        self.ignore_order_allowed.as_deref()
    }

    pub fn set_ignore_order_allowed(&mut self, value: impl Into<String>) -> &mut Self {
        self.ignore_order_allowed = Some(value.into());
        self
    }

    pub fn get_is_event(&self) -> Option<&str> {
        self.is_event.as_deref()
    }

    pub fn set_is_event(&mut self, value: impl Into<String>) -> &mut Self {
        self.is_event = Some(value.into());
        self
    }

    pub fn get_ordered_elements(&self) -> &[ElementRef] {
        &self.ordered_elements
    }

    pub fn push_ordered_element(&mut self, value: ElementRef) {
        self.ordered_elements.push(value);
    }

    pub fn get_permit_multiple_references_to_ee(&self) -> Option<&str> {
        self.permit_multiple_references_to_ee.as_deref()
    }

    pub fn set_permit_multiple_references_to_ee(&mut self, value: impl Into<String>) -> &mut Self {
        self.permit_multiple_references_to_ee = Some(value.into());
        self
    }

    pub fn get_timing_condition_ref(&self) -> Option<RefTypeId> {
        self.base().get_timing_condition_ref()
    }

    pub fn set_timing_condition_ref(&mut self, value: RefTypeId) -> &mut Self {
        self.base_mut().set_timing_condition_ref(value);
        self
    }

    pub fn get_trace_refs(&self) -> &[RefTypeId] {
        self.base().base().get_trace_refs()
    }

    pub fn push_trace_ref(&mut self, value: RefTypeId) {
        self.base_mut().base_mut().push_trace_ref(value)
    }

    pub fn get_admin_data(&self) -> Option<AdminDataId> {
        self.base().base().base().get_admin_data()
    }

    pub fn set_admin_data(&mut self, value: AdminDataId) -> &mut Self {
        self.base_mut().base_mut().base_mut().set_admin_data(value);
        self
    }

    pub fn remove_admin_data(&mut self) -> &mut Self {
        self.base_mut().base_mut().base_mut().remove_admin_data();
        self
    }

    pub fn get_annotations(&self) -> &[AnnotationId] {
        self.base().base().base().get_annotations()
    }

    pub fn push_annotation(&mut self, value: AnnotationId) {
        self.base_mut().base_mut().base_mut().push_annotation(value)
    }

    pub fn get_category(&self) -> Option<&str> {
        self.base().base().base().get_category()
    }

    pub fn set_category(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().base_mut().base_mut().set_category(value);
        self
    }

    pub fn get_desc(&self) -> Option<MultiLanguageOverviewParagraphId> {
        self.base().base().base().get_desc()
    }

    pub fn set_desc(&mut self, value: MultiLanguageOverviewParagraphId) -> &mut Self {
        self.base_mut().base_mut().base_mut().set_desc(value);
        self
    }

    pub fn get_introduction(&self) -> Option<DocumentationBlockId> {
        self.base().base().base().get_introduction()
    }

    pub fn set_introduction(&mut self, value: DocumentationBlockId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .set_introduction(value);
        self
    }

    pub fn get_uuid(&self) -> Option<&str> {
        self.base().base().base().get_uuid()
    }

    pub fn set_uuid(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().base_mut().base_mut().set_uuid(value);
        self
    }

    pub fn get_elements(&self) -> &[ElementRef] {
        self.base().base().base().get_elements()
    }

    pub fn push_element(&mut self, value: ElementRef) {
        self.base_mut().base_mut().base_mut().push_element(value)
    }

    pub fn get_long_name(&self) -> Option<MultilanguageLongNameId> {
        self.base().base().base().base().get_long_name()
    }

    pub fn set_long_name(&mut self, value: MultilanguageLongNameId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_long_name(value);
        self
    }

    pub fn get_short_name_fragments(&self) -> &[ShortNameFragmentId] {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .get_short_name_fragments()
    }

    pub fn push_short_name_fragment(&mut self, value: ShortNameFragmentId) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .push_short_name_fragment(value)
    }

    pub fn get_short_name(&self) -> Option<&str> {
        self.base().base().base().base().base().get_short_name()
    }

    pub fn set_short_name(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_short_name(value);
        self
    }

    pub fn get_checksum(&self) -> Option<&str> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_checksum()
    }

    pub fn set_checksum(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_checksum(value);
        self
    }

    pub fn get_timestamp(&self) -> Option<&str> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_timestamp()
    }

    pub fn set_timestamp(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_timestamp(value);
        self
    }

    pub fn get_parent(&self) -> Option<ElementRef> {
        self.base().base().base().base().base().get_parent()
    }

    pub fn set_parent(&mut self, parent: Option<ElementRef>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_parent(parent);
        self
    }
}

impl Document {
    pub(crate) fn compare_eoc_event_ref(
        &self,
        other: &Document,
        a: &EOCEventRef,
        b: &EOCEventRef,
        path: &str,
    ) -> Result<(), String> {
        self.compare_eoc_executable_entity_ref_abstract(other, a.base(), b.base(), path)?;
        if a.get_bsw_module_instance_ref() != b.get_bsw_module_instance_ref() {
            return Err(format!("{path}: BSW_MODULE_INSTANCE_REF mismatch"));
        }
        if a.get_component_i_ref() != b.get_component_i_ref() {
            return Err(format!("{path}: COMPONENT_I_REF mismatch"));
        }
        if a.get_event_ref() != b.get_event_ref() {
            return Err(format!("{path}: EVENT_REF mismatch"));
        }
        let list_a = a.get_successor_refs();
        let list_b = b.get_successor_refs();
        if list_a.len() != list_b.len() {
            return Err(format!("{path}: SUCCESSOR_REFS length mismatch"));
        }
        for (index, (x, y)) in list_a.iter().zip(list_b.iter()).enumerate() {
            let x = self.ref_types.get(*x).ok_or_else(|| {
                format!("{path}.SUCCESSOR_REFS[{index}]: id not found in own arena")
            })?;
            let y = other.ref_types.get(*y).ok_or_else(|| {
                format!("{path}.SUCCESSOR_REFS[{index}]: id not found in other arena")
            })?;
            self.compare_ref_type(other, x, y, &format!("{path}.SUCCESSOR_REFS[{index}]"))?;
        }
        Ok(())
    }

    pub(crate) fn compare_eoc_executable_entity_ref(
        &self,
        other: &Document,
        a: &EOCExecutableEntityRef,
        b: &EOCExecutableEntityRef,
        path: &str,
    ) -> Result<(), String> {
        self.compare_eoc_executable_entity_ref_abstract(other, a.base(), b.base(), path)?;
        if a.get_bsw_module_instance_ref() != b.get_bsw_module_instance_ref() {
            return Err(format!("{path}: BSW_MODULE_INSTANCE_REF mismatch"));
        }
        if a.get_component_i_ref() != b.get_component_i_ref() {
            return Err(format!("{path}: COMPONENT_I_REF mismatch"));
        }
        if a.get_executable_ref() != b.get_executable_ref() {
            return Err(format!("{path}: EXECUTABLE_REF mismatch"));
        }
        let list_a = a.get_successor_refs();
        let list_b = b.get_successor_refs();
        if list_a.len() != list_b.len() {
            return Err(format!("{path}: SUCCESSOR_REFS length mismatch"));
        }
        for (index, (x, y)) in list_a.iter().zip(list_b.iter()).enumerate() {
            let x = self.ref_types.get(*x).ok_or_else(|| {
                format!("{path}.SUCCESSOR_REFS[{index}]: id not found in own arena")
            })?;
            let y = other.ref_types.get(*y).ok_or_else(|| {
                format!("{path}.SUCCESSOR_REFS[{index}]: id not found in other arena")
            })?;
            self.compare_ref_type(other, x, y, &format!("{path}.SUCCESSOR_REFS[{index}]"))?;
        }
        Ok(())
    }

    pub(crate) fn compare_eoc_executable_entity_ref_abstract(
        &self,
        other: &Document,
        a: &EOCExecutableEntityRefAbstract,
        b: &EOCExecutableEntityRefAbstract,
        path: &str,
    ) -> Result<(), String> {
        self.compare_identifiable(other, a.base(), b.base(), path)?;
        let list_a = a.get_direct_successor_refs();
        let list_b = b.get_direct_successor_refs();
        if list_a.len() != list_b.len() {
            return Err(format!("{path}: DIRECT_SUCCESSOR_REFS length mismatch"));
        }
        for (index, (x, y)) in list_a.iter().zip(list_b.iter()).enumerate() {
            let x = self.ref_types.get(*x).ok_or_else(|| {
                format!("{path}.DIRECT_SUCCESSOR_REFS[{index}]: id not found in own arena")
            })?;
            let y = other.ref_types.get(*y).ok_or_else(|| {
                format!("{path}.DIRECT_SUCCESSOR_REFS[{index}]: id not found in other arena")
            })?;
            self.compare_ref_type(
                other,
                x,
                y,
                &format!("{path}.DIRECT_SUCCESSOR_REFS[{index}]"),
            )?;
        }
        Ok(())
    }

    pub(crate) fn compare_eoc_executable_entity_ref_group(
        &self,
        other: &Document,
        a: &EOCExecutableEntityRefGroup,
        b: &EOCExecutableEntityRefGroup,
        path: &str,
    ) -> Result<(), String> {
        self.compare_eoc_executable_entity_ref_abstract(other, a.base(), b.base(), path)?;
        if a.get_let_data_exchange_paradigm() != b.get_let_data_exchange_paradigm() {
            return Err(format!("{path}: LET_DATA_EXCHANGE_PARADIGM mismatch"));
        }
        let list_a = a.get_let_interval_refs();
        let list_b = b.get_let_interval_refs();
        if list_a.len() != list_b.len() {
            return Err(format!("{path}: LET_INTERVAL_REFS length mismatch"));
        }
        for (index, (x, y)) in list_a.iter().zip(list_b.iter()).enumerate() {
            let x = self.ref_types.get(*x).ok_or_else(|| {
                format!("{path}.LET_INTERVAL_REFS[{index}]: id not found in own arena")
            })?;
            let y = other.ref_types.get(*y).ok_or_else(|| {
                format!("{path}.LET_INTERVAL_REFS[{index}]: id not found in other arena")
            })?;
            self.compare_ref_type(other, x, y, &format!("{path}.LET_INTERVAL_REFS[{index}]"))?;
        }
        if a.get_max_cycle_repetitions() != b.get_max_cycle_repetitions() {
            return Err(format!("{path}: MAX_CYCLE_REPETITIONS mismatch"));
        }
        if a.get_max_cycles() != b.get_max_cycles() {
            return Err(format!("{path}: MAX_CYCLES mismatch"));
        }
        if a.get_max_slots() != b.get_max_slots() {
            return Err(format!("{path}: MAX_SLOTS mismatch"));
        }
        if a.get_max_slots_per_cycle() != b.get_max_slots_per_cycle() {
            return Err(format!("{path}: MAX_SLOTS_PER_CYCLE mismatch"));
        }
        let list_a = a.get_nested_element_refs();
        let list_b = b.get_nested_element_refs();
        if list_a.len() != list_b.len() {
            return Err(format!("{path}: NESTED_ELEMENT_REFS length mismatch"));
        }
        for (index, (x, y)) in list_a.iter().zip(list_b.iter()).enumerate() {
            let x = self.ref_types.get(*x).ok_or_else(|| {
                format!("{path}.NESTED_ELEMENT_REFS[{index}]: id not found in own arena")
            })?;
            let y = other.ref_types.get(*y).ok_or_else(|| {
                format!("{path}.NESTED_ELEMENT_REFS[{index}]: id not found in other arena")
            })?;
            self.compare_ref_type(other, x, y, &format!("{path}.NESTED_ELEMENT_REFS[{index}]"))?;
        }
        let list_a = a.get_successor_refs();
        let list_b = b.get_successor_refs();
        if list_a.len() != list_b.len() {
            return Err(format!("{path}: SUCCESSOR_REFS length mismatch"));
        }
        for (index, (x, y)) in list_a.iter().zip(list_b.iter()).enumerate() {
            let x = self.ref_types.get(*x).ok_or_else(|| {
                format!("{path}.SUCCESSOR_REFS[{index}]: id not found in own arena")
            })?;
            let y = other.ref_types.get(*y).ok_or_else(|| {
                format!("{path}.SUCCESSOR_REFS[{index}]: id not found in other arena")
            })?;
            self.compare_ref_type(other, x, y, &format!("{path}.SUCCESSOR_REFS[{index}]"))?;
        }
        if a.get_triggering_event_ref() != b.get_triggering_event_ref() {
            return Err(format!("{path}: TRIGGERING_EVENT_REF mismatch"));
        }
        Ok(())
    }

    pub(crate) fn compare_execution_order_constraint(
        &self,
        other: &Document,
        a: &ExecutionOrderConstraint,
        b: &ExecutionOrderConstraint,
        path: &str,
    ) -> Result<(), String> {
        self.compare_timing_constraint(other, a.base(), b.base(), path)?;
        if a.get_base_composition_ref() != b.get_base_composition_ref() {
            return Err(format!("{path}: BASE_COMPOSITION_REF mismatch"));
        }
        if a.get_execution_order_constraint_type() != b.get_execution_order_constraint_type() {
            return Err(format!("{path}: EXECUTION_ORDER_CONSTRAINT_TYPE mismatch"));
        }
        if a.get_ignore_order_allowed() != b.get_ignore_order_allowed() {
            return Err(format!("{path}: IGNORE_ORDER_ALLOWED mismatch"));
        }
        if a.get_is_event() != b.get_is_event() {
            return Err(format!("{path}: IS_EVENT mismatch"));
        }
        let list_a = a.get_ordered_elements();
        let list_b = b.get_ordered_elements();
        if list_a.len() != list_b.len() {
            return Err(format!("{path}: ORDERED_ELEMENTS length mismatch"));
        }
        for (index, (x, y)) in list_a.iter().zip(list_b.iter()).enumerate() {
            if x != y {
                return Err(format!("{path}.ORDERED_ELEMENTS[{index}] mismatch"));
            }
        }
        if a.get_permit_multiple_references_to_ee() != b.get_permit_multiple_references_to_ee() {
            return Err(format!("{path}: PERMIT_MULTIPLE_REFERENCES_TO_EE mismatch"));
        }
        Ok(())
    }
}
