// @generated by tools/py2rust from py-armodel models/M2 (see PY_ARMODEL_VERSION). Do not edit.

//! generated from spec package: m2::autosar_templates::common_structure::swc_bsw_mapping

use slotmap::new_key_type;

new_key_type! {
    pub struct SwcBswMappingId;
    pub struct SwcBswRunnableMappingId;
    pub struct SwcBswSynchronizedModeGroupPrototypeId;
    pub struct SwcBswSynchronizedTriggerId;
}

use crate::m2::autosar_templates::generic_structure::general_template_classes::ar_object::ARObject;
use crate::m2::autosar_templates::generic_structure::general_template_classes::ar_object::ElementRef;
use crate::m2::autosar_templates::generic_structure::general_template_classes::ar_package::ARElement;
use crate::m2::autosar_templates::generic_structure::general_template_classes::identifiable::ShortNameFragmentId;
use crate::m2::autosar_templates::generic_structure::general_template_classes::stereotype_mixins::VariationPointCapable;
use crate::m2::autosar_templates::generic_structure::variant_handling::VariationPointId;
use crate::m2::autosar_templates::sw_component_template::components::instance_refs::PModeGroupInAtomicSwcInstanceRefId;
use crate::m2::autosar_templates::sw_component_template::components::instance_refs::PTriggerInAtomicSwcTypeInstanceRefId;
use crate::m2::msr::asam_hdo::admin_data::AdminDataId;
use crate::m2::msr::documentation::annotation::AnnotationId;
use crate::m2::msr::documentation::text_model::block_elements::DocumentationBlockId;
use crate::m2::msr::documentation::text_model::multilanguage_data::MultiLanguageOverviewParagraphId;
use crate::m2::msr::documentation::text_model::multilanguage_data::MultilanguageLongNameId;
use crate::Document;

/// spec class `SwcBswMapping`
/// Maps an SwcInternalBehavior to an BswInternalBehavior. This is required to coordinate the API generation and the scheduling for AUTOSAR Service Components, ECU Abstraction Components and Complex Driver Components by the RTE and the BSW scheduling mechanisms.
#[derive(Debug, Default)]
pub struct SwcBswMapping {
    base: ARElement,
    bsw_behavior_ref: Option<String>,
    runnable_mappings: Vec<SwcBswRunnableMappingId>,
    swc_behavior_ref: Option<String>,
    synchronized_mode_groups: Vec<SwcBswSynchronizedModeGroupPrototypeId>,
    synchronized_triggers: Vec<SwcBswSynchronizedTriggerId>,
}

impl SwcBswMapping {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn base(&self) -> &ARElement {
        &self.base
    }

    pub fn base_mut(&mut self) -> &mut ARElement {
        &mut self.base
    }

    pub fn get_bsw_behavior_ref(&self) -> Option<&str> {
        self.bsw_behavior_ref.as_deref()
    }

    pub fn set_bsw_behavior_ref(&mut self, value: impl Into<String>) -> &mut Self {
        self.bsw_behavior_ref = Some(value.into());
        self
    }

    pub fn get_runnable_mappings(&self) -> &[SwcBswRunnableMappingId] {
        &self.runnable_mappings
    }

    pub fn push_runnable_mapping(&mut self, value: SwcBswRunnableMappingId) {
        self.runnable_mappings.push(value);
    }

    pub fn get_swc_behavior_ref(&self) -> Option<&str> {
        self.swc_behavior_ref.as_deref()
    }

    pub fn set_swc_behavior_ref(&mut self, value: impl Into<String>) -> &mut Self {
        self.swc_behavior_ref = Some(value.into());
        self
    }

    pub fn get_synchronized_mode_groups(&self) -> &[SwcBswSynchronizedModeGroupPrototypeId] {
        &self.synchronized_mode_groups
    }

    pub fn push_synchronized_mode_group(&mut self, value: SwcBswSynchronizedModeGroupPrototypeId) {
        self.synchronized_mode_groups.push(value);
    }

    pub fn get_synchronized_triggers(&self) -> &[SwcBswSynchronizedTriggerId] {
        &self.synchronized_triggers
    }

    pub fn push_synchronized_trigger(&mut self, value: SwcBswSynchronizedTriggerId) {
        self.synchronized_triggers.push(value);
    }

    pub fn get_admin_data(&self) -> Option<AdminDataId> {
        self.base().base().base().base().get_admin_data()
    }

    pub fn set_admin_data(&mut self, value: AdminDataId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_admin_data(value);
        self
    }

    pub fn remove_admin_data(&mut self) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .remove_admin_data();
        self
    }

    pub fn get_annotations(&self) -> &[AnnotationId] {
        self.base().base().base().base().get_annotations()
    }

    pub fn push_annotation(&mut self, value: AnnotationId) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .push_annotation(value)
    }

    pub fn get_category(&self) -> Option<&str> {
        self.base().base().base().base().get_category()
    }

    pub fn set_category(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_category(value);
        self
    }

    pub fn get_desc(&self) -> Option<MultiLanguageOverviewParagraphId> {
        self.base().base().base().base().get_desc()
    }

    pub fn set_desc(&mut self, value: MultiLanguageOverviewParagraphId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_desc(value);
        self
    }

    pub fn get_introduction(&self) -> Option<DocumentationBlockId> {
        self.base().base().base().base().get_introduction()
    }

    pub fn set_introduction(&mut self, value: DocumentationBlockId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_introduction(value);
        self
    }

    pub fn get_uuid(&self) -> Option<&str> {
        self.base().base().base().base().get_uuid()
    }

    pub fn set_uuid(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_uuid(value);
        self
    }

    pub fn get_elements(&self) -> &[ElementRef] {
        self.base().base().base().base().get_elements()
    }

    pub fn push_element(&mut self, value: ElementRef) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .push_element(value)
    }

    pub fn get_long_name(&self) -> Option<MultilanguageLongNameId> {
        self.base().base().base().base().base().get_long_name()
    }

    pub fn set_long_name(&mut self, value: MultilanguageLongNameId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_long_name(value);
        self
    }

    pub fn get_short_name_fragments(&self) -> &[ShortNameFragmentId] {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_short_name_fragments()
    }

    pub fn push_short_name_fragment(&mut self, value: ShortNameFragmentId) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .push_short_name_fragment(value)
    }

    pub fn get_short_name(&self) -> Option<&str> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_short_name()
    }

    pub fn set_short_name(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_short_name(value);
        self
    }

    pub fn get_checksum(&self) -> Option<&str> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_checksum()
    }

    pub fn set_checksum(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_checksum(value);
        self
    }

    pub fn get_timestamp(&self) -> Option<&str> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_timestamp()
    }

    pub fn set_timestamp(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_timestamp(value);
        self
    }

    pub fn get_parent(&self) -> Option<ElementRef> {
        self.base().base().base().base().base().base().get_parent()
    }

    pub fn set_parent(&mut self, parent: Option<ElementRef>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_parent(parent);
        self
    }
}

/// spec class `SwcBswRunnableMapping`
/// Maps a BswModuleEntity to a RunnableEntity if it is implemented as part of a BSW module (in the case of an AUTOSAR Service, a Complex Driver or an ECU Abstraction). The mapping can be used by a tool to find relevant information on the behavior, e.g. whether the bswEntity shall be running in interrupt context.
#[derive(Debug, Default)]
pub struct SwcBswRunnableMapping {
    base: ARObject,
    variation_point_capable: VariationPointCapable,
    bsw_entity_ref: Option<String>,
    swc_runnable_ref: Option<String>,
}

impl SwcBswRunnableMapping {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn base(&self) -> &ARObject {
        &self.base
    }

    pub fn base_mut(&mut self) -> &mut ARObject {
        &mut self.base
    }

    pub fn variation_point_capable(&self) -> &VariationPointCapable {
        &self.variation_point_capable
    }

    pub fn variation_point_capable_mut(&mut self) -> &mut VariationPointCapable {
        &mut self.variation_point_capable
    }

    pub fn get_bsw_entity_ref(&self) -> Option<&str> {
        self.bsw_entity_ref.as_deref()
    }

    pub fn set_bsw_entity_ref(&mut self, value: impl Into<String>) -> &mut Self {
        self.bsw_entity_ref = Some(value.into());
        self
    }

    pub fn get_swc_runnable_ref(&self) -> Option<&str> {
        self.swc_runnable_ref.as_deref()
    }

    pub fn set_swc_runnable_ref(&mut self, value: impl Into<String>) -> &mut Self {
        self.swc_runnable_ref = Some(value.into());
        self
    }

    pub fn get_checksum(&self) -> Option<&str> {
        self.base().get_checksum()
    }

    pub fn set_checksum(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_checksum(value);
        self
    }

    pub fn get_timestamp(&self) -> Option<&str> {
        self.base().get_timestamp()
    }

    pub fn set_timestamp(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_timestamp(value);
        self
    }

    pub fn get_variation_point(&self) -> Option<VariationPointId> {
        self.variation_point_capable().get_variation_point()
    }

    pub fn set_variation_point(&mut self, value: VariationPointId) -> &mut Self {
        self.variation_point_capable_mut()
            .set_variation_point(value);
        self
    }
}

/// spec class `SwcBswSynchronizedModeGroupPrototype`
/// Synchronizes a mode group provided by a component via a port with a mode group provided by a BSW module or cluster.
#[derive(Debug, Default)]
pub struct SwcBswSynchronizedModeGroupPrototype {
    base: ARObject,
    variation_point_capable: VariationPointCapable,
    bsw_mode_group_ref: Option<String>,
    swc_mode_group_i_ref: Option<PModeGroupInAtomicSwcInstanceRefId>,
}

impl SwcBswSynchronizedModeGroupPrototype {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn base(&self) -> &ARObject {
        &self.base
    }

    pub fn base_mut(&mut self) -> &mut ARObject {
        &mut self.base
    }

    pub fn variation_point_capable(&self) -> &VariationPointCapable {
        &self.variation_point_capable
    }

    pub fn variation_point_capable_mut(&mut self) -> &mut VariationPointCapable {
        &mut self.variation_point_capable
    }

    pub fn get_bsw_mode_group_ref(&self) -> Option<&str> {
        self.bsw_mode_group_ref.as_deref()
    }

    pub fn set_bsw_mode_group_ref(&mut self, value: impl Into<String>) -> &mut Self {
        self.bsw_mode_group_ref = Some(value.into());
        self
    }

    pub fn get_swc_mode_group_i_ref(&self) -> Option<PModeGroupInAtomicSwcInstanceRefId> {
        self.swc_mode_group_i_ref
    }

    pub fn set_swc_mode_group_i_ref(
        &mut self,
        value: PModeGroupInAtomicSwcInstanceRefId,
    ) -> &mut Self {
        self.swc_mode_group_i_ref = Some(value);
        self
    }

    pub fn get_checksum(&self) -> Option<&str> {
        self.base().get_checksum()
    }

    pub fn set_checksum(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_checksum(value);
        self
    }

    pub fn get_timestamp(&self) -> Option<&str> {
        self.base().get_timestamp()
    }

    pub fn set_timestamp(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_timestamp(value);
        self
    }

    pub fn get_variation_point(&self) -> Option<VariationPointId> {
        self.variation_point_capable().get_variation_point()
    }

    pub fn set_variation_point(&mut self, value: VariationPointId) -> &mut Self {
        self.variation_point_capable_mut()
            .set_variation_point(value);
        self
    }
}

/// spec class `SwcBswSynchronizedTrigger`
/// Synchronizes a Trigger provided by a component via a port with a Trigger provided by a BSW module or cluster.
#[derive(Debug, Default)]
pub struct SwcBswSynchronizedTrigger {
    base: ARObject,
    variation_point_capable: VariationPointCapable,
    bsw_trigger_ref: Option<String>,
    swc_trigger_i_ref: Option<PTriggerInAtomicSwcTypeInstanceRefId>,
}

impl SwcBswSynchronizedTrigger {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn base(&self) -> &ARObject {
        &self.base
    }

    pub fn base_mut(&mut self) -> &mut ARObject {
        &mut self.base
    }

    pub fn variation_point_capable(&self) -> &VariationPointCapable {
        &self.variation_point_capable
    }

    pub fn variation_point_capable_mut(&mut self) -> &mut VariationPointCapable {
        &mut self.variation_point_capable
    }

    pub fn get_bsw_trigger_ref(&self) -> Option<&str> {
        self.bsw_trigger_ref.as_deref()
    }

    pub fn set_bsw_trigger_ref(&mut self, value: impl Into<String>) -> &mut Self {
        self.bsw_trigger_ref = Some(value.into());
        self
    }

    pub fn get_swc_trigger_i_ref(&self) -> Option<PTriggerInAtomicSwcTypeInstanceRefId> {
        self.swc_trigger_i_ref
    }

    pub fn set_swc_trigger_i_ref(
        &mut self,
        value: PTriggerInAtomicSwcTypeInstanceRefId,
    ) -> &mut Self {
        self.swc_trigger_i_ref = Some(value);
        self
    }

    pub fn get_checksum(&self) -> Option<&str> {
        self.base().get_checksum()
    }

    pub fn set_checksum(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_checksum(value);
        self
    }

    pub fn get_timestamp(&self) -> Option<&str> {
        self.base().get_timestamp()
    }

    pub fn set_timestamp(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_timestamp(value);
        self
    }

    pub fn get_variation_point(&self) -> Option<VariationPointId> {
        self.variation_point_capable().get_variation_point()
    }

    pub fn set_variation_point(&mut self, value: VariationPointId) -> &mut Self {
        self.variation_point_capable_mut()
            .set_variation_point(value);
        self
    }
}

impl Document {
    pub(crate) fn compare_swc_bsw_mapping(
        &self,
        other: &Document,
        a: &SwcBswMapping,
        b: &SwcBswMapping,
        path: &str,
    ) -> Result<(), String> {
        self.compare_ar_element(other, a.base(), b.base(), path)?;
        if a.get_bsw_behavior_ref() != b.get_bsw_behavior_ref() {
            return Err(format!("{path}: BSW_BEHAVIOR_REF mismatch"));
        }
        let list_a = a.get_runnable_mappings();
        let list_b = b.get_runnable_mappings();
        if list_a.len() != list_b.len() {
            return Err(format!("{path}: RUNNABLE_MAPPINGS length mismatch"));
        }
        for (index, (x, y)) in list_a.iter().zip(list_b.iter()).enumerate() {
            let x = self.swc_bsw_runnable_mappings.get(*x).ok_or_else(|| {
                format!("{path}.RUNNABLE_MAPPINGS[{index}]: id not found in own arena")
            })?;
            let y = other.swc_bsw_runnable_mappings.get(*y).ok_or_else(|| {
                format!("{path}.RUNNABLE_MAPPINGS[{index}]: id not found in other arena")
            })?;
            self.compare_swc_bsw_runnable_mapping(
                other,
                x,
                y,
                &format!("{path}.RUNNABLE_MAPPINGS[{index}]"),
            )?;
        }
        if a.get_swc_behavior_ref() != b.get_swc_behavior_ref() {
            return Err(format!("{path}: SWC_BEHAVIOR_REF mismatch"));
        }
        let list_a = a.get_synchronized_mode_groups();
        let list_b = b.get_synchronized_mode_groups();
        if list_a.len() != list_b.len() {
            return Err(format!("{path}: SYNCHRONIZED_MODE_GROUPS length mismatch"));
        }
        for (index, (x, y)) in list_a.iter().zip(list_b.iter()).enumerate() {
            let x = self
                .swc_bsw_synchronized_mode_group_prototypes
                .get(*x)
                .ok_or_else(|| {
                    format!("{path}.SYNCHRONIZED_MODE_GROUPS[{index}]: id not found in own arena")
                })?;
            let y = other
                .swc_bsw_synchronized_mode_group_prototypes
                .get(*y)
                .ok_or_else(|| {
                    format!("{path}.SYNCHRONIZED_MODE_GROUPS[{index}]: id not found in other arena")
                })?;
            self.compare_swc_bsw_synchronized_mode_group_prototype(
                other,
                x,
                y,
                &format!("{path}.SYNCHRONIZED_MODE_GROUPS[{index}]"),
            )?;
        }
        let list_a = a.get_synchronized_triggers();
        let list_b = b.get_synchronized_triggers();
        if list_a.len() != list_b.len() {
            return Err(format!("{path}: SYNCHRONIZED_TRIGGERS length mismatch"));
        }
        for (index, (x, y)) in list_a.iter().zip(list_b.iter()).enumerate() {
            let x = self.swc_bsw_synchronized_triggers.get(*x).ok_or_else(|| {
                format!("{path}.SYNCHRONIZED_TRIGGERS[{index}]: id not found in own arena")
            })?;
            let y = other.swc_bsw_synchronized_triggers.get(*y).ok_or_else(|| {
                format!("{path}.SYNCHRONIZED_TRIGGERS[{index}]: id not found in other arena")
            })?;
            self.compare_swc_bsw_synchronized_trigger(
                other,
                x,
                y,
                &format!("{path}.SYNCHRONIZED_TRIGGERS[{index}]"),
            )?;
        }
        Ok(())
    }

    pub(crate) fn compare_swc_bsw_runnable_mapping(
        &self,
        other: &Document,
        a: &SwcBswRunnableMapping,
        b: &SwcBswRunnableMapping,
        path: &str,
    ) -> Result<(), String> {
        Self::compare_ar_object(a.base(), b.base(), path)?;
        self.compare_variation_point_capable(
            other,
            a.variation_point_capable(),
            b.variation_point_capable(),
            path,
        )?;
        if a.get_bsw_entity_ref() != b.get_bsw_entity_ref() {
            return Err(format!("{path}: BSW_ENTITY_REF mismatch"));
        }
        if a.get_swc_runnable_ref() != b.get_swc_runnable_ref() {
            return Err(format!("{path}: SWC_RUNNABLE_REF mismatch"));
        }
        Ok(())
    }

    pub(crate) fn compare_swc_bsw_synchronized_mode_group_prototype(
        &self,
        other: &Document,
        a: &SwcBswSynchronizedModeGroupPrototype,
        b: &SwcBswSynchronizedModeGroupPrototype,
        path: &str,
    ) -> Result<(), String> {
        Self::compare_ar_object(a.base(), b.base(), path)?;
        self.compare_variation_point_capable(
            other,
            a.variation_point_capable(),
            b.variation_point_capable(),
            path,
        )?;
        if a.get_bsw_mode_group_ref() != b.get_bsw_mode_group_ref() {
            return Err(format!("{path}: BSW_MODE_GROUP_REF mismatch"));
        }
        if a.get_swc_mode_group_i_ref() != b.get_swc_mode_group_i_ref() {
            return Err(format!("{path}: SWC_MODE_GROUP_I_REF mismatch"));
        }
        Ok(())
    }

    pub(crate) fn compare_swc_bsw_synchronized_trigger(
        &self,
        other: &Document,
        a: &SwcBswSynchronizedTrigger,
        b: &SwcBswSynchronizedTrigger,
        path: &str,
    ) -> Result<(), String> {
        Self::compare_ar_object(a.base(), b.base(), path)?;
        self.compare_variation_point_capable(
            other,
            a.variation_point_capable(),
            b.variation_point_capable(),
            path,
        )?;
        if a.get_bsw_trigger_ref() != b.get_bsw_trigger_ref() {
            return Err(format!("{path}: BSW_TRIGGER_REF mismatch"));
        }
        if a.get_swc_trigger_i_ref() != b.get_swc_trigger_i_ref() {
            return Err(format!("{path}: SWC_TRIGGER_I_REF mismatch"));
        }
        Ok(())
    }
}
