// @generated by tools/py2rust from py-armodel models/M2 (see PY_ARMODEL_VERSION). Do not edit.

//! generated from spec package: m2::autosar_templates::adaptive_platform::application_design::port_interface

use slotmap::new_key_type;

new_key_type! {
    pub struct FieldId;
}

use crate::m2::autosar_templates::generic_structure::general_template_classes::ar_object::ElementRef;
use crate::m2::autosar_templates::generic_structure::general_template_classes::identifiable::ShortNameFragmentId;
use crate::m2::autosar_templates::generic_structure::general_template_classes::stereotype_mixins::VariationPointCapable;
use crate::m2::autosar_templates::generic_structure::variant_handling::VariationPointId;
use crate::m2::autosar_templates::sw_component_template::datatype::data_prototypes::AutosarDataPrototype;
use crate::m2::msr::asam_hdo::admin_data::AdminDataId;
use crate::m2::msr::data_dictionary::data_def_properties::SwDataDefPropsId;
use crate::m2::msr::documentation::annotation::AnnotationId;
use crate::m2::msr::documentation::text_model::block_elements::DocumentationBlockId;
use crate::m2::msr::documentation::text_model::multilanguage_data::MultiLanguageOverviewParagraphId;
use crate::m2::msr::documentation::text_model::multilanguage_data::MultilanguageLongNameId;
use crate::Document;

/// spec class `Field`
/// This meta-class represents the ability to define a piece of data that can be accessed with read and/or write semantics. It is also possible to generate a notification if the value of the data changes.
#[derive(Debug, Default)]
pub struct Field {
    base: AutosarDataPrototype,
    variation_point_capable: VariationPointCapable,
    has_getter: Option<String>,
    has_notifier: Option<String>,
    has_setter: Option<String>,
}

impl Field {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn base(&self) -> &AutosarDataPrototype {
        &self.base
    }

    pub fn base_mut(&mut self) -> &mut AutosarDataPrototype {
        &mut self.base
    }

    pub fn variation_point_capable(&self) -> &VariationPointCapable {
        &self.variation_point_capable
    }

    pub fn variation_point_capable_mut(&mut self) -> &mut VariationPointCapable {
        &mut self.variation_point_capable
    }

    pub fn get_has_getter(&self) -> Option<&str> {
        self.has_getter.as_deref()
    }

    pub fn set_has_getter(&mut self, value: impl Into<String>) -> &mut Self {
        self.has_getter = Some(value.into());
        self
    }

    pub fn get_has_notifier(&self) -> Option<&str> {
        self.has_notifier.as_deref()
    }

    pub fn set_has_notifier(&mut self, value: impl Into<String>) -> &mut Self {
        self.has_notifier = Some(value.into());
        self
    }

    pub fn get_has_setter(&self) -> Option<&str> {
        self.has_setter.as_deref()
    }

    pub fn set_has_setter(&mut self, value: impl Into<String>) -> &mut Self {
        self.has_setter = Some(value.into());
        self
    }

    pub fn get_type_t_ref(&self) -> Option<&str> {
        self.base().get_type_t_ref()
    }

    pub fn set_type_t_ref(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut().set_type_t_ref(value);
        self
    }

    pub fn get_sw_data_def_props(&self) -> Option<SwDataDefPropsId> {
        self.base().base().get_sw_data_def_props()
    }

    pub fn set_sw_data_def_props(&mut self, value: SwDataDefPropsId) -> &mut Self {
        self.base_mut().base_mut().set_sw_data_def_props(value);
        self
    }

    pub fn get_atp_type_ref(&self) -> Option<&str> {
        self.base().base().base().get_atp_type_ref()
    }

    pub fn set_atp_type_ref(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .set_atp_type_ref(value);
        self
    }

    pub fn get_admin_data(&self) -> Option<AdminDataId> {
        self.base().base().base().base().base().get_admin_data()
    }

    pub fn set_admin_data(&mut self, value: AdminDataId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_admin_data(value);
        self
    }

    pub fn remove_admin_data(&mut self) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .remove_admin_data();
        self
    }

    pub fn get_annotations(&self) -> &[AnnotationId] {
        self.base().base().base().base().base().get_annotations()
    }

    pub fn push_annotation(&mut self, value: AnnotationId) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .push_annotation(value)
    }

    pub fn get_category(&self) -> Option<&str> {
        self.base().base().base().base().base().get_category()
    }

    pub fn set_category(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_category(value);
        self
    }

    pub fn get_desc(&self) -> Option<MultiLanguageOverviewParagraphId> {
        self.base().base().base().base().base().get_desc()
    }

    pub fn set_desc(&mut self, value: MultiLanguageOverviewParagraphId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_desc(value);
        self
    }

    pub fn get_introduction(&self) -> Option<DocumentationBlockId> {
        self.base().base().base().base().base().get_introduction()
    }

    pub fn set_introduction(&mut self, value: DocumentationBlockId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_introduction(value);
        self
    }

    pub fn get_uuid(&self) -> Option<&str> {
        self.base().base().base().base().base().get_uuid()
    }

    pub fn set_uuid(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_uuid(value);
        self
    }

    pub fn get_elements(&self) -> &[ElementRef] {
        self.base().base().base().base().base().get_elements()
    }

    pub fn push_element(&mut self, value: ElementRef) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .push_element(value)
    }

    pub fn get_long_name(&self) -> Option<MultilanguageLongNameId> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_long_name()
    }

    pub fn set_long_name(&mut self, value: MultilanguageLongNameId) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_long_name(value);
        self
    }

    pub fn get_short_name_fragments(&self) -> &[ShortNameFragmentId] {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_short_name_fragments()
    }

    pub fn push_short_name_fragment(&mut self, value: ShortNameFragmentId) {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .push_short_name_fragment(value)
    }

    pub fn get_short_name(&self) -> Option<&str> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_short_name()
    }

    pub fn set_short_name(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_short_name(value);
        self
    }

    pub fn get_checksum(&self) -> Option<&str> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_checksum()
    }

    pub fn set_checksum(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_checksum(value);
        self
    }

    pub fn get_timestamp(&self) -> Option<&str> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_timestamp()
    }

    pub fn set_timestamp(&mut self, value: impl Into<String>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_timestamp(value);
        self
    }

    pub fn get_variation_point(&self) -> Option<VariationPointId> {
        self.variation_point_capable().get_variation_point()
    }

    pub fn set_variation_point(&mut self, value: VariationPointId) -> &mut Self {
        self.variation_point_capable_mut()
            .set_variation_point(value);
        self
    }

    pub fn get_parent(&self) -> Option<ElementRef> {
        self.base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .base()
            .get_parent()
    }

    pub fn set_parent(&mut self, parent: Option<ElementRef>) -> &mut Self {
        self.base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .base_mut()
            .set_parent(parent);
        self
    }
}

impl Document {
    pub(crate) fn compare_field(
        &self,
        other: &Document,
        a: &Field,
        b: &Field,
        path: &str,
    ) -> Result<(), String> {
        self.compare_autosar_data_prototype(other, a.base(), b.base(), path)?;
        self.compare_variation_point_capable(
            other,
            a.variation_point_capable(),
            b.variation_point_capable(),
            path,
        )?;
        if a.get_has_getter() != b.get_has_getter() {
            return Err(format!("{path}: HAS_GETTER mismatch"));
        }
        if a.get_has_notifier() != b.get_has_notifier() {
            return Err(format!("{path}: HAS_NOTIFIER mismatch"));
        }
        if a.get_has_setter() != b.get_has_setter() {
            return Err(format!("{path}: HAS_SETTER mismatch"));
        }
        Ok(())
    }
}
